### ISSUE TITLE
REST API developer guide feedback from usage in DSX

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#1012]
The guide says:

> Instead of a username and password, the constructor arguments should include the path to a vcap file, and the name of the Streaming Analytics service:
On DSX there is no file input. The API doc says you can use a file or a String but doesn't tell you where to get the info for the string.   So I pasted my credentials for my service but that was incorrect:
```
_creds = pasted credentials
sc = StreamingAnalyticsConnection(service_name="MySA-service", vcap_services=_creds)
```
Gave me this error:
```
    service_name = os.environ.get('STREAMING_ANALYTICS_SERVICE_NAME', None)
    225     # Get the service corresponding to the SERVICE_NAME
--> 226     services = vcap_services['streaming-analytics']
    227     creds = None
    228     for service in services:

KeyError: 'streaming-analytics'
```
This was correct:
```
 vs={'streaming-analytics': [{'name': service_name, 'credentials': json.loads (_creds)}]}
    cfg = {}
    cfg[ConfigParams.VCAP_SERVICES] = vs
    cfg[ConfigParams.SERVICE_NAME] = service_name
    sc = StreamingAnalyticsConnection(service_name="MySA-service", vcap_services=vs)
```
Then, I tried to get my instance:
`print(len(sc.get_instances())`
Returned 0
But 
`    print(sc.get_instance(id="5a0fb1cf-444f-41d8-955d-9a316fd8ce31"))`
Returned an  instance.
Is this a bug or am I using the API incorrectly?

**Comment by ddebrunner** [comment]
> On DSX there is no file input.

DSX supports files. For a while the DSX notebooks for streams used a scheme that wrote the creds into a file and then used that file.

**Comment by ddebrunner** [comment]
> Is this a bug or am I using the API incorrectly?

Issue #943

**Comment by markheger** [comment]
Please re-open if still an issue
