### ISSUE TITLE
Java API: VcapServices assumes VCAP_SERVICES env variable is JSON object

### ISSUE THREAD

**Issue by pgerv12** [IBMStreams/streamsx.topology#1013]
I set the `VCAP_SERVICES` env variable to a Bluemix credentials file, but when running with `STREAMING_ANALYTICS_SERVICE`, a JSON parsing error is thrown on the first line and first column.

If I set the env variable to the contents of the credentials file, then it works successfully.

Similar to the config property, if it is specified, the env variable should accept a JSON object string or a file.

**Comment by yvchan** [comment]
Open question for this, I'm assuming SERVICE_NAME can also be an environment variable like VCAP_SERVICES, so if SERVICE_NAME is not found, the code should check for environment variables as well?

@ddebrunner is there a testcase or two that I can run to make sure i don't break any assumptions with this?

**Comment by ddebrunner** [comment]
Ensure the sample Java bluemix app can run. We don't yet have automated testing against bluemix.

**Comment by ddebrunner** [comment]
`SERVICE_NAME` variable is too generic, Bluemix has many many services, and Python uses an existing variable name `STREAMING_ANALYTICS_SERVICE_NAME`.

**Comment by yvchan** [comment]
ok, i'll change the environment variable to `STREAMING_ANALYTICS_SERVICE_NAME`  I had searched, but  had trouble finding this documented anywhere.

**Comment by yvchan** [comment]
PR #1121 for testcase to keep this working.

**Comment by yvchan** [comment]
Closing this as PR #1121 has been added in.
