### ISSUE TITLE
StreamsConnection is incorrectly associated with an instance.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1035]
A `StreamsConnection` is a connection to a domain not a single instance, thus it should not have an instance field, or a `getInstance(id)` that sets(!) the id.

**Comment by yvchan** [comment]
instanceId will be removed form StreamsConnection.  I'm trying to get confirmation whether or not the streaming analytics connection is tied to one instance or not.  From the description of the available REST api's, it appears to be tied to only one, in which case, I"ll have the Streaming Analytics Connection tied to one instance name, and remove it from the Streams Connection object.

**Comment by yvchan** [comment]
pull request #1054
