### ISSUE TITLE
Problem with Python streams as input to  SPL operators 

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#1036]
The Python API allows you to invoke an SPL operator, but the operator that is invoked can't access the data on the Python stream because it is a stream of Python objects. So compilation fails if the operator is looking for specific attributes on the input stream, or if you attempt to pass through attributes from the Python stream to the output stream.

**Comment by ddebrunner** [comment]
Not sure this is really a problem as described. 

If you invoke an SPL operator from Python requiring SPL attribute 'a' for a schema that doesn't contain 'a' it's expected that it's an error.

**Comment by natashadsilva** [comment]
If it is working as expected then the documentation should clarify that SPL operators can't really be mixed with a Python topology without some conversion, and show how to do that conversion of data types, if it is possible.

**Comment by ddebrunner** [comment]
I guess I'm just confused what you expect to happen, when say an SPL operator is invoked that expects an SPL attribute 'id' or 'a' against a stream of  untyped Python objects.

**Comment by ddebrunner** [comment]
I think this is covered by #1074
