### ISSUE TITLE
Support windowing.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1072]
Initial potential api added in #1053 

* [x] Resolve issues in #1211 
* [ ] Support partitioning.
* [x] Support structured schemas (blob/dict) with special handling for blob. The blob is a memory view, the window shouldn't store a memory view since when the process method returns, the memory will be invalid. Need to copy blobs as we insert into the window.

**Comment by natashadsilva** [comment]
Any plans to add support for grouping and partitioning?
The grouping support is available in by invoking the  Aggregate operator from the standard package, but it only provides basic functions (max, min, count, average, etc.)

**Comment by ddebrunner** [comment]
Partitioning is being worked on in Python - See #2104

Grouping would be implemented by the aggregate function, e.g. using Pandas data frames.
