### ISSUE TITLE
Adopt java.util.streams.Stream-isms?

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#108]
I took a peek at java.util.stream.Stream.  I don't know how much it and SparkStreaming mimic each other wrt terminology, etc but the common use of map()/flatMap() and reduce() jumped out at me.

A quick once over yielded these observations / questions:

Consider using Java Stream terminology? e.g.,
- "map()" vs "transform()"
- "reduce()","collect()"  vs  "aggregate()"
- "generate()", "iterate()", "of()"  vs  "source()","{endless,limited}Source()", "constants()", "numbers()", "strings()"
- "forEach()"  vs  "sink()"

Consider offering analogs to Java Stream predefined Stream types and operations that yield them? e.g.,
- {Double,Long,Int}Stream and Stream.mapTo{Double,Long,Int}()
- as{Double,Long,Int}Stream() on {Double,Long,Int}Stream

Consider offering analogs to Java Stream predefined transforms,reductions,filters?  e.g.,
- distinct(),min(),max(),sorted()
- sum(),average(),range[Closed]() on {Double,Long,Int}Stream

**Comment by ddebrunner** [comment]
In real streaming applications I'm not sure how useful streams of just doubles, ints or longs are. It's useful to in the Java api to sum a value etc in a method, but not as a top-level stream type.

**Comment by ddebrunner** [comment]
Also, while Java streams say infinite streams are supported, many of the methods seem more suited to  collections of limited size, whereas the Java Application API for IBM Streams is targeted at infinite streams.

**Comment by ddebrunner** [comment]
We can always add methods like 'map' that are the same as 'transform', by map just calling transform, effectively alias methods, the Java names seem to be from a map/reduce background, rather than a streaming background.

**Comment by dlaboss** [comment]
In my quick review of Stream I attempted to omit operations that couldn't have a sensible analog in a real streaming context.  So the analog for some Stream operations translate to operations on a window rather then the whole stream: distinct(),sorted(),min(),max(),range() (supported either by the tuple T implementing Comparable, or perhaps being supplied a Comparable<T>).  sum() and average() would be window based.
Fwiw, I see that SparkStreaming has both map()/flatMap() as well as a transform().
(flatMap() says its the same as map() except each input item can yield 0 or more output items)

**Comment by ddebrunner** [comment]
So flatMap is similar to multiTransform(), while multiTransform() is not a great name, flatMap seems like a piece of IKEA furniture. I guess it's for flatten map, but when the input object is not a map, e.g.  transforming an audio wave form to words as text it makes little sense.

**Comment by scotts** [comment]
The Java names might be inspired by MapReduce, but both are strongly influenced by functional programming. In this context, "map" does not mean the data structure, but the operation of *mapping* a domain to a range using a particular function.

I've gotten used to `transform`, but `map` is the accepted name for this operation in other languages. However, something to consider is that if we adopt `map` as the name, it would imply that we should adopt `reduce` instead of `aggregate`. While the programming languages world does not call summarizing a large set of data an aggregation, the data management world does.

**Comment by ddebrunner** [comment]
`map`, `forEach` and `flatMap` have been added as aliases (in reality they are the actual method, and the "non-standard" names are the aliases).
