### ISSUE TITLE
Maintain cookies on Java REST api.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1099]
_Process the HTTP status code, response headers, and any response message that are returned. Retain cookies that are returned in the Set-Cookie header so that they can be sent with subsequent requests._

https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.0.0/com.ibm.streams.dev.doc/doc/restapi-http.html

This article should help (search for cookie)
https://developer.ibm.com/streamsdev/docs/example-using-rest-apis-chart-streaming-data/

**Comment by yvchan** [comment]
@ddebrunner I took a closer look at the java tracing of the connections, and it looks like cookies are enabled (NOTE: i snipped out some info)

```
RequestAddCookies - CookieSpec selected: best-match
2017/06/26 09:42:02:570 EDT [DEBUG] wire - http-outgoing-0 << "Set-Cookie: <snip>; Path=/; Secure; HttpOnly[\r][\n]"
2017/06/26 09:42:02:570 EDT [DEBUG] wire - http-outgoing-0 << "Cache-Control: no-store, no-cache=set-cookie[\r][\n]"
2017/06/26 09:42:02:573 EDT [DEBUG] headers - http-outgoing-0 << Set-Cookie: <snip>; Path=/; Secure; HttpOnly
2017/06/26 09:42:02:573 EDT [DEBUG] headers - http-outgoing-0 << Cache-Control: no-store, no-cache=set-cookie
2017/06/26 09:42:02:581 EDT [DEBUG] ResponseProcessCookies - Cookie accepted [<snip>", version:0, domain:<snip>, path:/, expiry:null]
2017/06/26 09:42:02:638 EDT [DEBUG] RequestAddCookies - CookieSpec selected: best-match
2017/06/26 09:42:02:639 EDT [DEBUG] RequestAddCookies - Cookie [version: 0][name: <snip>][value: 6d6796b8-003c-466b-8c24-839dcc782a31][domain: <snip>][path: /][expiry: null] match [(secure)<snip>:8443/streams/rest/instances/development/jobs]
```

I haven't explicitly set a cookie manager/provider, however the http.fluent client that is used has default cookie management as it has an option to disable cookie management.  Let me know if this is sufficient, or if there's something specific that's missing.  thanks!

**Comment by ddebrunner** [comment]
Which is the method to disable cookie management? I'm not seeing anything obvious here:
https://hc.apache.org/httpcomponents-client-4.3.x/fluent-hc/apidocs/

Looking at the source of Executor cookieStore is set to null.

Did you check if a subsequent request used the same cookie? The request will always have a cookie, but the issue is do we reuse it on future requests.

**Comment by yvchan** [comment]
the version, name, value, path and expiry all match, and I see the following through-out the trace file i created (after the initial Cookie accepted, and no other Cookie accepted tracepoints are logged).

```
2017/06/26 09:42:03:526 EDT [DEBUG] RequestAddCookies - CookieSpec selected: best-match
2017/06/26 09:42:03:526 EDT [DEBUG] RequestAddCookies - Cookie [version: 0][name: <snip>][value: <snip>][domain: <snip>][path: /][expiry: null] **match** [(secure)<snip>:8443/streams/rest/instances/development/jobs/2887/operators/Counter_1_Read_UnboundedCountingSource_/metrics]
2017/06/26 09:42:03:528 EDT [DEBUG] headers - http-outgoing-0 >> Cookie: DOM_eden101=6d6796b8-003c-466b-8c24-839dcc782a31
2017/06/26 09:42:03:528 EDT [DEBUG] headers - http-outgoing-0 >> Cookie2: $Version=1
2017/06/26 09:42:03:528 EDT [DEBUG] wire - http-outgoing-0 >> "Cookie: DOM_eden101=6d6796b8-003c-466b-8c24-839dcc782a31[\r][\n]"
2017/06/26 09:42:03:528 EDT [DEBUG] wire - http-outgoing-0 >> "Cookie2: $Version=1[\r][\n]"
```

As for the code;
https://hc.apache.org/httpcomponents-client-ga/fluent-hc/xref/org/apache/http/client/fluent/Executor.html#L100  shows that Executor is using HttpClientBuilder to create the clients, and that has a method to disableCookieManagement() here;
http://hc.apache.org/httpcomponents-client-4.3.x/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#disableCookieManagement()

**Comment by yvchan** [comment]
the http-outgoing are showing the re-use of the cookie, so am going to close this with no code changes.
