### ISSUE TITLE
Committer Nomination: Yvonne Chan @yvchan

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1103]
I propose adding Yvonne as a committer to `streamsx.topology`.

Yvonne contributed the Java REST api code (*) developing incrementally over the last few months, responding to any requests/changes quickly.

* https://github.com/IBMStreams/streamsx.topology/tree/master/java/src/com/ibm/streamsx/rest

**Comment by dlaboss** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by cancilla** [comment]
+1

**Comment by wmarshall484** [comment]
+1

**Comment by chanskw** [comment]
Added Yvonne as committer.  Welcome!
