### ISSUE TITLE
Add a split function

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#113]
On TStream something like:

`List<TStream<T>> split(int n, IntFunction<T> splitter)`

Returns N streams, for each tuple on the stream  splitter.apply(tuple) is called, the return value  r determines the destination:
if  r < 0 the tuple is discarded
else it is sent to the stream at position (r % n) in the returned array.

**Comment by dlaboss** [comment]
After discussion w/Dan decided to define ToIntFunction<T> => int applyAsInt(T v)  to mirror the corresponding java8 functionality (and java8 IntFunction<R> is about the opposite of what was proposed above).
