### ISSUE TITLE
DEVELOPMENT.md should mention dependency on `future` module

### ISSUE THREAD

**Issue by johnmac-ibm** [IBMStreams/streamsx.topology#1131]
I just tried to build master and it failed with a trace ending in:

```
     [exec]   File "/home/johnmac/work/beam/dev/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/runtime.py", line 7, in <module>
     [exec]     from past.builtins import basestring
     [exec] ImportError: No module named 'past'
```

A bit of poking around and bugging someone found that's in the `future` module, which I didn't have installed, and sure enough `pip3 install future` did the trick.

If it's a dependency for building, I think it should be mentioned in `DEVELOPMENT.md` like the `sphinx` ones are for docs.

**Comment by ddebrunner** [comment]
Not applicable anymore now that 2.7 support has been dropped.
