### ISSUE TITLE
Add the ability to partition based upon a function.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#114]
If a Java type doesn't implement Keyable then still allow partitioning (window or parallel).

Maybe add this to Topology

`<T,K> void registerKeyFunction(Function<T,K> keyGetter, Class<T> tupleClass)`

Useful when the tuple class is an class from a library, or you don't want to depend on the Java Application API because your classes are used elsewhere.

**Comment by dlaboss** [comment]
Interesting idea having a topology registry for this.

Also consider parallel(..., Function<T,K> keyGetter) in case different parts of the same application might want different partitioning behavior for the same type?

**Comment by ddebrunner** [comment]
Right, could also use the function you just added for Split

parallel(..., ToIntFunction<T> channelSelector)

**Comment by ddebrunner** [comment]
Though the issue with the ToIntFunction channelSelector overload is that I don't believe UDP will guarantee which channel a tuple will go to, only that all tuples with the same hash code go to the same channel. E.g. if the channelSelector function returned 0, then the tuple might actually go to channel 2.

**Comment by ddebrunner** [comment]
Added through keyed streams and windows.
