### ISSUE TITLE
the REST Api objects will throw a 404 on refresh() if the object disappears

### ISSUE THREAD

**Issue by yvchan** [IBMStreams/streamsx.topology#1142]
Job.refresh() or Metric.refresh() will throw a RESTException if the code encounters a 404 (object not found).  This is normal since things like jobs or metrics can disappear after they've finished or been canceled.

In this code: 
https://github.com/IBMStreams/streamsx.topology/blob/master/java/src/com/ibm/streamsx/rest/Element.java#L64-L80

we could add some smarter logic in to catch the 404 and perhaps set the object to a state to say it's gone or invalid

**Comment by markheger** [comment]
user is responsible for handling exceptions in this case
