### ISSUE TITLE
Rename StreamingAnalyticsConnection.createInstance to newInstance.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1146]
I find "createInstance" confusing, as it can be thought of a creating a Streams instance.

See here for recommended names of factory methods.

http://www.informit.com/articles/article.aspx?p=1216151

**Comment by ddebrunner** [comment]
@yvchan Thoughts?

**Comment by yvchan** [comment]
i have no objection to changing this to newInstance.

**Comment by ddebrunner** [comment]
Already part of the api.
