### ISSUE TITLE
Automatically include etc directory for Python topologies

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.topology#1163]
In SPL applications, the etc directory automatically gets included as part of the bundle. Would it make sense to also do this in the case of Python topologies? 

In the meantime, how can I include my etc directory with config info?

**Comment by ddebrunner** [comment]
@Alex-Cook4 
PR #1191 adds two methods:

`Topology.add_file_dependency(path, location)` - Adds the file or directory defined by `path` into the application directory defined by `location` which can be `etc` or `opt`. At runtime the file can be obtained by SPL applications/operators using the existing mechanisms to get the application directory or by Python applications using the new function below.

`streamsx.ec.get_application_directory()` - Return the (runtime) application directory .

**Comment by Alex-Cook4** [comment]
+1 These look like good solutions.
