### ISSUE TITLE
Is there a way to control how long an application is deployed for during test?

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.topology#1169]
How does the Tester know when to consider a test complete and cancel a job? Is this configurable?

**Comment by ddebrunner** [comment]
For distributed/cloud when all the conditions become valid or one fails, or the job has an issue.

For standalone when the app exists.

**Comment by Alex-Cook4** [comment]
If we were waiting on 10 tuples, and got stuck at 9. What would cause it to get shutdown? Since in that case the condition still has the opportunity to become valid at any time in the future.

**Comment by ddebrunner** [comment]
There is a timeout if the conditions do not become valid and none fail.  It's somewhat of a smart timeout as if a condition is making progress, e.g. it moved from 8 to 9 tuples the timeout is extended. This is to avoid a the case where a hard timeout is usually sufficient but sometimes fails due the machine being busy etc.

**Comment by Alex-Cook4** [comment]
Is that explanation in the docs? If not, I think it would be useful to add.
