### ISSUE TITLE
Source location SPL note annotation formatting incorrect for some Java operators

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.topology#1174]
Some annotations have an extra `"sourcelocation"` property in `text` (first 2 in bad examples below), which does not match the format in this [wiki](https://github.com/IBMStreams/streamsx.topology/wiki/SPL-Annotations#source-location) page. And some point to the internal topology code (last one in bad examples).

Good examples:
- `@spl_note(id="__spl_sourcelocation", text='{"file":"FilterEcho.java","class":"simple.FilterEcho","method":"main","line":56,"api.method":"strings"}')`
- `@spl_note(id="__spl_sourcelocation", text='{"file":"SubscribeBeacon.java","class":"topic.SubscribeBeacon","method":"main","line":40,"api.method":"print"}')`

Bad examples:
- `@spl_note(id="__spl_sourcelocation", text='{"sourcelocation":[{"file":"FilterEcho.java","class":"simple.FilterEcho","method":"main","line":66,"api.method":"filter"}]}')`
- `@spl_note(id="__spl_sourcelocation", text='{"sourcelocation":[{"file":"PublishBeacon.java","class":"topic.PublishBeacon","method":"main","line":58,"api.method":"throttle"}]}')`
- `@spl_note(id="__spl_sourcelocation", text='{"sourcelocation":[{"file":"Topology.java","class":"com.ibm.streamsx.topology.Topology","method":"subscribe","line":497,"api.method":"invokeSource"}]}')`

**Comment by ddebrunner** [comment]
@queeniema Any code examples for the bad ones?

**Comment by queeniema** [comment]
- [FilterEcho.java](https://github.com/IBMStreams/streamsx.topology/blob/master/samples/java/functional/src/simple/FilterEcho.java): `TStream<String> filtered = echo.filter(new Predicate<String>() {...});`
- [PublishBeacon.java](https://github.com/IBMStreams/streamsx.topology/blob/master/samples/java/functional/src/topic/PublishBeacon.java): `BeaconStreams.beacon(topology).throttle(100, TimeUnit.MILLISECONDS).publish(topic);`
- [SubscribeBeacon.java](https://github.com/IBMStreams/streamsx.topology/blob/master/samples/java/functional/src/topic/SubscribeBeacon.java): `TStream<BeaconTuple> beacon = topology.subscribe(topic, BeaconTuple.class);`
