### ISSUE TITLE
Define how SPL toolkits are copied into build archives.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1184]
Currently for remote builds the entire toolkit is copied into the build archive, while this works it can end up including additional information that is not required, increasing upload time, e.g. the `doc` directory.

Reference on SPL toolkit structure:

https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.1/com.ibm.streams.dev.doc/doc/toolkitstructure.html

By convention these top-level folders should be excluded from being copied into a build archive:

- `doc`
- `output`
- `samples`
- `opt/client` (see below)

A toolkit should be able to provide info about what *else* is not required, typically client side code. This should be a convention (like the toolkit structure) as there is no single tool that creates build archives. I propose that the folder `opt/client` and its contents are not intended to be copied into a build archive.

**Comment by cancilla** [comment]
What would typically go in `opt/client`? I could not find any info in the Streams docs regarding the intended structure under `opt/`. All I could find was a short blurb stating that `opt` is intended for *other* artifacts (ref: https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.1/com.ibm.streams.dev.doc/doc/toolkitartifacts.html)

**Comment by cancilla** [comment]
As far as the dirs you list, I can't think of any other standard toolkit dirs we would want excluded by default. Any thoughts on how a toolkit would "provide info about what *else* is not required"?

**Comment by pgerv12** [comment]
I'd have to look but when a toolkit is added by the user could there be an optional list of directory names that could be excluded?

**Comment by ddebrunner** [comment]
> Any thoughts on how a toolkit would "provide info about what else is not required"?

@cancilla That's the concept of `opt/client`, anything under there is not added to the build archive.

**Comment by ddebrunner** [comment]
> What would typically go in opt/client?

@cancilla  Flippant answer, anything the toolkit developer doesn't want to go in a build archive.

But any artifacts that are solely used in a client side role, e.g. code for a jmx application that interacts with operators in the toolkit.  Maybe scripts used by customers to create SPL types (doesn't JSON have something like that?).

For `topology` it is jars and other files that relate to submitting the build archive.

**Comment by ddebrunner** [comment]
> I'd have to look but when a toolkit is added by the user could there be an optional list of directory names that could be excluded?

I'd like it to be part of the toolkit, not having to be defined by every user of the toolkit.

**Comment by ddebrunner** [comment]
@cancilla @pgerv12 

`bin` is an interesting one, should it be omitted?

 `com.ibm.streams.teda` and `com.ibm.streams.text` could probably be used to compile SPL apps without `bin`, but `com.ibm.streamsx.topology` might need `bin` though its code is moving anyway.
