### ISSUE TITLE
A user provided name with a 'dot' can result in duplicate names.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1199]
If multiple stream/operator names are set with a common portion after a dot then a duplicate identifier is hit during spl compilation, e.g.:

```
     s = hw.filter(lambda x : True, name = "One.A")
     s = s.filter(lambda x : True, name = "Two.A")
```

**Comment by pgerv12** [comment]
Java: https://github.com/IBMStreams/streamsx.topology/blob/master/java/src/com/ibm/streamsx/topology/generator/spl/SPLGenerator.java#L556

Python (I believe): https://github.com/IBMStreams/streamsx.topology/blob/master/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py#L53
