### ISSUE TITLE
Getting the application directory at declaration time

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.topology#1208]
Currently [streamsx.ec.get_application_directory()](http://ibmstreams.github.io/streamsx.topology/doc/releases/1.7/pythondoc/streamsx.ec.html#streamsx.ec.get_application_directory) can only be called at runtime, not at declaration time. For example:

```python
    topo = Topology()
    topo.add_file_dependency(temp.name, 'etc')

    s = topo.source(['A'])
    s = s.filter(lambda x : os.path.isdir(ec.get_application_directory()))
```

There are cases where I want to create a source stream from an application directory. For example:

```python
    directory = sys.argv[1]
    topo = Topology("grep")

    topo.add_file_dependency(directory, "etc")
    lines = topo.source(util_functions.DirectoryWatcher(ec.get_application_directory()))
```

**Comment by ddebrunner** [comment]
If `DirectoryWatcher` is your own class then you could set it up so that if the path passed is relative then it is relative to the app dir at runtime.

**Comment by ddebrunner** [comment]
Something like:
```
class DirectoryWatcher(object):
    def __init__(self, directory):
        self.directory = directory

   def __enter__(self):
        if not os.path.isabs(self.directory):
            self.directory = os.path.join(ec.get_application_directory(), self.directory)

    def __exit__(self, exc_type, exc_value, traceback):
        pass
```
See: http://ibmstreams.github.io/streamsx.topology/doc/releases/1.6/pythondoc/streamsx.topology.topology.html#initialization-and-shutdown

**Comment by queeniema** [comment]
Thanks! That worked, along with making this change:

```python
lines = topo.source(util_functions.DirectoryWatcher(os.path.join('etc', os.path.basename(directory))))
```

**Comment by ddebrunner** [comment]
PR #1209 makes `add_file_dependency` return the path of the dependency relative to app dir, so the code would change to:
```
rtp = topo.add_file_dependency(directory, "etc")
lines = topo.source(util_functions.DirectoryWatcher(rtp))
```
