### ISSUE TITLE
Implementation changes for Python windowing support

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#1211]
* [x] Fix naming scheme for SPLPY_TUPLE_MAP macro in Aggregate operator, and any other names that need changing.
* [x] Create c++ functions to convert SPL value to PyObject * value, that doesn't require wrapping the `streamsx.runtime.identity` function.
* [x] Obtain window definition through the code generation API, not using operator parameters.
* [x] Rename operator from CCWindow to Aggregate.
* [x] Window tests, such as the string tests, should use operations that use type-specific functions, such as concatenation.
* [x] Remove loadAndWrapCallable function in `splpyFuncOp` 
* [x] Resolve list/tuple - `aggregate` says a list of tuples is passed, implementation passes a tuple of tuples.
* [x] Rename pickle_in_object_out to object_in_object_out
* [x] Macro rename
* [x] Don’t use identity function, have more <% if $pystyle == ‘string’ %> type switches for handling it in c++ code
* [x] Find a better name than funcop_
* [x] Remove schema parameter from aggregate

**Comment by wmarshall484** [comment]
How about only passing an iterable to the aggregate operator instead of a list/tuple?

**Comment by ddebrunner** [comment]
> Create streamsx.runtime.object_in_*_out functions. Use these instead of pickle_in_*_out.
I'm creating these (but not modifying the window code) as I need them for supporting named tuples.

**Comment by ddebrunner** [comment]
@wmarshall484 See #1232

**Comment by ddebrunner** [comment]
> How about only passing an iterable to the aggregate operator instead of a list/tuple?
This does create the issue that you can't tell how many tuples are in the window, though maybe a Pythonic way is just to try `len(tuples)` and it if fails you just don't get to know the length.

**Comment by ddebrunner** [comment]
unchecked three items as they have not yet been done, pr's are not yet merged.

**Comment by wmarshall484** [comment]
Fixed in #1273 and #1275
