### ISSUE TITLE
Project page documentation issues

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#1229]
Just a couple things I've noticed:
1) getting started only has information for Java - if it is meant to be this way then it shouldn't be a top level link. Otherwise it would be nice to add info for Python
2) Documentation page does not have a link to the python developer guide

**Comment by ddebrunner** [comment]
@natashadsilva Can you be more specific?

http://ibmstreams.github.io/streamsx.topology/
 I see the gettting started is under Java/Scala.
The Python getting started is under Python.

Maybe you are looking at a different page?

**Comment by natashadsilva** [comment]
I'm referring to the "Getting Started" link in the horizontal navigation bar at the top of the page between "Documentation" and "FAQ".
It goes to this link http://ibmstreams.github.io/streamsx.topology/gettingstarted.html which is Java specific.
Seocndly,  The [documentation link](http://ibmstreams.github.io/streamsx.topology/doc.html) just points to the  Python API documentation with no link to the development guide.
However, the Java API doc on the same page has links to both the Java doc and the development guide for Java.

**Comment by markheger** [comment]
* documentation page is already updated
* "getting started" is still an issue as described above and needs to be updated
