### ISSUE TITLE
Support passing structured schemas as Python tuples.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1235]
Currently a structured schema is passed into a Python callable as a dict:

`tuple<rstring a, int32 b>` is passed as `{'a': 'hello', 'b': 42}`

Allow passing as a

- [x] `tuple` - would be passed as `('hello', 42)`
- [x] `collections.namedtuple` - would be passed as a named tuple, e.g. `t.a == 'hello'` and `t.b == 42`
- [ ] `typing.NamedTuple` - would be passed as a named tuple, e.g. `t.a == 'hello'` and `t.b == 42` and include type hints (Python 3.5 only).
- [ ] specific named tuple - A named tuple class provided by the user.

Concept is to have additional methods on `StreamSchema` to indicate how the tuples should be handled, e.g.
```
   s.map(myfunc, schema=StreamSchema('tuple<rstring a, int32 b>').as_tuple())
```

**Comment by ddebrunner** [comment]
@chanskw FYI plus the example in PR #1236

**Comment by ddebrunner** [comment]
named tuple support added in 1.9 under #1376

**Comment by markheger** [comment]
supported
