### ISSUE TITLE
aggregate maintains the input schema.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1238]
aggregate deviates from other methods by maintaining the input schema for a transformation, all others (i.e. `map` & `flat_map`) default to the Python schema (since it's a Python transformation).

Currently only `map` allows the schema to be changed.

Should it be consistent with map and flat_map?

**Comment by ddebrunner** [comment]
@wmarshall484  Is this done?

**Comment by wmarshall484** [comment]
Yes
