### ISSUE TITLE
streamsx version clashes between multiple SPL toolkits with Python ops.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1250]
When an SPL python operator is invoked its `streamsx` classes (and hence its behaviour when annotated with `@spl.map()` etc.) can come from one of four locations:

1. Its toolkit (`opt/.__splpy/packages`)
1. Another toolkit with a python operator in the same PE  (`othertoolkit/opt/.__splpy/packages`)
1. The topology toolkit if the operator is invoked from the topology API (`com.ibm.streamsx.topology/opt/python/packages`)
1. The system python path, e.g with the system having installed `streamsx` (`pip install streamsx`).

The issue comes when an older version is loaded and becomes the defacto version, or the older toolkit gets its `packages` directory earlier on `sys.path` than a toolkit requiring a new version. Order of when a module is loaded also becomes significant, as a `streamsx` module might be loaded during the operator invocation or later during initialization.

PR #1248 includes a test that has an expected failure for this case (actually case 2).

**Comment by ddebrunner** [comment]
Note that for a decorated SPL python operator:

- extraction which creates the C++ primitive operator artifacts occurs at one release level, when the toolkit is being developed and released, e.g. say `1.7`.
- decorating of the class/function also occurs at runtime with the loaded version of `streamsx.spl`, which could be `1.9`.

Thus

1. changes to the decorators must maintain backwards compatibility including continuing to work with the primitive operator cgt/xml files previously generated.

**Comment by ddebrunner** [comment]
Current work around in SPL apps would be to exlocate operators from toolkits with different versions.

Or rextract the toolkits before building the app.

**Comment by markheger** [comment]
workaround is available, either rebuild or exlocate
