### ISSUE TITLE
Can I parallelize a source?

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#128]
Is it possible to use `parallel()` on a source?  I didn't see a way.

**Comment by wmarshall484** [comment]
There is not currently a way to parallelize sources. This is on the to-do list, but is currently listed as a lower priority than other features.

The following features are currently not supported:
*parallel sources
*multiple input/output ports to parallel regions
*cats cradle parallelism for regions that are adjacent to each other
*unions/joins between parallelized TStreams

If you think of any other important parallel() features to include, let me know.

**Comment by ddebrunner** [comment]
See #1398
