### ISSUE TITLE
ViewDemo error with SSL

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.topology#1289]
I can connect to the rest api using rest.StreamsConnection and disable the SSL check with sc.session.verify = False

But all views acres give me this error.
<img width="859" alt="screen shot 2017-11-06 at 15 42 03" src="https://user-images.githubusercontent.com/7124757/32446476-556ed10a-c309-11e7-8ee1-313ca10870c3.png">
[notebook_views_error.txt](https://github.com/IBMStreams/streamsx.topology/files/1446585/notebook_views_error.txt)

**Comment by chanskw** [comment]
Looking at your log, it can't connect to your streams instance:
streamsqse.localdomain

Do you have the following env vars set before running the jupyter notebook?
STREAMS_SPLPATH=/opt/ibm/InfoSphere_Streams/4.2.1.1/toolkits
STREAMS_QSEVM=/opt/ibm/InfoSphere_Streams/4.2.1.1
STREAMS_INSTALL=/opt/ibm/InfoSphere_Streams/4.2.1.1
STREAMS_DOMAIN_ID=StreamsDomain
STREAMS_INSTANCE_ID=StreamsInstance

**Comment by jchailloux** [comment]
cd /home/streamsadmin/workspace/com.ibm.streamsx.topology.pysamples
chmod -R 777 *

It solves the issue.

**Comment by wmarshall484** [comment]
Hi @jchailloux, I'm trying to recreate your exact problem. I'm assuming you're running this on a quickstart VM version 4.2.1.1?

What happens when you run this python script, for me it executes properly:
```python
from streamsx.topology.topology import Topology
from streamsx.topology.context import submit
from streamsx import rest
import time

class cntr(object):
    def __init__(self):
        self.cnt = 0

    def __iter__(self):
        return self

    def __next__(self):
        self.cnt += 1
        time.sleep(0.1)
        return self.cnt

if __name__ == "__main__":
    t = Topology()
    s = t.source(cntr())
    v = s.view()

    submit("DISTRIBUTED",t, username="streamsadmin", password="passw0rd")

    resource_url = "https://streamsqse.localdomain:8443/streams/rest/resources"
    sc = rest.StreamsConnection("streamsadmin", "passw0rd", resource_url)
    sc.session.verify = False
    instances = sc.get_instances()
    job = instances[0].get_jobs()[0]
    view = job.get_views()[0]

    q = view.start_data_fetch()

    for itm in iter(q.get, None):
        print(itm)
```

**Comment by jchailloux** [comment]
It works on my QSE(4.2.0.0) as well.

I was already able to access view by connecting myself with sc, instances, job, ....

But in the ViewDemo it appears that can use the view when created like this : view = stock_data.view()
I think that this is this access that doesn't handle the sc.session.verify=False
[ViewDemo.ipynb.zip](https://github.com/IBMStreams/streamsx.topology/files/1451929/ViewDemo.ipynb.zip)

**Comment by wmarshall484** [comment]
@jchailloux, try setting your StreamsConnection in the config object before you submit. It allows you to disable SSL certificate verification for your view objects:

```python
from streamsx.topology.topology import Topology
from streamsx.topology.context import submit, ConfigParams
from streamsx import rest
import time

class cntr(object):
    def __init__(self):
        self.cnt = 0

    def __iter__(self):
        return self

    def __next__(self):
        self.cnt += 1
        time.sleep(0.1)
        return self.cnt


if __name__ == "__main__":
    resource_url = "https://streamsqse.localdomain:8443/streams/rest/resources"
    sc = rest.StreamsConnection("streamsadmin", "passw0rd", resource_url)
    sc.session.verify = False

    conf = {ConfigParams.STREAMS_CONNECTION : sc}

    t = Topology()
    s = t.source(cntr())
    v = s.view()

    submit("DISTRIBUTED",t, username="streamsadmin", password="passw0rd", config=conf)

    q = v.start_data_fetch()

    for itm in iter(q.get, None):
        print(itm)
```

**Comment by wmarshall484** [comment]
@jchailloux, try setting your StreamsConnection in the config object before you submit. It allows you to disable SSL certificate verification for your view objects:

```python
from streamsx.topology.topology import Topology
from streamsx.topology.context import submit, ConfigParams
from streamsx import rest
import time

class cntr(object):
    def __init__(self):
        self.cnt = 0

    def __iter__(self):
        return self

    def __next__(self):
        self.cnt += 1
        time.sleep(0.1)
        return self.cnt


if __name__ == "__main__":
    resource_url = "https://streamsqse.localdomain:8443/streams/rest/resources"
    sc = rest.StreamsConnection("streamsadmin", "passw0rd", resource_url)
    sc.session.verify = False

    conf = {ConfigParams.STREAMS_CONNECTION : sc}

    t = Topology()
    s = t.source(cntr())
    v = s.view()

    submit("DISTRIBUTED",t, username="streamsadmin", password="passw0rd", config=conf)

    q = v.start_data_fetch()

    for itm in iter(q.get, None):
        print(itm)
```

**Comment by jchailloux** [comment]
Thanks.
It works

**Comment by jchailloux** [comment]
what about read_every ?

**Comment by wmarshall484** [comment]
I'm not sure what you mean.

**Comment by jchailloux** [comment]
<img width="594" alt="screen shot 2017-11-13 at 08 39 25" src="https://user-images.githubusercontent.com/7124757/32714441-364d16ca-c84e-11e7-919a-a630e951384c.png">
<img width="616" alt="screen shot 2017-11-13 at 08 40 02" src="https://user-images.githubusercontent.com/7124757/32714453-47b115d8-c84e-11e7-8639-8a246473a886.png">

**Comment by ddebrunner** [comment]
Where did see that `graph_every` or `multi_graph_every` exist?
