### ISSUE TITLE
Request for a new @spl.function decorator

### ISSUE THREAD

**Issue by nysenthil** [IBMStreams/streamsx.topology#1291]
Invoking Python code (functions and classes) as operators inside the SPL composites is nicely done in the streamsx.topology toolkit. Similarly, ability to invoke any SPL operator inside a streamsx.topology enabled Python script is also nicely done.

Please provide a new @spl.function decorator so that any arbitrary Python function inside a module present in the opt/python/streams directory can be called from within the SPL operators such as Functor, Custom etc. This feature will be very similar to the C++ and Java native function support that currently exists.

**Comment by ddebrunner** [comment]
Just an implementation note that the issue might be where to have the initialization step that will load the Python VM. With native C++ functions I don't think there is an initialization hook.

**Comment by markheger** [comment]
Streams compiler related
