### ISSUE TITLE
Updates to the streamsx package in DSX

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#1295]
The package is currently out of date and so attempts to use 1.7+ API fail.
Will the release process be updated to push releases to DSX or should it be the other way around?

**Comment by wmarshall484** [comment]
Hi Natasha,

You can update the version of the topology toolkit from DSX by running
```
!pip install --upgrade streamsx
```
as a cell. I doubt this change is permanent, and it doesn't work across notebooks. I think it's up to the DSX platform maintainers to upgrade the version.
