### ISSUE TITLE
Stream that feeds into parallel region and another transformation sees no tuples in the parallel region.

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#131]
My app ran correctly in Embedded mode, but not standalone, and it turned out this was due to a tuple type that didn't have `serialVersionUID`.

This took me a while to discover, however, because when my app called `print()` on the stream of tuples that wouldn't serialize, I got no error.  It was only when I removed the print that I got that error message.

ie, 
When FileSplit lacked the `serialVersionUID`: 

```
TStream<FileSplit> splits = // blah blah blah
splits.print();  // Printed
TStream<FileSplit> parallelizedSplits = splits.parallel(2);
parallelizedSplits.print();  // Nothing happened in Standalone, worked fine in Embedded.
```

with no errors.    (Code is [here](https://github.com/hildrum/streamsx.topology.samples/blob/master/ReadFromHDFS/src/app/ReadHDFSInParallel.java) but in an evolving state.) 

When I commented out the two prints, I got stack trace with `java.io.NotSerializableException` in Standalone.

**Comment by hildrum** [comment]
After some further changes, it seems this item may be mistitled.  The bug is that if I print the `splits` stream, nothing ends up on the parallelizedSplits TStream, whether or not the FileSplit implements serializable.

**Comment by ddebrunner** [comment]
Having a serialized Id  field is not required for serialization.

**Comment by hildrum** [comment]
@ddebrunner you're right, I misunderstood the problem.  There's two problems I ran into where the it ran in embedded and not in standalone.  

Minor:  For some applications, embedded mode does not require tuple types to be serializable while stand alone does.  If you debug apps with embedded, they'll seem fine until you run standalone.  This is easy to fix by making the tuple serializable. 

Bigger:  When running standalone, calling `print` on a stream prevents it from being parallelized.  The stream that is the result of the `parallel` call has no tuples on it.

**Comment by ddebrunner** [comment]
Not sure what can be done about the "minor" issue. In some applications if there is no need to serialize a tuple then there is no check for can it be serialized. We don't want to check on the declared type, as it should be valid to say a declared stream type is Runnable or Object which are not serializable, but tuple instances on the stream would be serializable.

**Comment by ddebrunner** [comment]
See the test case in ParallelTest with the @Ignore annotation.

**Comment by wmarshall484** [comment]
This no longer seems to be an issue. I've verified that the **@ignore**'d parallel test passes, and that the following code produces the correct output:
```
		Topology top = new Topology();
		TStream<Integer> s = top.source(() -> Arrays.asList(1,2,3,4));
		s.print();
		s.parallel(4).map(tup -> tup *-1).print();
		
		StreamsContextFactory.getStreamsContext(Type.STANDALONE).submit(top).get();
```
