### ISSUE TITLE
Support Streaming Analytics credentials directly.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1331]
Credentials for the service maybe be obtained a number of ways:

1. VCAP_SERVICES environment variable and format
   - Full JSON format allowing multiple services of same and/or different types
1. Copied credentials from service manage tab
    - Basic information needed as a single JSON object
1. DSX project information for associated services
     - JSON object holding `name`, `type` and  `credentials` object which holds the basic credentials as in 2.

Ideally any of these should be able be used to define the service to connect to without forcing the user to provide a VCAP services format. 

- [x] Java REST api
- [x] Java topology submission
- [x] Python REST api
- [x] Python topology submission

**Comment by ddebrunner** [comment]
So today a pair of {`VCAP_SERVICES`, `SERVICE_NAME`} is required to connect to the service.

Once we use options 2 or 3 then there is just a single piece of information needed, rather than forcing this into `VCAP_SERVICES` (because it is not a list of services), what should the name of the item be?

Ideally there would be one, and dynamically we figure out if it's 2 or three, so how about `SERVICE_DEFINITION`, e.g.

```
# In DSX
cfg['SERVICE_DEFINITION'] = project.get_associated_service('myservice')
``` 

```
cfg['SERVICE_DEFINITION'] = { credentials pasted from service manage page }
```

**Comment by ddebrunner** [comment]
Note, service name is not required.

**Comment by wmarshall484** [comment]
> project.get_associated_service('myservice')
> { credentials pasted from service manage page }

If we do it this way, we're going to have to determine whether it's 1., 2., or 3. based on the contents of the json object. Right now that's easy, since all of these have distinguishing keys/structure, but in the future we could have, say, 10 different ways of authenticating. Maybe we should require a name?

Something like:
```
cfg['SERVICE_DEFINITION'] = {'credential' :  credentials pasted from service manage page }
```
or
```
cfg['SERVICE_DEFINITION'] = {'project' : project.get_associated_service('myservice') }
```

The downside would be users have to know the keys, like `project` or `credential`.

**Comment by ddebrunner** [comment]
It's only 2 or 3 we are differentiating between, 1 is the full vcap and not supported as a *service definition* as it is a collection of all services, not a single service.

**Comment by ddebrunner** [comment]
So I guess it's a question of do we complicate **every** user on the chance we will have "10 in the future" or keep it simple for the user and make us do the complicated code **once** when/if we have 10?

**Comment by wmarshall484** [comment]
> do the complicated code once
+1

`SERVICE_DEFINITION` seems good to me.

**Comment by ddebrunner** [comment]
FYI - it is a valid point you raise, i.e. we have to assume that properties like `type`, `name`, `credentials` are not added to the base credentials (option 2) though it seems really unlikely that would be the case, and we can also work to ensure that won't happen in the future (WDP consistency).
