### ISSUE TITLE
Streaming Analytics Service REST API support for credentials with mixed V1 / V2 info

### ISSUE THREAD

**Issue by johnmac-ibm** [IBMStreams/streamsx.topology#1334]
The recently added REST changes assumed credentials would be either for V1 or V2 but we recently learned there will be a case where credentials could contain both:

> When I refer to v2 API I am only referring to the APIs provided by Streaming Analytics. For the case where a VM-based instance has credentials containing a `rest_url` (v1) and a `v2_rest_url` you can choose to use either interface. 
>
> Regardless of whether you use our v1 or v2 interface... if the credentials contain a `user` and `password` you *must* use Basic auth for the Streams REST API. When the credentials do not contain `user` and `password`, you must use Bearer auth with an IAM token for the Streams REST APIs.

We have two options to resolve, one is simpler but might be less flexible going forward:

1. Switch the order we check so if we see `userid` and `password` treat as V1 service and use `Basic` auth, if we don't see that but do see `v2_rest_url` use V2 service and `Bearer` auth. This would only require changing the version checking utility code.
2. Separate authentication from service and Streams REST handling, providing either a Basic or Bearer authentication strategy when we create the service / connection. This is a bit more work but I think properly separates the REST APIs from the authentication required.

**Comment by ddebrunner** [comment]
Option 1) sounds good.
