### ISSUE TITLE
Is there a better way to do this?

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#134]
Source and multiTransform require a Iterable, but when it's natural to put the work in an Iterator, the class implementing Iterable is essentially an empty class.  

To write an HDFSFileReader, I wrote three classes -- [one implementing Function](https://github.com/hildrum/streamsx.topology.samples/blob/master/ReadFromHDFS/src/hdfshelper/HDFSFileReader.java) that returned a class  implementing Iterable, one [class implementing Iterable](https://github.com/hildrum/streamsx.topology.samples/blob/master/ReadFromHDFS/src/hdfshelper/HDFSFileIterable.java), and then [one implementing Iterator](https://github.com/hildrum/streamsx.topology.samples/blob/master/ReadFromHDFS/src/hdfshelper/HDFSFileReadIterator.java).   The class implementing Iterable does no work.    

In an earlier version, I [had a class](https://github.com/hildrum/streamsx.topology.samples/blob/master/ReadFromHDFS/src/hdfshelper/ReadHDFSFile.java) that implement Iterable and return itself when `iterator` is calls.   Is this a better way to organize something like this?

**Comment by ddebrunner** [comment]
My first thought was that your class would implement Iterator and Iterable.

But then I wondered if the first class objects you hand back to the user should not implement Iterator, just Iterable. Then you would have the common pattern of being able to iterator over an object multiple times. If you main object implements Iterator then it's a one shot object.

**Comment by ddebrunner** [comment]
Found this:

http://stackoverflow.com/questions/16088860/why-java-iterator-interface-should-be-implemented-as-inner-class

which is similar to what I said, separate out the class representing the collection of items, from a cursor (Iterator) over that collection.

**Comment by hildrum** [comment]
I understand the purpose in general, but I think `Supplier` would be easier to use if it was `Supplier<Iterator<U>>` rather than `Supplier<Iterable<U>>` and the same for `Function` in multiTransform.   I don't know enough about the Java Application API internals to know whether that would be feasible.

**Comment by ddebrunner** [comment]
I'm not so sure it would be easier, in all cases where I've brought in an external library the collections of things I wanted on the stream was represented by an Iterable, so I could just return that directly. If Iterator was required, then the developer would be required to add an extra call to iterator(). And then there are arrays, an example with multiTransform, for the word split example, using Java 8:

Current: `words  = lines.multiTransform(tuple -> tuple.split(" "))`

Iterator: `words = lines..multiTransform(tuple -> Arrays.asList(tuple.split(" ")).iterator())`

I think forcing the use of Iterator is moving away from a declarative style api, you can see source and multiTransform as analogous to the 'for each' statement, and this Iterable seems the correct interface. Having to specify the `iterator()` invocation seems superfluous, the source and multiTransform stated they were going to iterate, why must the developer explicitly invoke it as well?

**Comment by hildrum** [comment]
I agree it wouldn't be more convenient in the case of lists and arrays; Iterable makes more sense there.  

However, using Iterator would save me from having to create an extra class to wrap the Iterator in an Iterable.  The extra lines of code to do the wrapping are minimal, but  I got confused between Iterable and Iterator, and had to rename my classes when I put the Iterator code in the Iterable class.  

For multiTransform, I think lists and arrays are probably the most common case; but I'd guess that won't be true for sources.  However, I think you'd want to use the same choice for multiTransform and for source.
