### ISSUE TITLE
API Reference for Python operators doesn't mention extract script

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#1386]
The extract script must be called in order to generate SPL operators from the decorated Python code, but it is only mentioned in the SPL DOC:
https://ibmstreams.github.io/streamsx.topology/doc/releases/1.8/spldoc/html/tk$com.ibm.streamsx.topology/ns$com.ibm.streamsx.topology.python$6.html 
I couldn't find any references to it in the API doc, so it should be updated accordingly.

**Comment by ddebrunner** [comment]
Mainly because it is functionality aimed at SPL developers, so it's documented in SPLDOC.

Likely we will be creating a script for it and in that case it would be documented as a script.

**Comment by natashadsilva** [comment]
Ok, I agree the focus of the doc is Python, but even as an SPL developer trying to use Python I still initially went first to the Python doc. Just a comment about what needs to be done in one of those blue "Note" boxes would suffice.

**Comment by markheger** [comment]
Python doc contains description of `spl-python-extract`
