### ISSUE TITLE
Translate Python functions to SPL on structured streams.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1424]
For simple Python code translate to SPL, e.g a filter of `lambda x : x.a > 3` can be translated to an SPL invocation of `spl.relational::Filter` with a `filter` parameter of `x.a > 3` where x is the alias for the input stream.

If a function cannot be translated then code generation and execution will use the function as-is.

Propose adding as an experimental feature that is disabled by default initially.

**Comment by ddebrunner** [comment]
Also can be used as the basis for a validation of Python code at topology declaration time rather than finding errors at runtime.

**Comment by ddebrunner** [comment]
Initial support:
* Structured streams
* `Stream.filter`, `Stream.map`
* Python function (no classes) as callable passed to `filter/map`
* Stream tuple passed in as `dict`, `tuple` or `namedtuple`.
* For `map()` stream tuple returned as `tuple`
* Support for Python idioms such as a filter of `x.a or x.b` where `a` and `b` are numeric expanding to `x.a != 0 || x.b != 0`

**Comment by markheger** [comment]
no demand at the moment
