### ISSUE TITLE
Add parallel info to Operator in Java REST API

### ISSUE THREAD

**Issue by johnmac-ibm** [IBMStreams/streamsx.topology#1429]
The REST information for operator includes several members that are only returned if the operator is in a parallel region: `channel`, `channels` (and its nested properites), and `logicalName`. See https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.restapi.doc/doc/restapis-operator.html

I'm specifically interested in `logicalName`, and happy to do the pull request but wanted to ask a couple questions first:

1. Since `logicalName` is all I need now, and since `channels` in particular could bulk up the object, should I just stick with it or do them all, and
2. Should I mimic the REST API so the getters return `null` if the property is not present, leaving that as the only indicator of a parallel region, or make them a bit more user-friendly, eg. add a `isInParallelRegion()` and have `getLogicalName()` return the bare operator name if it is not in a parallel region?

**Comment by ddebrunner** [comment]
I think channel should default to the value returned by the SPL/Java/C++ functions when not in a parallel region (`-1` I think, but need to verify).
Logical name should always return the logical name (which as you say is the physical name when not in a parallel region).
If we support channel, then we need max channels as well, is that a separate property or part of the `channels` object?

**Comment by johnmac-ibm** [comment]
It doesn't appear to be a separate property, but it may be implied by the `channels` array (eg. size of), though I haven't yet looked closely at what it returns in practice, beyond what the doc says:

> **channels**
> An array of objects that provide the following information about the channels of the parallel regions used to route tuple data for the operator.
> - **indexWithinRegion**
>        A number that identifies the channel index within the parallel region.
> - **logicalOperatorName**
>        A string that identifies the logical name of the parallelized operator introducing the region.

**Comment by johnmac-ibm** [comment]
After playing around with it a bit, neither `logicalName` nor `channels` is not quite what I expected.

Both `name` and `logicalName` include what appear to be default names for the parallel region as a prefix to the invocation name, with the latter just lacking any index, eg. for an operator assigned `invocationName("Foo")` in a nested parallel instance we might see:

`"name": "PARALLEL[1].PARALLEL_2[3].Foo"`
`"logicalName": "PARALLEL.PARALLEL_2.Foo"`

I was a bit surprised to see the `PARALLEL.PARALLEL_2` portion, but I understand it.

The `channel` for that operator is 3, and the `channels` array has an element for each nested region:

```
"channels" : [
    { "indexWithinRegion" : 3, "logicalOperatorName" : "PARALLEL_2" },
    { "indexWithinRegion" : 1, "logicalOperatorName" : "PARALLEL" } ]
```

so I don't see a way to get max channels except by iterating over all channels in all operators.

For now, I'm inclined to stick with just `logicalName` since that's all I need at the moment.

Comments?

**Comment by wmarshall484** [comment]
> channels in particular could bulk up the object, should I just stick with it or do them all

I seems like channels would bulk up the object only if it's deeply nested in a parallel region -- I can't see the channels list being more than a few items longs, so I think it's fine to include it.

Since there's no `channels` analogue in the C++ API, I think setting it to `null` would be fine if it's the operator is not in a parallel region. For `channel`, I agree setting it to -1 would be better.

> then we need max channels as well

It would be nice to have, but I don't see it anywhere in the REST API, nor a convenient way of calculating it. Since dynamic UDP is coming, I think the max channels potentially change every time we query the operator.

**Comment by johnmac-ibm** [comment]
Yeah, I don't think my space argument against `channels` holds: I'd been assuming it was all possible channels, not just one per nested region.

**Comment by johnmac-ibm** [comment]
Add PR #1444 for `logicalName` only since it's all I need for now. I can add `channel` and `channels` if desired.

In that case though I should add that several fields that exist now are not yet exposed through `public` members so if the rationale for adding the channel info is to make the REST info available through the API, we may want to also expose other members.

**Comment by markheger** [comment]
no demand for this
