### ISSUE TITLE
Support parallel partitioning by key for python objects streams.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1470]
Basically supporting `Routing.KEY_PARTITIONED` when the schema is a python object.

`s.parallel(width=3, routing=KEY_PARTITIONED, func=lambda t : (t.city, t.state))`

Exact api TBD.

Under the covers it would turn into `HASH_PARTITIONED` with a function equivalent to : `lambda t : hash((t.city, t.state))`

**Comment by wmarshall484** [comment]
> s.parallel(width=3, routing=KEY_PARTITIONED, func=lambda t : (t.city, t.state))
> Under the covers it would turn into HASH_PARTITIONED

Where is the hash function provided? Does it have defaults if Python detects the types are `ints`?

**Comment by markheger** [comment]
`Routing.KEY_PARTITIONED` is supported for structured schema only, see PR #2428 
For python objects `HASH_PARTITIONED` should be used
