### ISSUE TITLE
Reduce code archive size.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1476]
For simple apps the `com.ibm.streamsx.topology` toolkit dominates the code archive size, being about 3.8MB (before compression). Consisder reducing it by:

- [ ] Not including Apache Mina - (only used for testing locally with distributed/standalone). ~652K
- [ ] If no Java functional operators then don't include Java functional primitive operators and `lib/com.ibm.streamsx.topology.jar`  - ~800K
- [ ] If no Python functional operators then don't include Python functional primitive operators or `opt/python`. ~1124K
- [ ] Don't include Python2 files - ~288K
- [x] Don't include PYI files. ~14k
- [x] Don't include toolkit.xml (we will redindex toolkit anyway) - 68K
- [x] ~Don't include icons. 44K~ - Icons are needed during toolkit reindexing.

**Comment by ddebrunner** [comment]
Initial stats for a simple Hello World APP.
```
{'codeArchiveSize': 1951353,
'codeArchiveUploadTime_ms': 6322,
'buildState_buildingTime_ms': 31645,
'jobSubmissionTime_ms': 2909,
'totalBuildTime_ms': 34485}
```

**Comment by markheger** [comment]
risk is higher than benefit
