### ISSUE TITLE
Support Stream.filter() also creating a stream that contains the tuples dropped from the main stream.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1478]

**Comment by markheger** [comment]
can be done with SPL Filter operator
https://streamsxstandard.readthedocs.io/en/latest/generated/streamsx.standard.relational.html#streamsx.standard.relational.Filter

**Comment by ddebrunner** [comment]
@markheger Not really, the idea was to have it with Python filter expressions.
