### ISSUE TITLE
Support creating a punctuation window.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1480]
Since Java/Python app apis can invoke SPL it makes sense to allow windows based upon SPL window punctuation marks.

In addition it probably makes sense to discuss window punctuation marks since they are created by Java/Python aggregations (as well as SPL operators) and maybe eventually allow source (all) operators to submit window punctuations.

So a common pattern of a two-stage aggregation can be created, a time/count window followed by a punctuation based window.

**Comment by markheger** [comment]
covered by https://github.com/IBMStreams/streamsx.topology/issues/1982
