### ISSUE TITLE
Support "cats-cradle" parallelism.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#149]
Allow topologies that include sequences similar to this:

`s.endParallel().parallel(4)`

including the various variants of parallel(...).

One issue is that a HashAdder added by the second parallel must be actually put into the preceding region, rather than after it, otherwise it's not a cats-cradle, but instead single threaded through the HashAdder.

**Comment by ddebrunner** [comment]
Is this complete?

**Comment by wmarshall484** [comment]
Yes. However, related bug #131 is inhibiting some of its functionality.
