### ISSUE TITLE
Merge optional_type branch to master when this support is needed in Streams product

### ISSUE THREAD

**Issue by nigelgodwin** [IBMStreams/streamsx.topology#1537]
Plan to do merge for version 10 of topology toolkit.
To complete the merge will require the version number of Streams with optional type support (issue 1438).

**Comment by ddebrunner** [comment]
We might create a separate release branch for the version intended to be released with the product that first supports optional type.

**Comment by ddebrunner** [comment]
optional branch has been merged to v1_10
