### ISSUE TITLE
Document synchronization model for @spl.primitive.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1541]
From a user:

_Apparently @spl.primitive_operator with multiple input ports (unlike SPL Custom operator) doesn't block other ports when it enters the process() method, which is a great news!_

**Comment by ddebrunner** [comment]
Need to document for all operators, thoughts:

- Input ports can have multiple threads active due to 
   - multiple upstream operators connect to the same port
   - upstream operator that uses multiple threads for tuple submission.

Assumptions:
 - Synchronization is not an issue for functions, we assume functions are stateless and therefore if (say `Filter` maps to a function then no additional synchronization is added.

**Comment by ddebrunner** [comment]
## Simple proposal

 - No guarantees provided by Streams at all, multiple threads may be active in an operators Python class instance. Synchronization must be provided by the operators class (unless it can suffice with Python atomic instructions).
  - Downside - maybe no Pythonic, not easy for a inexperienced developer.

## Single threading guarantee proposal (similar to Java).

Streams guarantees that only a single thread is active in the callable for the duration of call (_call__, __next__ etc). Note the actual thread used can change for each call.

- `@spl.filter`, `@spl.map`, `@spl.for_each` 
   -  Use `AutoPortMutex` so in most cases no additional overhead.
       - overhead added when multiple threads from upstream operator(s) can call process.
   - Checkpointing or consistent region would require using AutoMutex so always an overhead.

- `@spl.source`
    Already single threaded - no additional syncrhonization.

- `@spl.primitive`
   - What to do?
    - Use with checkpointing or consistent region might force a single lock, which then removes the quality the original user (see summary) desired.

**Comment by wmarshall484** [comment]
I like the idea of optionally enabling manual threading via opt-out. Regarding topology callables -- we could do something like:
```
s = s.map(MyCallable(), allow_multiple_threads = True)
```

> Per-port mutex and AutoPortMutex
I'm not sure what a per-port mutex would look like. Whereas with `@map` we can just add an auto port mutex for the entire `process` method, how do we selectively guard ports?

**Comment by ddebrunner** [comment]
> how do we selectively guard ports?
A mutex object per port.

**Comment by markheger** [comment]
no demand from user
