### ISSUE TITLE
Investigate optimizing conversion of SPL tuple to/from dictionary.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1543]
- [ ] Look at returning the `dict` to the C++ operators and convert it to a tuple using Python C-API.
    - [x] - `@spl.map` `@spl.source` - #1562 
    - [x] - `@spl.primitive` - #1583
    - [ ] - Functional `map`, `flat_map`, `source`
    - [ ] - Functional `aggregate`
- [ ] Look at creating a default `dict` and use that as the base when converting SPL tuple to Python `dict`. May avoid resizing of the dict as it will already have the correct number of keys.

**Comment by ddebrunner** [comment]
#1562 added handling returned `dict` in the cgt code and improved performance for both `tuple` and `dict` as there is no longer one additional Python call layer. 

The change for #1562 still needs to be appled to `@spl.primitive` and functional operators.

**Comment by markheger** [comment]
`flat_map` is still an open issue and covered in issue: https://github.com/IBMStreams/streamsx.topology/issues/2486
