### ISSUE TITLE
Update Apache HttpClient jars to version 4.5.2

### ISSUE THREAD

**Issue by johnmac-ibm** [IBMStreams/streamsx.topology#1545]
The IBM Streams Runner for Apache Beam will be updating to a version that includes S3 filesystem support that will work with IBM Cloud Object Storage, but this Beam SDK has a dependency on the AWS client libraries which depend on Apache HttpClient 4.5.2

Topology currently uses 4.3.6 and there appear to be some compatibility conflicts, so I'd like to update the jars in `com.ibm.streamsx.topology/opt/client/`

**Comment by ddebrunner** [comment]
Not acceptable for the users to have to specify it.

What's the downside with setting it to `true`?

**Comment by johnmac-ibm** [comment]
A couple extra versions of TLS support will be added if the user (or a lib or whatever) requested `TLS`, in particular `TLSv1.1` and `TLSv1.2`.

It seems a bit of a stretch but if the user was previously relying on `TLS` to *only* provide `TLSv1.0` and want the newer versions to fail for some other connection they have, that would not happen and the connections would now succeed.

I'm also not sure if the IBM JSSE2 provider that is looking at this property caches it, in which case it might be too late for us to set it in the REST API, but we could perhaps force the option at JVM startup (probably a safer solution) if there is a way for topology to do that without interfering with user JVM options.

**Comment by ddebrunner** [comment]
SSL connections negotiate the algorithm, so if there's a server that only accepts TLSv1.0 that it should continue to work.

**Comment by ddebrunner** [comment]
Here's a sample on how to use a TLS level.

https://stackoverflow.com/questions/28391798/how-to-set-tls-version-on-apache-httpclient

**Comment by johnmac-ibm** [comment]
So to be clear you suggesting we change the REST API to use explicit TLS versions instead of the current behaviour (which uses the default factory) to basically mimic the effect of the property?

**Comment by ddebrunner** [comment]
Maybe first understand what is different between the old code and the new?

**Comment by johnmac-ibm** [comment]
They must have made a change to the default client connection options between 4.3.6 and 4.5.2, but I'm not sure what. The only mentions I can find in the 4.4.x or 4.5.x release notes are related to hostname verification, so I'd have to dig into the source to find the details.

As a test I changed the way the REST API is creating connections to use hard-coded list of {"TLS", "TLSv1.2", "TLSv1.1", "TLSv1"} (which sort of mimics the property on IBM JVMs) and that works, but if it's just {"TLS"} it fails, so I think the former can serve as a workaround with the drawback that if the IBM JVM behavior stays as-is, and a newer version of TLS comes out, we'll have to update the list.

**Comment by pgerv12** [comment]
Perhaps we need to use https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClients.html#createSystem() instead of `createDefault()`?

**Comment by johnmac-ibm** [comment]
I suspect that would not work because the IBM JVM system default (where the default provider offers TLSv1.0) prevents connection to current IBM cloud (which requires TLSv1.2), but I will try it out when the current tests finish.

I'll also have to look into how to do that with the overrides we offer for host / cert validation.

**Comment by johnmac-ibm** [comment]
Excellent suggestion @pgerv12 my skepticism was unfounded!

I think this is the best solution in the normal case. For the case where we allow insecure hosts, I think it's okay to list the protocols.

I will move all the client creation into the existing `StreamsRestUtils` class so if we do change later we only have to change in one place.
