### ISSUE TITLE
Allow publish/subscribe of JSON streams to be accessed as `String`.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1552]
Would allow an application to select the JSON library it is using, rather than being forced to use JSONObject.

See also #839

**Comment by nigelgodwin** [comment]
Proposed API:

- public final class PublishConfig:

  - public static PublishConfig toTopic(String topic)
  - public static PublishConfig toTopic(Supplier topic)

  - public String getTopic()

  - public PublishConfig allowFilter()
    - only allowed for some stream types
    - default: no filter allowed
  - public boolean hasAllowFilter()

  - public PublishConfig stringAsJSON()
    - specifies to publish a String stream as a JSON stream
  - public boolean hasStringAsJSON()

  - equals()
  - hashCode()

- public interface TStream<T>:

  - void publish(PublishConfig config)
    - java.lang.IllegalStateException
      - stringAsJSON() specified for PublishConfig with type of stream not
        String

- public final class SubscribeConfig:

  - public static SubscribeConfig fromTopic(String topic)
  - public static SubscribeConfig fromTopic(Supplier topic)

  - public String getTopic()

  - public SubscribeConfig JSONAsString()
    - specifies to receive a JSON stream as a String stream
  - public boolean hasJSONAsString()

- public class Topology:

  - public <T> TStream<T> subscribe(SubscribeConfig config,
                                    Class<T> tupleTypeClass)
    - java.lang.IllegalStateException
      - JSONAsString() specified for SubscribeConfig with type of stream not
        String

Notes:
- there is no getPublishConfig() or getSubscribeConfig() method

Thus the following will be supported:
- s.publish(PublishConfig.toTopic("a/b/c").stringAsJSON())
- s.publish(PublishConfig.toTopic(submissionParam).allowFilter())
- t.subscribe(SubscribeConfig.fromTopic(submissionParam).JSONAsString())
and in the future:
- s.publish(PublishConfig.toTopic("data/critical").dropSlowConnections())

**Comment by ddebrunner** [comment]
I think we just want 'PublishConfig.asJSON()` to support conversions of other types to JSON in the future, such as streams with an arbitrary Java class as its type.

Maybe similar for subscribe, we need the type so maybe something like `JSONAsType(Class<T> clazz)`.

**Comment by ddebrunner** [comment]
See also: http://ibmstreams.github.io/streamsx.documentation/docs/beamrunner/beamrunner-5a-io/

**Comment by ddebrunner** [comment]
I updated the proposed api with some minor changes.

I wonder if it should be `toTopic()` for subscribe as one normally subscribes to something, not from something.

**Comment by ddebrunner** [comment]
I don't like the names of the `hasXXX` methods, normal Java standard is to use `is` for boolean, but then they should be readable.

**Comment by markheger** [comment]
do demand at the moment
