### ISSUE TITLE
Standalone context does not honor TRACING_LEVEL context property

### ISSUE THREAD

**Issue by pgerv12** [IBMStreams/streamsx.topology#1570]
When I run my application with the `ContextProperties.TRACING_LEVEL` set to Debug for `DISTRIBUTED`, the tracing level is as expected, but `STANDALONE` contexts seems to be set to `ERROR` only.

**Comment by ddebrunner** [comment]
Is this with Java or Python?

**Comment by pgerv12** [comment]
I've seen this in Java. Unknown about Python.

**Comment by ddebrunner** [comment]
Thanks, I thought we set the tracing level on the standalone invocation, do you have the command line it executes from the log output?

**Comment by pgerv12** [comment]
```
Mar 23, 2018 5:20:29 PM com.ibm.streamsx.topology.internal.streams.InvokeStandalone invoke
INFO: /opt/ibm/java-x86_64-80/jre/bin/java -jar /homes/hny7/pgerver/StreamsToolkits/streams.beamrunner/beam-samples/com.ibm.streams.beam.sample.temperature.TemperatureSample.sab 
```
