### ISSUE TITLE
com.ibm.streamsx.topology.test.api.ParallelTest.testBroadcast test failed in master

### ISSUE THREAD

**Issue by nigelgodwin** [IBMStreams/streamsx.topology#1580]
Failed as:
        ParallelTest	testBroadcast	Failure	broadcast count:
        junit.framework.AssertionFailedError: broadcast count:
        at com.ibm.streamsx.topology.test.api.ParallelTest.testBroadcast(ParallelTest.java:753)

Results:
        [junit] Tests run: 15, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 0.998 sec, Thread: 1, Class: com.ibm.streamsx.topology.test.api.ParallelTest
        /homes/hny9/nigelg/gitx/streamsx.topology/test/java/build.xml:210: The following error occurred while executing this line:
        /homes/hny9/nigelg/gitx/streamsx.topology/test/java/build.xml:318: Unittests failed

Ran as:
  cd $VIEW_HOME/test/java; ant $ant_args -Dtopology.test.haltonfailure=no -f build.xml unittest

Ran with:
  master as of 24Mar2018

**Comment by ddebrunner** [comment]
Will be fixed by PR #1556 - test should not run in embedded mode.
