### ISSUE TITLE
Testing document should include Streams requirements/limitations

### ISSUE THREAD

**Issue by pgerv12** [IBMStreams/streamsx.topology#1587]
While trying to run the many topology tests in different environments I ran into a couple of issues that I think should be warned in the `TESTING.md` guide.

1. Consistent region is required (point to infocenter, etc. for information on how to set this up).
2. Not all tests work against Streaming Analytics

**Comment by markheger** [comment]
Junit description is part of Developmentmd
TESTING.md needs to be updated for CR (link to KC)
