### ISSUE TITLE
Java REST API cannot connect to local DISTRIBUTED after HttpClient 4.5.2 upgrade

### ISSUE THREAD

**Issue by pgerv12** [IBMStreams/streamsx.topology#1597]
My application is failing to connect to my local Streams instance even with allowing insecure connections. Based on the log below, it looks like the `HttpClient` being created is only using TLSv1 and not TLSv1.2.

```
WARNING: Insecure host connections enabled.

Is initial handshake: true
...
*** ClientHello, TLSv1
...
main, received EOFException: error
main, handling exception: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
main, SEND TLSv1.2 ALERT:  fatal, description = handshake_failure
main, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 02 28                               .......

main, called closeSocket()
Finalizer thread, called close()
Finalizer thread, called closeInternal(true)
```

**Comment by ddebrunner** [comment]
What version of Streams?

**Comment by pgerv12** [comment]
I've only tested against Streams 4.3 and 4.2.4.2, but I hit this issue with both. This is in a test, not QSE, environment so the default self-signed Streams certificate was not used (hence the need to use insecure connections).
