### ISSUE TITLE
Investigate fusion setup for applications.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1617]
Now that Streams 4.2 is the base level in most cases we want to let Streams decide any fusion, while still honoring any application requirements such as _isolate_ and _low_latency_. This then supports submission time fusion rather than compile time and potentially in the future fusion changes at runtime.

In addition we can rely on the JCO so if SPL is unable to express application requirements, then maybe we can use capabilities of the JCO instead.

As an example `channelIsolation` works well for Python parallel regions to avoid all channels sharing a single Python VM with any parallelism potentially lost due to the GIL. But for Java or pure SPL apps it may not be the best choice.

**Comment by markheger** [comment]
no idea what to investigate

**Comment by pgerv12** [comment]
I *think* this was put here for topology to inject some values into the JCO depending on the type of application. If it was python, then it would inject `channelIsolation` for parallel regions. Not sure what other values would be used if the application is purely SPL operators or Java topology.

**Comment by markheger** [comment]
ok, but could be done by the user
