### ISSUE TITLE
Is it possible with streamsx.spl.op.Invoke to specify multiple streams into a single port on an SPL Primitive Operator?

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#1640]
I have a situation where I have a section of a topology that will use two SPL Primitive operators that produce the same schema.  I want to invoke a third SPL primitive operator that takes in two streams in a single input port.  

In SPL I could do something like this:
stream<MySchema> NewStream = Functor(InStream1, InStream2){}

Is there a way to do this using the streamsx.spl.op?  

What I read sounds like if I pass multple streams to the stream parameter of Invoke, it will interpret each as a separate port.

Thanks,
Brian

P.S. I am using 1.9.2_beta

**Comment by ddebrunner** [comment]
`union` is correct.
