### ISSUE TITLE
v1_10 test errors: com.ibm.streamsx.topology.test.perf.TuplePassingTest

### ISSUE THREAD

**Issue by nigelgodwin** [IBMStreams/streamsx.topology#1642]
test/java: unittest (main, standalone):

testStringMillion5Standalone, testObjectMillion5Standalone:

SEVERE: CDISP0385E ERROR: The com.ibm.streamsx.iot toolkit requires version [1.0.0,2.0.0) of the com.ibm.streamsx.mqtt toolkit, but version [1.0.0,2.0.0) of the com.ibm.streamsx.mqtt toolkit is not available.

**Comment by ddebrunner** [comment]
@nigelgodwin 
That looks to be an issue with the Streams install.

**Comment by rnostream** [comment]
All actual Cloud releases contain version 1.1.1 (plus future 1.1.x fixes) of streamsx.iot toolkit. 
Using here the new streamsx.iot version will cause this error. It should be used the streamsx.iot version provided by Cloud product version (QSE).
In the release comment of streamsx.iot version 1.2.0 it is stated that the streamsx.mqtt toolkit has to be downloaded by hand and installed in the correct location if someone wants to use this version.

**Comment by ddebrunner** [comment]
Not an issue with topology toolkit.
