### ISSUE TITLE
Remove dependency on Apache Commons IO

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#166]
It's only being used to copy a directory, which can be done fairly simply using Java 7 file visitor pattern.

**Comment by ddebrunner** [comment]
http://stackoverflow.com/questions/6214703/copy-entire-directory-contents-to-another-directory

See the Java 7 solution.

**Comment by ddebrunner** [comment]
Also solution is here:

http://docs.oracle.com/javase/7/docs/api/java/nio/file/FileVisitor.html

**Comment by dlaboss** [comment]
fixed by pull#168
