### ISSUE TITLE
Nested tuple: Support tuple as attribute type.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1679]
Support nested tuples, e.g attribute `b` in this schema.

`tuple<int32 a, tuple<int32 x, int32 y> b>`

**Comment by markheger** [comment]
1. Required types: 

- str
- bool
- int
- float
- Decimal
- complex
- bytes
- List[T]
- Set[T]
- Mapping[T]
- Optional[T]

2. Nesting of the above types, as well as custom types - for example:
```
class Address(NamedTuple):
    street: str
    city: str
    state: str
class Person(NamedTuple):
    name: str
    age: float
    address: Address
    children: List[Person]
```

**Comment by markheger** [comment]
This feature is related to conversion from structured stream to Python and vice versa.

For example streams from SPL operators containing nested tuples are converted to dict in the operator passing the tuple to Python callable.

Python callables can submit structured streams (with nested tuples), defined with type hints (named tuple), to downstream operators either Python operators or SPL operators.

### Note
When a tuple on a structured stream, that contains **nested tuples**, is passed into a Python callable it is **always** converted to a ``dict`` object containing all attributes of the stream tuple.
