### ISSUE TITLE
Align exception handling with existing code.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1698]
Follow on to #1692 @EricMichaelJohnson

We should be handling exceptions consistently including passing the exception to `__exit__` if it exists and suppressing it if needed.

If improvements are needed in the existing mechanism then they should be added there.

**Comment by EricMichaelJohnson** [comment]
This issue can be closed.

**Comment by ddebrunner** [comment]
There still seems to be multiple exception handling calls, each doing something different.

**Comment by markheger** [comment]
no hint what is missing, close issue
