### ISSUE TITLE
Reuse session and hence IAM token across multiple tests.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1712]
Currently when running with Python unittests:

 - Each test uses its own streaming analytics connection and hence its own HTTP session and IAM token. Within that test the session & IAM token are reused for the polling of metrics/job state.
- Each test actually uses two HTTP connections and IAM tokens, one from Java for build & job submission and one from Python to check the test status through metrics and job state.

- [ ] In a `unittest` run with multiple tests we can reuse the client and hence HTTP session & IAM token for the complete run by sharing the client across multiple uses by the **same** thread.
    - [x] Python
    - [ ] Java
- [ ] We can pass the IAM token between Java & Python.

**Comment by markheger** [comment]
test only, no benefit, close issue
