### ISSUE TITLE
Within a parallel region, SPL source op is generated in the main composite instead of the parallel composite

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#173]
Below, the Beacon operator instance ends up in the main composite instead of the parallel region's  synthesized composite (where the transform op instance resides)

        TStream<BeaconTuple> fb = BeaconStreams.beacon(topology, count);
        TStream<BeaconTuple> pb = fb.parallel(5);
        TStream<Integer> is = pb.transform(randomHashProducer());
        SPLStream splStream = SPL.invokeSource(is, "Beacon", new HashMap<String,Object>(), SPLSchemas.STRING);

**Comment by wmarshall484** [comment]
Source operators can't currently be parallelized with parallel(). Calling
```java
SPL.invokeSource(is, "Beacon", new HashMap<String,Object>(), SPLSchemas.STRING);
```
Is the same as calling
```java 
SPL.invokeSource(topology, "Beacon", new HashMap<String,Object>(), SPLSchemas.STRING);
```
The javadoc states that data parallelism occurs on only "subsequent transformations on the returned stream", but it should have been made clear that this doesn't apply to sources.

I'll take another pass at parallel to support the following unsupported items:
* parallel sources
* multiple input/output ports
* joining separate parallelized streams

**Comment by dlaboss** [comment]
Another problem case: fanout from the stream where endParallel() is called generates bad code.
As an aside, don't know how challenging it would be for these known limitations, but it would be way better for users if a clearer "xyz is not yet supported" exception was thrown.
```
TStream<BeaconTuple> fb = BeaconStreams.beacon(topology, count);
TStream<BeaconTuple> pb = fb.parallel(5);
TStream<Integer> is = pb.transform(randomHashProducer());
is.print();
// workaround: add a no-op filter here
// is = is.filter(passAll());
is.endParallel();
```

**Comment by wmarshall484** [comment]
Per pull request #193, and exception is now throws in the cases where fanout before endParallel would generate bad code.

**Comment by ddebrunner** [comment]
As defined by the api, the source operator is not part of the parallel region.
