### ISSUE TITLE
AttributeError: module 'dill' has no attribute 'dill'

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1736]
With the latest version of dill `0.2.8.2` this error occurs creating a topology. (line 19 `streamsx.topology.runtime.py`)

See https://github.com/uqfoundation/dill/issues/217

Also switching to `0.2.8.2` and removing the code that causes the issue fails on the streaming analytic service, probably because `0.2.7.1` is being used to deserialize. See https://github.com/uqfoundation/dill/issues/270

**Comment by mmckerns** [comment]
Can you distill the issue and post a simple example + traceback that demonstrates the particular break?  (on the `dill` issue tracker)

**Comment by mmckerns** [comment]
I have posted a solution to the workaround that's apparently in your code -- see https://github.com/uqfoundation/dill/issues/217.  Let me know if there's anything else that's an issue.

**Comment by ddebrunner** [comment]
Even with the change to use `dill._dill` we hit issue https://github.com/uqfoundation/dill/issues/272 since we are picking with 0.2.8.2 and depickling with 0.2.7.1 (on the Streaming Analytics service).

Best workaround for Streaming Analytics users is to do:
`pip install dill==0.2.7.1`

**Comment by mmckerns** [comment]
Until the version of `dill` on the Streaming Analytics service gets upgraded, I'd agree.  There is an alternate solution that could be rectified with a patch to `0.2.8.2`... as mentioned on https://github.com/uqfoundation/dill/issues/272... but it's likely to be a bit tricky (basically find everywhere `dill._dill` is potentially stored as a name, and replace it upon `dump` with `dill.dill`.

**Comment by ddebrunner** [comment]
Fixed in streamsx by #1758
