### ISSUE TITLE
Simplify SPL naming for Java topologies .

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1756]
Simplify input and output port names in generated SPL.

If a single output functional operator has an invocation name then the name of the output port should be the invocation name.

For an input port only use an alias if one has been explicitly requesteds

Basically instead of generating this:
```
stream<rstring string> UnaryOperatorLambda) as F2C =
    com.ibm.streamsx.topology.functional.java::Map (StringConstants as UnaryOperatorLambda_IN0)
```

generate

```
stream<rstring string>  F2C =
    com.ibm.streamsx.topology.functional.java::Map (StringConstants)
```

**Comment by markheger** [comment]
output stream is already simplified, no as F2C anymore
