### ISSUE TITLE
Colocating a stream with a low latency section breaks the low latency guarantee

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#181]
In distributed the low latency operators end up in different PEs.

**Comment by dlaboss** [comment]
It's not so much that colocate broke the low latency **code**, as the low latency code is effectively a no-op -- nothing looks at its results. Today, lowLatency works only as a side effect of the *fuse-islands* processing.  Presumably the results were utilized prior to the refactoring to change the default from *fuse-none* to the *fuse-islands* model, but it's not any longer.

For now, disallow this configuration -- make colocate() throw with a helpful message.  Will followup with an issue to remove this restriction.

**Comment by ddebrunner** [comment]
What configuration will be disallowed?

**Comment by dlaboss** [comment]
disallowing if colocate's TStream or input arg is in a low latency region.

note there are already certain placements of colocate that get a message-less IllegalArgumentException when colocate().isPlaceable()==false (e.g., lowLatency().colocate())  That won't change as part of this, though I've created some tests for it and enhanced the message.

I'll also be fixing / disallowing isolate() in a low latency region (currently breaks low latency guarantee), and disallowing s1.isolate().op.colocate(s1).
