### ISSUE TITLE
Source iterators can delay shutdown/consistent region cycles indefinitely.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1869]
If a source iterator blocks waiting for a tuple or returns `None` then control is not returned to the operator which will delay shutdown or a consistent region cycle.

One possible solution without requiring the app developer to perform anything special (such as returning `None` instead of blocking forever) would be to use a separate Python thread to call the iterator and to pass tuples to the operator using a Python queue (with a size limit).

**Comment by markheger** [comment]
resolved in pr #1983
