### ISSUE TITLE
SPLOperatorsTest.testSubmissionParamsWithoutDefault fails in distributed

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#190]
expected:<test"Lit erals[\n]452602956> but was:<test"Lit erals[ ]452602956>

junit.framework.AssertionFailedError: expected:<test"Lit
erals[\n]452602956> but was:<test"Lit
erals[
]452602956>
at com.ibm.streamsx.topology.test.spl.SPLOperatorsTest.testOpParams(SPLOperatorsTest.java:191)
at com.ibm.streamsx.topology.test.spl.SPLOperatorsTest.testSubmissionParamsWithoutDefault(SPLOperatorsTest.java:249)

**Comment by dlaboss** [comment]
Looks like you have an old version.  Those line #s don't make sense (the file doesn't have 249 lines).
That said I just tried with current master version and it seems to fail the same way.
Hmm... standalone is fine.
investigating.

**Comment by ddebrunner** [comment]
Probably the line numbers were wrong as I was adding a test in that class.

**Comment by dlaboss** [comment]
streamtool is misbehaving with submission parameter value handling with respect to escape sequences such as "\\n" ultimately being incorrectly passed to the application as a newline instead of the two character sequence '\', 'n'.  We're able to work around it.  See pull#194.

**Comment by dlaboss** [comment]
fixed by pull#194
