### ISSUE TITLE
Fix toUpperCase use in SubmissionTimeValue

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#195]
In com.ibm.streamsx.topology.generator.spl.SubmissionTimeValue there is this line of code (a couple of times):

MetaType.valueOf(metaType.toUpperCase())

toUpperCase() is problematic as it actually depends on the locale (search for turkish i upper case).

Since MetaType is a enum, we should be just writing out its name() value as the value in json and then using it directly, without any lower or upper casing.

**Comment by dlaboss** [comment]
fixed by pull#195
