### ISSUE TITLE
punctuation handling in streamsx.spl.spl

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#1982]
I am looking for two features in streamsx.spl.spl and can't find them if they are available:
1) @spl.source(): Ability to submit window marker punctuation.  In my case, the ability to submit it when next() is called on the iterator would be best.  My next() function knows when it is between events (scans of elasticsearch for example)

2) @spl.primitive_operator (or others): Ability to preserve punctuation.  Have a need to accept punctuation and submit it.  

Thanks,
Brian

**Comment by ddebrunner** [comment]
I like the idea of a window marker after each next().

**Comment by markheger** [comment]
Ability to emit punctuations and receive punctuation is applied by the following issues:

* Python: Provide Stream.punctor() #2517
* Python: Ability to submit punctuation in streamsx.spl.spl.PrimitiveOperator #2518
* Python: Ability to handle received punctuations in for_each and streamsx.spl.spl.PrimitiveOperator #2520 

The Python source will not be changed. There is the possibility to create a composite source with source class and Stream.punctor. Source class can generate tuples that can be replaced by window markers in the punctor.

Furthermore the feature/punct contains extensions of the Python window&aggregate #2527 and enhancements in the TopologyTester #2525 and Stream.print #2516

Feature/punct is planned for v1.16
