### ISSUE TITLE
sc error when blob attr goes into @spl.map python

### ISSUE THREAD

**Issue by bmel** [IBMStreams/streamsx.topology#2012]
### Description
I'm getting this error from `sc`:
  `splpy_general.h:1074:30: error: 'pyMvs' was not declared in this scope`
This happens for `@spl.map` when the input schema is a single attr of type `blob`. (For `@spl.source`, works fine).

### Provided material
I've placed a reproducible scenario and the build log here:
https://ibm.box.com/s/5s8fn75rb2ppg6j1nx1kx6xc55m8cc2t
See the `Readme.md` there, for info about the archive.

**Comment by ddebrunner** [comment]
@bmel - which version of streamsx are you using?

**Comment by ddebrunner** [comment]
As an FYI 1.11.9 GA is available, but it doesn't seem to fix your issue.

I can reproduce with the archive, but it's strange as we have a blob in blob out test using `@spl.map` that I believe is passing.

**Comment by ddebrunner** [comment]
Is a bug due to `@spl.map` passing the tuple as a dict not being handled correctly (`**tuple_` or `**kwargs`).
