### ISSUE TITLE
script location warnings when creating bundle

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.topology#2066]
When calling streamsx.topology.context.submit("BUNDLE", topo.graph)  the following messages appear:

```
The scripts futurize and pasteurize are installed in '/tmp/tk1870948405182788203/output/etc/streamsx.topology/python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

```

**Comment by markheger** [comment]
` python3 -m streamsx.scripts.info`
streamsx==1.12.8 (package)
  location: /home/streamsadmin/anaconda3/lib/python3.5/site-packages
Python version:3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
PYTHONHOME=/home/streamsadmin/anaconda3
PYTHONPATH=unset
PYTHONWARNINGS=unset
STREAMS_INSTALL=/home/streamsadmin/InfoSphere_Streams/4.3.0.0
JAVA_HOME=/home/streamsadmin/InfoSphere_Streams/4.3.0.0/java

**Comment by ddebrunner** [comment]
@markheger Can you share an example, it must be some package you are including that is causing that warning.
