### ISSUE TITLE
Toolkit fails to build using Ant 1.9.1

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#207]
The javadoc task added the "failonwarning" attribute in Ant v1.9.4. However, out current build environment is setup to use Ant 1.9.1. As a result, this toolkit fails to build. Due to technical issues, the environment cannot be upgraded to the latest Ant version at this time.

Therefore, I am requesting that the "failonwarning" attribute be removed from the javadoc task in order to support building the toolkit on Ant v1.9.1.

**Comment by ddebrunner** [comment]
The DEVELOPMENT doc says Ant 1.9.4 is required.
