### ISSUE TITLE
Read the docs "Edit on GitHub" link is broken

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#2076]
The link to "Edit on Github" is broken - takes you to a 404 page.

**Comment by ddebrunner** [comment]
@natashadsilva Can you provide a link to a page where you see this issue?.

**Comment by ddebrunner** [comment]
Ok - seems to be on any page generated from a `.py` file, e.g.:

https://streamsxtopology.readthedocs.io/en/stable/streamsx.topology.context.html#module-streamsx.topology.context

Also seems a common problem with readthedocs.

**Comment by markheger** [comment]
works for some pages and some not. common problem with the readthedocs
