### ISSUE TITLE
New Python Wrapper Functions required for Publish and Subscribe

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.topology#2093]
For a special application we need 2 new python wrapper functions for publish and subscribe. These functions read the required parameters for the publish and subscribe operator from a special dictionary. This dictionary contains among other information:
- Topic
- Schema,
- Connection mode
- Buffer Capacity
- Buffer Full Policy

**Comment by joergboe** [comment]
If we pass the dictionary as **params, it must have exactly the key value pairs that are expected from the function. But this is not the case. The special connection dictionary contains the required parameters among others (e.g. Connetion name,  Instance name...) Thus we need a function as adapter adapter from connection dictionary to publis/subscribe function.

**Comment by markheger** [comment]
@joergboe further PR or can this issue be closed?

**Comment by joergboe** [comment]
Due to incomplete and unclear requirements, this issue can be closed.
