### ISSUE TITLE
multiple key() on a single stream doesn't work?

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#212]
In the following example, keyd has the correct num of tuples (5) and keydD gets 0.
The function isn't (shouldn't be) important here, it's a no-op: `apply(v) just returns v`
```
        TStream<Integer> keyd = s.key(functionFn(someInt, 1));
        TStream<Integer> keydD = s.key(functionFn(someIntD, 2));
        // but this is OK:
        // TStream<Integer> keydD = s.filter(new AllowAll<Integer>()).key(functionFn(someIntD, 2));
```

**Comment by ddebrunner** [comment]
Do you have a reproducible case?

**Comment by dlaboss** [comment]
inject this into a test and run it embedded.
```
    @Test
    public void ReproIssue212Test() throws Exception {
        Topology topology = new Topology("ReproIssue212Test");
        TStream<Integer> s = topology.constants(Arrays.asList(new Integer[] {1,2,3,4,5}));
        
        TStream<Integer> keyd = s.key(functionFn());
        // with the following and test fails: expected 10 received 5
        TStream<Integer> keydD = s.key(functionFn());
        // comment out the above and uncomment the following and it works.
        //TStream<Integer> keydD = s.filter(new AllowAll<Integer>()).key(functionFn());
        
        TStream<Integer> union = keyd.union(keydD);
        // tester sees 0 tuples on union when they are really there. workaround...
        union = union.filter(new AllowAll<Integer>());
        Tester tester = topology.getTester();
        Condition<Long> expectedCount = tester.tupleCount(union, 10);
        complete(tester, expectedCount, 15, TimeUnit.SECONDS);
        assertTrue(expectedCount.toString(), expectedCount.valid());
    }
    private static Function<Integer,Integer> functionFn() {
        return new Function<Integer,Integer>() {
            public Integer apply(Integer v) { return v; }};
    }
```

**Comment by ddebrunner** [comment]
I can see why it is returning 5, because keyd and keydD are the same underlying stream, so a union of a stream with itself is itself, no double copies.

Keying the stream is really creating a view of a stream with additional meta data for subsequent processing.

Need to think if this should be covered with additional doc, rather than changing the behaviour.

**Comment by dlaboss** [comment]
Duh.   Hmm... feels like it will be less surprising if union() throws if one tries to union a TStream with the same or another TStream for the same underlying stream.   Today's "convenience" of silently ignoring the dups doesn't seem to be "needed" and given the several current ways one can create TStreams with the same underlying stream it just seems like there are possibly lots of ways users might get confused with the results from union().  Presumably we wouldn't want to consider changing the behavior to actually make the original scenario above behave as the naive user expects (i.e., yielding the 10 tuples).

**Comment by ddebrunner** [comment]
Improved documentation to indicate that union of a stream with itself is a no-op.
