### ISSUE TITLE
streamtool application configs CLI for ICP4D REST API

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#2136]
Command line tool that mimics `streamtool` for application configurations using the Streams V5/ICP4D REST api. Development is in `feature/tools`.

- [x] `chappconfig`
   - [x] Basic functionality incl `--property`
   - [x] `--description` option
   - [x] Tests
   - [x] `--User` option
- [x] `getappconfig`
   - [x] Basic functionality
   - [x] Tests
   - [x] `--User` option
- [x] `lsappconfig`
   - [x] Basic functionality
   - [x] Tests
   - [x] `--fmt` option
   - [x] `--User` option
- [x] `mkappconfig`
   - [x] Basic functionality incl `--property`
   - [x] `--description` option
   - [x] `--propfile` option
   - [x] Tests
   - [x] `--User` option
- [x] `rmappconfig`
   - [x] Basic functionality incl `--noprompt`
   - [x] Tests
   - [x] `--User` option

**Comment by Karsten12** [comment]
Updated checklist:
* [ ]  `chappconfig`   
   * [x]  Basic functionality incl `--property`
   * [x]  `--description` option
   * [ ]  Tests
   * [ ]  `--User` option
 * [ ]  `getappconfig`
   
   * [x]  Basic functionality
   * [ ]  Tests
   * [ ]  `--User` option
 * [ ]  `lsappconfig`
   
   * [x]  Basic functionality
   * [ ]  Tests
   * [x]  `--fmt` option
   * [ ]  `--User` option
 * [ ]  `mkappconfig`
   
   * [x]  Basic functionality incl `--property`
   * [x]  `--description` option
   * [x]  `--propfile` option
   * [ ]  Tests
   * [ ]  `--User` option
 * [ ]  `rmappconfig`
   
   * [x]  Basic functionality incl `--noprompt`
   * [ ]  Tests
   * [ ]  `--User` option

**Comment by ddebrunner** [comment]
@Karsten12 `rmappconfig` is returning 0 when it fails to delete an non-existent app config.

**Comment by ddebrunner** [comment]
@Karsten12 Sometimes passing `--User` to `mkappconfig` causes nothing to be created with no output.
