### ISSUE TITLE
SPL compiler sc CLI for ICP4D REST API

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#2137]
Command line tool that mimics SPL compiler `sc` using the Streams V5/ICP4D REST api. Development is in `feature/tools`.

TODO: in approximate priority

- [x] Basic build of sab
- [ ] Correct handling for output directory
- [x] Determine which toolkits to include
  - [x] From current directory.
  - [x] From `--spl-path` or `STREAMS_SPLPATH` environment variable and declared app and toolkit dependencies
  - [x] Interaction with build service to determine which toolkits are already on build service. (see #2132 )
- [x] Tests
- [ ] `--cxx-flags` , `--ld-flags` - Important for C++11 apps.
- [x] Deprecated options
- [ ] Determine additional options to support that continue to make sense in container/ICP4D world.

**Comment by Karsten12** [comment]
List of options:

-C, --clean-and-suppress
-F, --use-transport=VALUE
-J, --suppress-all-but-the-application-model
-O, --set-relax-fusion-relocatability-restartability
-P, --profile-all-operators=INT
-Z, --max-pe-cpu-fraction=VALUE
-c, --clean  
-d, --default-pool-size=INT
 -g, --debug    
-j, --num-make-threads=INT
-k, --prefer-facade-tuples
-m, --makefile-generation
-p, --part-mode=VALUE     
-r, --num-distcc-remote-hosts=INT
-v, --verbose-mode   
-z, --code-beautification
--avoid-runtime-yield=VALUE
--c++std=VALUE   
--data-directory=VALUE
--default-relocatable=VALUE  
--default-restartable=VALUE
--max-filename-length=VALUE 
--no-mixed-mode-preprocessing
--no-toolkit-indexing 
--output-directory=VALUE 
--output-side-effects-behavior=VALUE
--rebuild-toolkits
--state-variable-scoping-behavior=VALUE
--transport-stat-dir=VALUE
--validate-hosts
--window-clause-ordering=VALUE

**Comment by ddebrunner** [comment]
Need for the first release:
  --c++std=VALUE
  --data-directory=VALUE
  compile-time-arguments

and the correct output handling.

**Comment by ddebrunner** [comment]
Ref for args: https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.3.0/com.ibm.streams.ref.doc/doc/sc.html

**Comment by Karsten12** [comment]
Should this be closed? I believe all items have been completed

- Correct handling for output directory

- --cxx-flags , --ld-flags - Important for C++11 apps.

Maybe except for this option ?

- Determine additional options to support that continue to make sense in container/ICP4D world.
