### ISSUE TITLE
consider additional submission parameter support

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#215]
Additional places where a submission parameter Supplier makes sense:
- TStream/TKeyedStream args to publish(topic), throttle(delay), sample(fraction), last(count/time)
- Topology args to subscribe(topic), checkpoint(period)
- Placeable args to addResourceTags

**Comment by ddebrunner** [comment]
Topic can't be a submission time parameter, I don't think resource hosts can be either.

**Comment by dlaboss** [comment]
ic...  a SPL compiler and Property based Export/Import limitation... how lame.  Without thinking hard about it... we can't use a Name based Export/Import?

**Comment by ddebrunner** [comment]
No, only a single exported stream can exist with the same name, thus multiple applications could not publish to the same topic.

**Comment by dlaboss** [comment]
sounds like an SPL/runtime enhancement request for Property based specs?  baking the topic into a bundle seems rather restrictive.

**Comment by ddebrunner** [comment]
Submission time parameters are now supported to publish/subscribe by the core operators.
