### ISSUE TITLE
lsappconfig hardcodes the time format and timezone GMT.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#2153]
Timestamps are being printed in local time but `GMT` is always being appended.

https://github.com/IBMStreams/streamsx.topology/blob/feature/tools/com.ibm.streamsx.topology/opt/python/packages/streamsx/scripts/streamtool.py#L169

The timezone should come from a local time format. 

The format is also hardcoded to US style (M/D/Y).

A Python localtime function should be used to print times, which will handle the format and timezone correctly.

**Comment by Karsten12** [comment]
Fixed in 7fe145e90a4a31acee1c4a640d050ce7e1a5766a
