### ISSUE TITLE
get_views() example

### ISSUE THREAD

**Issue by engebret** [IBMStreams/streamsx.topology#2159]
In the documentation for get_views():
https://ibmstreams.github.io/streamsx.topology/doc/pythondoc/streamsx.rest_primitives.html#streamsx.rest_primitives.View
it shows use of "*somename*",  which results in an error on ICP4D.  Proper regex form must be used, for example ".*namename*".

This should only be a documentation update.

**Comment by ddebrunner** [comment]
@engebret Could you link specifically to what you are seeing, each method has a permalink.

I'm not seeing `sometime` anywhere in `get_views`.

What error are you seeing?

**Comment by engebret** [comment]
The current page has the following example:

>>> views = job.get_views(name = "*temperatureSensor*")

I believe you need a . before the first * to be correct. I don’t have access to my system right now to get the actual error.

**Comment by ddebrunner** [comment]
I see this:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/3769612/61230669-570e8d00-a6df-11e9-81e3-b79d9a4634b7.png">

at https://ibmstreams.github.io/streamsx.topology/doc/pythondoc/streamsx.rest_primitives.html#streamsx.rest_primitives.Instance.get_views

So I think you are saying the `*` should be `.*`. It's just in your comments formatting seems to have dropped the `*` characters.
