### ISSUE TITLE
View name on source operators

### ISSUE THREAD

**Issue by engebret** [IBMStreams/streamsx.topology#2160]
Given the following code partial code snippet, there appears to be inconsistent naming of views if they are on a source operator.  Is this the expected behavior to not use the exact name given in the creation of the view?  Only difference I see is that one of the views is on a source operator.

<...>
real_event_j = topology.subscribe(topic="Records",schema=json)
real_event_view = real_event_j.view(name="real_event")
store_events = all_feed.map(StoreEvents(), name="store_events")
store_events.view(buffer_time=5.0, sample_size=5, name="store_events")
<...>

views = submission_result.job.get_views() 
print(views[5].name)
(output-->) store_events

views = submission_result.job.get_views()
print(views[7].name)
(output-->) subscribe.Topic.real_event

**Comment by ddebrunner** [comment]
This is actually a Streams issue with the way view names are created.

**Comment by engebret** [comment]
Is it due to this being a source operator ?  Given a specific name is set by the application this is not what anyone would expect to see and later attempts to match on the name to find it will fail if wildcards do not happen to be used.

**Comment by ddebrunner** [comment]
I think it's related to if an operator invocation is in a composite.
