### ISSUE TITLE
Vwap sample - EMBEDDED fails

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#22]
0.7.0 beta release:  ran the samples with tgts defined in build.xml and all went well.  
Added a run.vwap.embedded.  Unlike the other "embedded" mode samples, it fails:
run.vwap.embedded:
     [java] Exception in thread "main" java.lang.InstantiationException: com.ibm.streams.operator.Operator
     [java]     at java.lang.J9VMInternals.newInstanceImpl(Native Method)
     [java]     at java.lang.Class.newInstance(Class.java:1920)
     [java]     at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.<init>(OperatorAdapter.java:540)
     [java]     at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.newAdapter(OperatorAdapter.java:523)
     [java]     at com.ibm.streams.flow.internal.OpExec.<init>(OpExec.java:102)
     [java]     at com.ibm.streams.flow.internal.ExecutableGraphBase.<init>(ExecutableGraphBase.java:79)
     [java]     at com.ibm.streams.flow.internal.GraphTester.<init>(GraphTester.java:64)
     [java]     at com.ibm.streams.flow.internal.RuntimeFlowProvider.newJavaTestableGraph(RuntimeFlowProvider.java:40)
     [java]     at com.ibm.streams.flow.javaprimitives.JavaOperatorTester.executable(JavaOperatorTester.java:50)
     [java]     at com.ibm.streamsx.topology.internal.context.EmbeddedStreamsContext.submit(EmbeddedStreamsContext.java:28)
     [java]     at com.ibm.streamsx.topology.internal.context.StreamsContextImpl.submit(StreamsContextImpl.java:17)
     [java]     at vwap.Vwap.main(Vwap.java:40)
     [java] Java Result: 1

**Comment by ddebrunner** [comment]
This is due to the topology including SPL operators, more error checking is needed to throw an exception if the context cannot support the topology.

**Comment by dlaboss** [comment]
Committing a change / creating a pull request for review of a base/minimal fix for the issue - better failure behavior.  

e.g., Exception in thread "main" java.lang.IllegalStateException: Topology 'vwap.Vwap' does not support EMBEDDED mode: the topology contains non-Java operators.
    ....

Will follow on with a question about additional API considerations.

**Comment by dlaboss** [comment]
Should we support additional API methods for convenience?  e.g., zero or more of things like:
- Topology.supportsEmbeddedMode()
- StreamsContext.isSupported(Topology)
- StreamsContextFactory.isSupported(Topology, StreamsContext.Type)

**Comment by ddebrunner** [comment]
> StreamsContext.isSupported(Topology)

I think this is sufficient initially.
