### ISSUE TITLE
FunctionalSubmissionParamsTest.otherTest() fails on jenkins

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#225]
The jenkins streamsx.topology builder suddenly started getting a failure on unittest.standalone's FunctionalSubmissionParamsTest.otherTest().  

It first failed in build http://sdsvm0002.svl.ibm.com:8080/job/streamsx.topology/119/  resulting from the merge of #222 (which has nothing to do with things it tests). 

Oddly that test doesn't fail in the pull request builds.  And other manual runs outside of jenkins also work... though I was able to reproduce it once.

The test fails in the assert after the complete(), reporting expected 100 got 0 tuples.  Seems like FunctionalSubmissionParamsTest runs for ~150sec when it works and ~250sec when it fails.
#224 added an @Ignore of the test to get the builds working again.

**Comment by ddebrunner** [comment]
Tests are passing on Jenkins.
