### ISSUE TITLE
Improve add_file_dependency by accepting sub-folders under location(s)

### ISSUE THREAD

**Issue by schubon** [IBMStreams/streamsx.topology#2275]
A toolkit/Streams application requiring a zoo of class libraries must/may bring these in its sab file in cloud/CP4D environments. When using Streams' Python technology adding these class libraries via add_file_dependency(), all the files end up directly under 'etc' or 'opt'.

In case of file name clashes, the user will have to re-package her libraries. Instead I think it would be easier if the location parameter would allow to create directory structures, too.

**Comment by RolefH** [comment]
You can add entire directory structures recursively. For example, when you wan to add a complete class file tree under **_APPLICATION_DIR_/opt/driver/classes**, you prepare the directory structure **driver/classes/** in a temporary directory (`tempfile.gettempdir()`), place the class file tree in **driver/classes/**, and add the **driver** directory as file dependency to the topology:
```
driver_dir = os.path.join(tempfile.gettempdir(), 'driver')
topology.add_file_dependency(driver_dir, 'opt')
```
In the SAB, you will find **opt/driver/classes/...**.

The key is, that you prepare your target directory structure before you add everything to the topology.

**Comment by RolefH** [comment]
@schubon Is the explanation above sufficient (so that the issue can be closed), or is really a function like
`topology.add_file_dependency(source, 'opt/subdir')` required? Right now, only 'etc' and 'opt' is allowed for the location.

**Comment by schubon** [comment]
I probably wasn't aware that you could add directories, too, maybe because I didn't know the extra steps for the temporary structure. Feels cumbersome, but achieves what is needed, so issue can be closed I guess.
