### ISSUE TITLE
streamsx-sc should not require a namespace to be provided for compilation

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#2285]
I can compile a main composite using Atom or Studio without requiring a namespace but with streamsx-sc I get this error:

`streamsx-sc -M SubscribeToBusLocations`
Traceback (most recent call last):
  File "//anaconda/envs/py36/bin/streamsx-sc", line 10, in <module>
    sys.exit(main())
  File "//anaconda/envs/py36/lib/python3.6/site-packages/streamsx/scripts/sc.py", line 29, in main
    topo = _create_topo(cmd_args)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/streamsx/scripts/sc.py", line 318, in _create_topo
    topo,invoke = main_composite(kind=cmd_args.main_composite)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/streamsx/spl/op.py", line 476, in main_composite
    raise ValueError('Main composite requires a namespace qualified name: ' + str(kind))
ValueError: Main composite requires a namespace qualified name: SubscribeToBusLocations

**Comment by ddebrunner** [comment]
`streamsx-sc` was designed mainly for DevOps use and in that case applications should be using a namespace. Not having a namespace is only suitable for quick test apps, not production or reusable apps.

**Comment by markheger** [comment]
Remark:

**streamsx-runner** requires a namespace for the main composite:
See "Warning": https://streamsxtopology.readthedocs.io/en/v1.14.11/scripts/runner.html#spl-applications

**Comment by RolefH** [comment]
This issue will be resolved only for the command line tools **streamsx-sc** and **streamsx-runner**, but not for the topology Python API `streamsx.spl.op.main_composite(kind, toolkits, name)`.

**Comment by markheger** [comment]
released in 1.14.12
