### ISSUE TITLE
Problem using callable class as source

### ISSUE THREAD

**Issue by schubon** [IBMStreams/streamsx.topology#2289]
I'm not sure if I failed to follow the latest changes, but in a notebook that ran before, I now have problems to use a callable class as a source in a topology:

#### Streamsx package:

Name: streamsx
Version: 1.13.11
Summary: IBM Streams Python Support
Home-page: https://github.com/IBMStreams/pypi.streamsx
Author: IBM Streams @ github.com
Author-email: debrunne@us.ibm.com
License: Apache License - Version 2.0
Location: /user-home/_global_/python-3
Requires: dill, requests, future
Required-by: streamsx.toolkits, streamsx.pmml, streamsx.objectstorage, streamsx.kafka, streamsx.inet, streamsx.hdfs, streamsx.hbase, streamsx.eventstreams, streamsx.eventstore, streamsx.elasticsearch, streamsx.database, streamsx.avro, streamsx.endpoint

#### Topology:

```
from streamsx.topology.topology import Topology

mockupDataTopo = Topology(name="MockupWebhookData")
mockupDataStream = mockupDataTopo.source(WebhookDataSource())
mockupDataStream_view = mockupDataStream.view(name="Mockup data", description="Mockup data stream")
mockupDataStream.publish(topic="SegmentWebhookData", schema=CommonSchema.Json, name="MockupWebhookData")

```
#### Error trace:

```
INFO: Webhook Data Source starting up
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-90622b30e7a8> in <module>
     10 
     11 # Use WebhookDataSource as a Streams source
---> 12 mockupDataStream = mockupDataTopo.source(WebhookDataSource())
     13 
     14 # Attach a view to watch the data stream when running

/user-home/_global_/python-3/streamsx/topology/topology.py in source(self, func, name)
    592         _name = self.graph._requested_name(_name, action='source', func=func)
    593         # source is always stateful
--> 594         op = self.graph.addOperator(self.opnamespace+"::Source", func, name=_name, sl=sl, nargs=0)
    595         op._layout(kind='Source', name=_name, orig_name=name)
    596         oport = op.addOutputPort(name=_name)

/user-home/_global_/python-3/streamsx/topology/graph.py in addOperator(self, kind, function, name, params, sl, stateful, nargs)
    163             if function is not None:
    164                 params['toolkitDir'] = streamsx.topology.param.toolkit_dir()
--> 165             op = _SPLInvocation(len(self.operators), kind, function, name, params, self, sl=sl, stateful=stateful, nargs=nargs)
    166         self.operators.append(op)
    167         if not function is None:

/user-home/_global_/python-3/streamsx/topology/graph.py in __init__(self, index, kind, function, name, params, graph, sl, stateful, nargs)
    323         self.outputPorts = []
    324         self._layout_hints = {}
--> 325         self._addOperatorFunction(self.function, stateful, nargs)
    326 
    327     def addOutputPort(self, oWidth=None, name=None, inputPort=None, schema= CommonSchema.Python,partitioned_keys=None, routing = None):

/user-home/_global_/python-3/streamsx/topology/graph.py in _addOperatorFunction(self, function, stateful, nargs)
    488             else:
    489                 function = streamsx.topology.runtime._Callable0(function,
--> 490                     no_context = True if inspect.isroutine(function) else None)
    491             recurse = True
    492 

/user-home/_global_/python-3/streamsx/topology/runtime.py in __init__(self, callable_, no_context)
    471 
    472         if check_cmm and self._streamsx_ec_context:
--> 473             self._modules.update(_inline_modules(callable_.__enter__, modules, constants))
    474             self._modules.update(_inline_modules(callable_.__exit__, modules, constants))
    475 

AttributeError: 'NoneType' object has no attribute 'update'
```

**Comment by schubon** [comment]
Just played with the RollingAverage notebook, which uses a simpler callable class as source and I do not encounter the problem there. Maybe a problem in my callable class.

**Comment by schubon** [comment]
Just for informational purposes I had implemented methods __enter__ and __exit__. If I activate both of these the callable class cannot be used as source as seen above. If I comment just one, or both of these, everything is fine.

#    def __enter__(self):
#        print("INFO: Webhook Data Source starting up")

#    def __exit__(self, excptn_type, excptn_value, traceback):
#        if excptn_type or excptn_value or traceback:
#            print("WARN: Some exception")
#        else:
#            print("Process is shutting down")

**Comment by ddebrunner** [comment]
@schubon This is fixed in 1.13.12 or the latest 1.13.13

**Comment by schubon** [comment]
Behaviour observed again in v1.13.14

**Comment by schubon** [comment]
The system I am on seems to be working again, so if the change you introduced after v1.13.11 is still in, you shouldn't investigate more for the time being. Maybe, a shared system were many people use the same account and change the packages freely isn't the ideal environment ...

I'll watch a bit longer.

**Comment by ddebrunner** [comment]
That's fix is still in.

**Comment by schubon** [comment]
I tend to that the version information and the package that really was used came from different paths, so the event that let me reopen this issue probably has been caused by a misconfiguration. Will observer further and then close.

**Comment by schubon** [comment]
Works with v1.13.14 on current Blitz test machine -> close
