### ISSUE TITLE
Inline callables cannot capture inline classes or functions.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#2292]
E.g.
```
import typing
SensorReading = typing.NamedTuple('SensorReading', [('id', str), ('val',float)])

def as_sensor(tuple_):
    return SensorReading(tuple_['id'], float(tuple_['reading'])

# s is a Stream
s.map(as_sensor, schema=SensorReading)
```

**Comment by ddebrunner** [comment]
Fixed by #2290

**Comment by schubon** [comment]
Behaviour observed again in v1.13.14

**Comment by ddebrunner** [comment]
@schubon Is that with the same example or a different one?

**Comment by ddebrunner** [comment]
All the inline/lamba tests pass when run in a main context.

`python3 test2_lambdas.py`

This test case was added to verify this: https://github.com/IBMStreams/streamsx.topology/blob/master/test/python/topology/test2_lambdas.py#L183

**Comment by schubon** [comment]
Oh sorry, I reopened the wrong issue ... 
I think I'm owing you a beer now.
