### ISSUE TITLE
Python: typing.NamedTuple used with streamsx.spl.Source excpects a list of schemas

### ISSUE THREAD

**Issue by rnostream** [IBMStreams/streamsx.topology#2313]
Trying to use a `typing.NamedTuple` defined schema in Python with a source operator derived from `streamsx.spl.op.Source`.

Following error occurs ... It expects a schema list ... 
But in this case a list is an error as `streamsx.spl.op.Source` is defined to have no input port and **exact 1 output port**.
Using usual way `StreamSchema('tuple <>')` doesn't expect a list.

Took a while getting the root cause as it was  not obvious if I do a mistake when using structured schemas.

**Comment by ddebrunner** [comment]
@rnostream I think a work around is to pass a the named tuple as a list, e.g. `[nt]`

**Comment by rnostream** [comment]
Yes, that's what I actually do.
