### ISSUE TITLE
Publish/Subscribe not working between DataFlow/Notebooks/StreamsStudio (fab)

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.topology#2327]
I can't connect applications written using Python Notebooks , DataFlow and Streams studio.

Only application written using the same environment (Notebooks for example) can connect using pub/sub.

Other application (DataFlow or sab) that want to subscribe the same topic with the same data (name & type) are running but not connected.

**Comment by ddebrunner** [comment]
@jchailloux Can you provide an example, e.g. a Python topology that is meant to connect to a SPL app written with Streams studio?

**Comment by markheger** [comment]
@jchailloux Any update on this? Is this still an issue?

**Comment by markheger** [comment]
@jchailloux re-open the issue, when this is still an issue and you can provide a sample
