### ISSUE TITLE
Use of super in a main class causes runtime error.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#2336]
Having a transform (e.g. map) callable/iterable class defined in a notebook or in the main script that uses super causes Attribute error like:
```
AttributeError: Can't get attribute 'A' on <module '__main__' (built-in)>
```

Sample classes:

```
class A(X):
    def __init__(self)
         super().__init__()
```

```
class A(X):
    def __init__(self)
         super(A, self).__init__()
```

Workaround is to call the parent class method directly:

```
class A(X):
    def __init__(self)
         X.__init__(self)
```

or to define the class in its own module (not in notebook or main script)

**Comment by markheger** [comment]
workaround is documented, close issue
