### ISSUE TITLE
improve failure mode behavior when STREAMS_INSTALL, etc not setup

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#24]
Attempting to run a Java API topology with STREAMS_INSTALL is not set fails and the messages are not particularly clear.
Similarly, attempting to submit a DISTRIBUTED topology if STREAMS_DOMAIN_ID and STREAMS_INSTANCE_ID aren't set yields confusing behavior.

**Comment by ddebrunner** [comment]
Did pull request #26 fix this?

Note that if you add info like "Fixes #24" in the pull request description, then the issue is closed automatically when the pull request is closed.

**Comment by dlaboss** [comment]
Yes, Dan it did.  Thx for the pointer.
