### ISSUE TITLE
Rename messaging ConsumerConnector/ProducerConnector.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#242]
While the names are in a messaging framework specific package when used in code what messaging framework does not stand out, e.g. from the javadoc:

`ProducerConnector producer = new ProducerConnector(top, config);`

Would it be better to have names such as:

`MqttProducer producer = new MqttProducer (top, config);`

?

**Comment by ddebrunner** [comment]
For Mqtt, I also think that there just needs to be a single MqttBroker object, I think that's how MQTT is thought about, a single broker that you publish to and subscribe from.

**Comment by ddebrunner** [comment]
Actually, looking at this more, MqttCLient has the potential to be confused with the actual MqttClient class, so how about:

MqttStreams

?

**Comment by dlaboss** [comment]
* mqtt.MqttStreams replaces mqtt.{Producer,Consumer}Connector
* kafka.Kafka{Producer,Consumer} replaces kafka.{Producer,Consumer}Connector

**Comment by dlaboss** [comment]
closed by #244
