### ISSUE TITLE
Javadoc link is out of date

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#2466]
On the documentation page:
http://ibmstreams.github.io/streamsx.topology/doc.html,
It says "The javadoc for the Java Application API may be found here. 
The link to the javadocdoc page:
http://ibmstreams.github.io/streamsx.topology/doc/javadoc/index.html
has `streamsx.topology 1.10` at the bottom, so this is not the latest.

**Comment by RolefH** [comment]
**common-build.xml**:
```
<property name="streamsx.topology.version" value="1.10"/>
```
This property should be derived from info.xml of the toolkit.

**Comment by RolefH** [comment]
**Note:** The Javadoc itself is up-to-date. Only the footer shows an out-dated version as the version is fixed in the build scripts.
