### ISSUE TITLE
Publish streamsx.topology releases in Maven repository

### ISSUE THREAD

**Issue by Golfer474** [IBMStreams/streamsx.topology#2522]
Would like to request that the streamsx.topology artifacts (jar files and toolkit zip files) for each release/tag be published in a public Maven repo.  This would allow Maven/Gradle based projects to easily consume and update the version of streamsx.topology used.

**Comment by markheger** [comment]
Publish artifacts in maven repository is a good idea, for example at `com/ibm/streams/topology`: https://repo1.maven.org/maven2/com/ibm/

This would help developers working with Java topologies.

**Comment by Golfer474** [comment]
The artifacts I see needing published with each release are:
* The API jar/lib.  Example name: com.ibm.streamsx.topology-1.15.7.jar
* The sources jar for the API/lib.  Example name: com.ibm.streamsx.topology-1.15.7-sources.jar
* The tgz containing the toolkit, etc (the same artifact that is created with each release today).  Example name: com.ibm.streamsx.topology-1.15.7.tgz

**Comment by markheger** [comment]
1.15.8 has been published:
https://repo1.maven.org/maven2/com/ibm/streams/streamsx.topology/1.15.8/

**Comment by Golfer474** [comment]
Perfect, thanks.

**Comment by markheger** [comment]
pom.xml is incomplete, will be fixed with 1.15.9

**Comment by markheger** [comment]
1.15.9 released on Maven
