### ISSUE TITLE
Defect in use of suppliers for config

### ISSUE THREAD

**Issue by Golfer474** [IBMStreams/streamsx.topology#2524]
The use of submission params for window configuration was implemented here: https://github.com/IBMStreams/streamsx.topology/pull/2501/

However, it appears the use of the key() method on a declared window was overlooked, as the new WindowDefinition is being created with a null supplierConfig:
https://github.com/IBMStreams/streamsx.topology/blob/2d19403d9bbd7b8d0c32b0099f53aa451e519195/java/src/com/ibm/streamsx/topology/internal/core/WindowDefinition.java#L209

To correct this issue I believe the code needs to be changed to:
```java
return new WindowDefinition<T,U>(stream, policy, config, timeUnit, keyGetter, supplierConfig);
```
in order to maintain the supplierConfig object when copying / creating a new WindowDefinition object from the existing one.

**Comment by markheger** [comment]
fix will be part of release v1.15.8

**Comment by Golfer474** [comment]
Thanks, do you know when the v1.15.8 release is planned?

**Comment by markheger** [comment]
either this week or next week

**Comment by markheger** [comment]
v1.15.8 has been released
