### ISSUE TITLE
Unable to get started with Scala samples

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#257]
I compiled the scala samples from here as follows:

samples/com.ibm.streamsx.topology/scala

I ran ant and got the samples to build.

Problem 1 - When the Scala samples are built, the output of the classes go to the com.ibm.streamsx.topology/functional/classes directory.

I was not able to figure out where the build output.  Why do we want to build the classes into the functional directory?

Problem 2:  Next, I went to this directory to try to run the HelloWorldScala sample:

cd com.im.streamsx.topology/functional/classes
scala -classpath . simple.HelloWorldScala

I got a ClassNotFoundException:  com.ibms.treamsx.topology.Topology

I later found on the wiki that the topology and sampleOperator.jar are required.

Problem 3:  I specified the class paths and finally get a scala prompt to show up.

But it is unclear to me what the sample is supposed to do and what I am supposed to see.

Can we have some instructions as to how we are supposed to run these samples?  The information seems to be scattered between wiki pages and javadoc for the scala sample. 

Thanks!

**Comment by chanskw** [comment]
I am looking for instructions that will help me with this:

1)  How to build the samples?  What do I expect to see after the build command to see that it is successful.

2)  How do I run the samples?

3)  How do I validate the samples are running correctly and what are the samples supposed to do?

4)  How do I import the samples into Studio / Eclipse for me to do development?  

Thanks

**Comment by ddebrunner** [comment]
The requirement to have the topology jar and the operator jar is documented here:

http://ibmstreams.github.io/streamsx.topology/doc/scaladoc/index.html#package

**Comment by chanskw** [comment]
Your wiki page is missing the operator.jar.  And that's why i ran into trouble running the sample.  https://github.com/IBMStreams/streamsx.topology/wiki/Scala-Support

Information is too scattered and hard to find. :(

**Comment by chanskw** [comment]
Sorry to be clear... in both sets of documentation, it mentioned that you need topology.jar and sample.jar.  There was no mention that we need the operator.jar.

**Comment by ddebrunner** [comment]
No, it's right there at the bottom.

**Comment by chanskw** [comment]
yes, it mentioned this:

com.ibm.streamsx.topology/lib/com.ibm.streamsx.topology.jar - Scala & Java Application APIs for IBM Streams
$STREAMS_INSTALL/lib/com.ibm.streams.operator.samples.jar - IBM Streams Java Operator API and its samples

But it's missing this jar:

$STREAMS_INSTALL/lib/com.ibm.streams.operator.jar 

Unless by saying "IBM Streams Java Operator API and its samples", we are supposed to understand that we also should include the operator.jar.  

I just looked at *.jar and added them to the list, did not read the words to mean that I also need to add the com.ibm.streams.operator.jar.

**Comment by ddebrunner** [comment]
You don't need to add `com.ibm.streams.operator.jar`

but you do need `com.ibm.streams.operator.samples.jar` which is what the instructions say.

The samples jar is required and it brings in the operator api jar.

**Comment by ddebrunner** [comment]
I agree we need to move more of the information from the wiki to scaladoc.

**Comment by chanskw** [comment]
Thanks Dan for the clarification.

I think perhaps we should move it out of scalaDoc and have separate documentation for this.  scalaDoc and javadoc to me is for documenting API references.  Information about how to compile, build and run should be outside of the API references.  Having it in scalaDoc is not very discoverable.

**Comment by ddebrunner** [comment]
Maybe not move it out, but also have it elsewhere. Some (most?) developers will just start at the javadoc/scaladoc and expect to find all info there.

**Comment by chanskw** [comment]
Agree... doesn't hurt to have it in both places as this information is rather static, and does not change often.
