### ISSUE TITLE
Kafka sample too hard to understand

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#259]
I looked at the Kafka sample and tried to figure out the minimum steps required to read from Kafka or publish to Kafka.

(1)  I do not think it is a common scenario where we have a single application for reading and writing to Kafka.  I think a more common scenario is where we have one application for publishing and then a separate application for reading.  Combining it into one, makes it harder to understand the steps required to do either of these things.

(2)  We got too many functions, making it hard to understand at the very basic level, what is it that the user is required to do.

I read the sample and came up with this one for the consumer.  I am looking for something that can tell me the minimum number of steps / code that is required for me to read from Kafka or publish to Kafka.

```
    // create properties to connect to Kafka server
    Map<String,Object> props = new HashMap<>();
    props.put("zookeeper.connect", "kafka_zookeeper:port");
    props.put("group.id", "group1");
    props.put("zookeeper.session.timeout.ms", "400");
    props.put("zookeeper.sync.time.ms", "200");
    props.put("auto.commit.interval.ms", "1000");

    // set up topic for consumer to subscribe too
    Supplier<String> topic = new Value<String>("NewsTopic");

    // create Streams topology
    Topology topology = new Topology("KafkaReader");

    // create KafkaConsumer and add to Streams topology
    KafkaConsumer consumer = new KafkaConsumer(topology, props);

    // consumer to subscribe to topic
    TStream<Message> messages = consumer.subscribe(topic);

    /* Filter out non-matching messages. */
    TStream<Message> matching = messages.filter(t->t.getMessage().contains("MyInterest"));

    /* And print the matching lines to standard out.*/
    matching.print();
```

**Comment by markheger** [comment]
streamsx.kafka python wrapper should be used instead: https://pypi.python.org/pypi/streamsx.kafka
