### ISSUE TITLE
Vulnerable jquery.js version in 1.16.0 release

### ISSUE THREAD

**Issue by ZollnaPa** [IBMStreams/streamsx.topology#2592]
Here is the vulnerable jquery.js: com.ibm.streamsx.topology/doc/en_US/scaladoc/lib/jquery.js. Resolution: Upgrade to version jQuery - v1.9.0

**Comment by ghost** [comment]
The javascript jquery.js is part of the documentation and generated by _scaladoc_ into the documentation.
The only possible resolution would be to use a scala version for the documentation, which does not generate a javascript artifact that uses a vulnerable jquery.js in the scaladoc's lib directory.

**Comment by markheger** [comment]
Scala version related.
