### ISSUE TITLE
Writing to files, any samples? 

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#261]
The java topology contains classes for reading files and there some samples that demonstrate this. However, I cannot find any classes or samples that demonstrate how to write the output of a stream to a file. All of the samples appear to print the output to System.out. Am I missing something?

**Comment by dlaboss** [comment]
Nope.  You can leverage the Streams spl.adapter.FileSink operator via SPLStreams.{convertStream,stringToSPLStream}() and SPL.invokeSink().  Something along the lines of:
```
        TStream<String> s = ...
        SPLStream splStream = SPLStreams.stringToSPLStream(s);
        Map<String,Object> splParams = new HashMap<>();
        splParams.put("file", tmpFile.getAbsolutePath());
        splParams.put("append", true);
        splParams.put("flush", false);
        SPL.invokeSink("spl.adapter::FileSink", splStream, splParams);
       
```

**Comment by cancilla** [comment]
Thanks @dlaboss. That seems to have worked. However, I am wondering now how would I set the "format" parameter given that it's an enum? I tried the following with no luck:

    splParams.put("format", "txt")
    ERROR: The format operator parameter requires values of the enum{csv,txt,bin,block,line} type, but values of the rstring type are specified.**
    
    splParams.put("format", SPL.createValue("txt", MetaType.ENUM));
    ERROR: The format operator parameter requires values of the enum{csv,txt,bin,block,line} type, but values of the rstring type are specified.

Any thoughts on how to make this work?

**Comment by dlaboss** [comment]
I *think* (sorry can't be more definitive at this moment), the value needs to be an Enum... and you'll have to create your own.   e.g.,
```
enum FileAdapterFormat { csv, txt, line, block, ... };  // order isn't important
splParams.put("format", FileAdapterFormat.txt);
```
Does that work?

**Comment by cancilla** [comment]
That worked! Thanks for all of the help. Closing this issue.
