### ISSUE TITLE
specifying a space in a notebook

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#2643]
I used the `ConfigParams.SPACE_NAME` parameter from a notebook in a CPD project and I was confused when I could not find the job within the project's jobs tab, and it was not listed under **Projects>Jobs.**
 I'm not sure if this is a bug or not, but it does seems to be a CPD "design" constraint where a job is no longer  part of the project if it is added to a space. 
If it is working as designed then adding some clarification to the doc for the parameter as to its behaviour is a good idea.
It seems the space specified is created if it does not exist, this should also be mentioned.

**Comment by ghost** [comment]
Works as designed.
