### ISSUE TITLE
Question on implementing Python PassThru 

### ISSUE THREAD

**Issue by drhvm** [IBMStreams/streamsx.topology#278]
To implement the passthru operator, I see in java you just create a java PassThru class with a process method that just receives then sends the tuple back out....in our Python world....I was thinking of adding a PythonPassThru operator that basically does not call back into python in the process method ....it just sends the tuple received to the output without doing any python calls.....is that the right approach?

**Comment by wmarshall484** [comment]
Yup, adding a primitive passthrough operator which simply forwards all tuples to output is the right approach. E.g, creating 
```
com.ibm.streamsx.topology.functional.python::PassThrough
```
In the `streamsx.topology/com.ibm.streamsx.topology/com.ibm.streamsx.topology.functional.python/PassThrough` directory.

**Comment by ddebrunner** [comment]
* Why do we need such an operator?

* If it's not calling into Python why do we need an operator, just use a Filter.

**Comment by wmarshall484** [comment]
Filter deserializes the tuple, even the the lambda just returns true. A passthrough operator does no deserialization since it doesn't need to.

You might be wondering why a passThrough operator is necessary in the first place. The code generation has issues when a $Union$ op immediately precedes an $EndParallel$ op. We do the same thing in the JAA:
``` Java
    @Override
    public TStream<T> endParallel() {
        BOutput end = output();
        if(end instanceof BUnionOutput){
            end = builder().addPassThroughOperator(end);
        }
        end = builder().isolate(end);
        return addMatchingStream(builder().unparallel(end));
    }
```

**Comment by ddebrunner** [comment]
This has been addressed using an spl::relational::Filter which is what I was refering to (the Python filter is PyFunctionFilter).
