### ISSUE TITLE
Problem with Union operators not adding all upstream outputs to its inputs

### ISSUE THREAD

**Issue by drhvm** [IBMStreams/streamsx.topology#279]
I think I found the bug in the code generation and working on a fix which seems to now work.
The code in PreProcessor.java calls GraphUtilities.removeOperators which was only considering one input port (vs all input ports) when looking for a match of operators to hook-up to its children operators.

Do we need a java test update and if so, which test(s) should be updated or added?

**Comment by wmarshall484** [comment]
The way union() is implemented in the JAA doesn't use *removeOperator* to handle the connections, so the existing union tests are fine. 

However, all tests and preprocessing which do rely on *removeOperator* might have issues. This should be looked into.

**Comment by drhvm** [comment]
I did a quick check and the removeOperator seems to be called by the PreProcessor.preprocess method when calling the following:
        pePlacementPreprocess.tagIsolationRegions(graph);
        pePlacementPreprocess.tagLowLatencyRegions(graph);
        removeUnionOperators();

Since the last one seems to not be affected per your previous comment, the first two are potentials.
I am not familiar enough with the java environment to come up with tests to excercise these functions when the upstream operators would have multiple inputs.  Maybe a join followed by endlowlatency? Suggestions on testcase?

**Comment by drhvm** [comment]
Sorry...I accidentally closed this
