### ISSUE TITLE
Documenting Python application API updates

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#281]
There have been some good improvements to the Python Application API recently but I'm not sure it's being documented for users.

You can see the current documentation here.

http://ibmstreams.github.io/streamsx.topology/experimental/python/doc/spldoc/html/tk$com.ibm.streamsx.topology/ns$com.ibm.streamsx.topology.python$8.html

**Comment by sdickes** [comment]
I am making a first pass at documentation changes -- please see #283.
