### ISSUE TITLE
Problem running the java unittests

### ISSUE THREAD

**Issue by drhvm** [IBMStreams/streamsx.topology#285]
When I try to run the java unittests, I get the following error:
 Running com.ibm.streamsx.topology.test.perf.TuplePassingTest
    [junit] Exception in thread "Thread-17" java.lang.RuntimeException: java.io.InvalidClassException: com.ibm.streamsx.topology.test.perf.TuplePassingTest$4; local class incompatible: stream classdesc serialVersionUID = 1781555491621753694, local class serialVersionUID = -4312367215250204901
    [junit]     at com.ibm.streamsx.topology.internal.functional.ObjectUtils.deserializeLogic(ObjectUtils.java:49

Anyone else hit this problem?

**Comment by ddebrunner** [comment]
I just ran using Streams 4.1 with no problem.

**Comment by drhvm** [comment]
We are also using Streams 4.1.  What version of java are you running?  We are running Java 1.8

**Comment by ddebrunner** [comment]
Java 8 - as that's the supported version for Streams 4.1
