### ISSUE TITLE
[Python] Have consistent naming for functions.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#286]
Looking the at the SPLDOC describing the python Streams functions we have inconsistent naming for functions:

multi_transform
lowlatency
endlowlatency

PEP-0008 states:
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.

https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles

**Comment by sdickes** [comment]
makes sense, I will update the latency functions to use "_"  and I think @drhvm has the same problem with endparallel.

**Comment by sdickes** [comment]
lowlatency and endlowlatency have been updated in pull request #288

**Comment by ddebrunner** [comment]
was this fixed for all public api functions?

**Comment by sdickes** [comment]
In my opinion we need one update -- in the Stream class getOport() should probably be renamed to _get_oport to follow the naming convention for non-public function in a public class.
