### ISSUE TITLE
What's the difference between transform and multitransform?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#293]
I am wondering what is the difference between transform and multi transform in TStream?

When should I use transform and when should I use multitransform?

**Comment by ddebrunner** [comment]
From the javadoc for the methods:

transform: Declare a new stream that transforms each tuple from this stream into one (or zero) tuple of a different type U. 

multiTransform: Declare a new stream that transforms tuples from this stream into one or more (or zero) tuples of a different type U.

So transform is a 1-1 or 1-0 mapping, where as multTransform allows you to split an input tuple into multiple output tuples, for example splitting a sentence into its individual words.

**Comment by ddebrunner** [comment]
Did this answer your question?
