### ISSUE TITLE
[Python] [enhancement] importing application modules and packages

### ISSUE THREAD

**Issue by henrychi2** [IBMStreams/streamsx.topology#294]
**Overview**
Operations in the Python API such as filter() and transform() accept a user-supplied function as input parameter.  The function is defined in a module created by an application developer.  To allow the application to be executed from different locations, dependencies such as these application modules are copied into the Streams application bundle (.sab file).

In the current implementation, when the Python topology is submitted and compiled into a bundle, each module containing user-supplied functions is automatically copied from the local file system to a target directory in the bundle (`<toolkitRoot>/opt/python/modules`).  When the bundle is executed, the target directory is automatically added to the Python search path `sys.path`, allowing the modules to be imported and its functions to be called at runtime.

**Limitations**
There are a couple of limitations in the current implementation.

1)
Imported modules are not allowed to be defined as part of a package.  When individual modules are copied into the application bundle, the directory structure is not maintained.  For example,
```
test1.py
test_package/  <== package
    __init__.py
    test_module.py  <== user-supplied functions in a module inside a package
```
```
test1.py
from test_package import test_module
...
     topo = Topology("test_TopologyImport")
     source = topo.source(test_module.test_func) 
```
For source(), the input function's module name is actually `test_package.test_module`.  In the .sab, we see that test_module.py is copied without the package hierarchy.
```
<toolkitRoot>/opt/python/modules/
    test_module.py
```
The runtime tries to import the module named `test_package.test_module` but cannot find it.  The application fails execution with error:
`ImportError: No module named 'test_package'`

2)
If the imported module imports another module, execution might fail with `ImportError`.  This is because only the module containing the function used as input to the operation gets copied into the application bundle.  The module's dependencies are not.

**Possible Solutions**

1)
To support importing of application packages, we could have the Python API detect if the module containing user-supplied functions is part of a package.  If so, automatically copy the package directory from the local file system to a target destination in the bundle (`<toolkitRoot>/opt/python/packages`).  This target destination is also added to the Python search path, allowing modules in the package to be imported at runtime.

2)
To support importing of a module's dependencies, we could introduce a new method that lets the application add a module file or package directory to the application runtime.  For example,
```
# Adds a Python module or package to the application runtime
# If the path is for a Python module file, the file is copied to <toolkitRoot>/opt/python/modules
# If the path is for a Python package, the package is copied to <toolkitRoot>/opt/python/packages
Topology.add_dependency(self, path)
```
**Edit 2: Summary of proposed changes**

1)
Support importing of modules (containing user-supplied functions to operations) that are inside a regular package (contains `__init__.py`).  The directory of the top-level package is copied to a target destination inside the bundle, `<applicationDirectory>/opt/python/packages`.  `<applicationDirectory>/opt/python/packages` is also added to the Python search path `sys.path` during runtime.
* The top-level package is determined by the function module's `__name__`.  For example, for a module name `a.b.my_module`, the top-level package is `a`. 
* The path of package `a` is determined by the module's `__path__` attribute.  For example, for module `sys.modules['a']`, the path is determined by `sys.modules['a'].__path__`.  This will be the directory to copy to `<applicationDirectory>/opt/python/packages`.

For more information on the example, see
https://github.com/IBMStreams/streamsx.topology/wiki/Python-Support---Copying-application-packages-to-a-bundle

Notes:
* Support for importing individual modules that are not part of package already exists in the current implementation.  As before, individual modules are copied to `<applicationDirectory>/opt/python/modules`.

2)
Support for importing of modules inside a namespace package (does not contain `__init__.py`).  The top-level package is determined in the same way as regular packages, and it is copied to `<applicationDirectory>/opt/python/packages`.

It is possible for a top-level namespace package to contain multiple directories.  This can happen if different directories in the `sys.path` contain the same sub-directory name.  Although the sub-directory locations differ, Python views them as one common namespace package.  The Python API will copy each sub-directory with the same name into `<applicationDirectory>/opt/python/packages`.

For an example, see
https://github.com/IBMStreams/streamsx.topology/wiki/Python-Support---Copying-application-packages-to-a-bundle

Notes:
To avoid name collision when using the Python API, do not create modules with the same name as:
* `streamsx`, which is used by the Python API
* built-in and standard library module names (https://docs.python.org/3/library)

~~3) Limited support for importing of modules archived in a zip file.~~

4)
Support importing of modules (containing user-supplied functions to operations) that have dependencies on other application modules.
 * A particular module's dependencies are automatically determined by the Python API and copied into the bundle.  An exhaustive search is performed.  Dependencies are determined by the built-in function `vars(module)`, which shows a module's local symbol table.  To find just the application module dependencies, built-in modules, standard library modules, and modules from the Python API `streamsx` package are filtered out.

~~5) Limited support using local functions in the `__main__` module as input to operations.~~

**Comment by ddebrunner** [comment]
What exactly would be copied for a package? And i assume the copying maintains the package structure, so that if the package has multiple levels those are copied?

**Comment by ddebrunner** [comment]
Both solutions would be needed right, we just can't support one or the other?

**Comment by henrychi2** [comment]
>>> What exactly would be copied for a package? And i assume the copying maintains the package structure, so that if the package has multiple levels those are copied?

Yes.  Assuming the package is a directory on the file system, we will copy the entire contents of the directory to `<toolkitRoot>/opt/python/packages`.  This maintains the package structure.
As a side note, I read that a package can be in a form of a zip file.  So if a zip file containing the directory structure is copied to `<toolkitRoot>/opt/python/packages`, we can directly import from the zip.  I'm not sure how common this is, so we may not support this for the initial delivery.

**Comment by henrychi2** [comment]
>>> Both solutions would be needed right, we just can't support one or the other?

We can have just one solution, or a combination of both.

1) Ideally, the Python API can figure out all of the application imports and automatically copy those into the bundle.  This way, we don't need a new method `Topology.add_dependency()`.

2) If we can't find a reliable way to implicitly add all application imports, we can completely rely on the application calling `Topology.add_dependency()`.  The Python API will not implicitly add imports at all.

3) We can take a hybrid approach.  The Python API can implicitly add first-order imports  (modules containing user-supplied functions).  For "higher-order" imports (modules importing other modules importing other modules), we can rely on `Topology.add_dependency()`.  This can be somewhat confusing to the developer however, that only some imports are added.

For the initial delivery, we can try for solution 1), where the runtime automatically adds all application imports.

**Comment by ddebrunner** [comment]
> Yes. Assuming the package is a directory on the file system, we will copy the entire contents of the directory to <toolkitRoot>/opt/python/packages. This maintains the package structure.

I think you mean something different:

Assuming the package is a directory on the file system, we will copy the entire contents of the directory to <toolkitRoot>/opt/python/packages maintaining the package structure.

For example if I have a package a.b.c which is laid out as a/b/c then directory c is not copied to `<applicationDirectory>/opt/python/packages`, but instead we need to copy c to `<applicationDirectory>/opt/python/packages/a/b/c` **and** copy all of the `__init__.py` in a and b.

So I think we need a full description of what is being copied and to make the decision in this case do we just copy a/b/c and the intermediate `__init__.py` , or must be copy the whole package structure so everything under the parent directory is copied into <applicationDirectory>/opt/python/packages.

**Comment by henrychi2** [comment]
I believe which package directory to copy is determined by the import statement.  Given the following structure:
```
tmp/
  a/
    __init__.py
    b/
      __init__.py
```

1) For `import a`, we copy entire directory `a` to opt/python/packages
2) For `import a.b`, we copy entire directory `a` to opt/python/packages
3) For `import b`, we copy entire directory `b` to opt/python/packages
4) For `import a, b` we copy both `a` and `b` to opt/python/packages

**Comment by henrychi2** [comment]
For 4), it's not great that package `b` is copied to two places.  An alternative to explore:
4) For `import a, b`, we copy `a` to opt/python/packages.  Add both `opt/python/packages` and `opt/python/packages/a` to sys.path.

**Comment by henrychi2** [comment]
>>> do we just copy a/b/c and the intermediate __init__.py , or must we copy the whole package structure

For `import a.b.c`, it's simpler and possibly safer to copy the the whole directory structure from `a`.  The application might have logic that looks for resources in `a` or `b` using relative paths from `c` for example, so just having the `__init__.py` might not be enough.

**Comment by ddebrunner** [comment]
Maybe a wiki page could be created with the rules for copying, first just based upon the module name of the callable being invoked. 

I'm probably missing something but I don't understand your import cases, with 3) if the top-level tmp directory is in PYTHONPATH than how would (3) or (4) work, "b" does not exist, the module is "a.b"??? 

I'm also not understanding how we would know the import statements, are they available through reflection as i don't think we should be parsing python code.

So that's why first describing the basic case would be good, given the module of the callable that's a package what is done.

**Comment by henrychi2** [comment]
I added some basic cases in a [wiki page.](https://github.com/IBMStreams/streamsx.topology/wiki/Python-Support---Copying-application-packages-to-a-bundle)

**Comment by wmarshall484** [comment]
I'm also confused with 3) and 4), so I want to reiterate to make sure I understand.

If there exists a module within a package:
```Python
a/b/my_module.py
```
The user can reference that module from a function one of ways:
A) 
```Python
>>> import a.b.my_module
>>> a.b.my_module
>>> <module 'a.b.my_module' from 'a\b\my_module.pyc'>
```
B) 
```Python
>>> from a import b
>>> b.my_module
>>> <module 'a.b.my_module' from 'a\b\my_module.pyc'>
```
C) 
```Python
>>> from a.b import my_module
>>> my_module
>>> <module 'a.b.my_module' from 'a\b\my_module.pyc'>
```

For A), @henrychi2 is suggesting we copy the entire package structure into opy/python/packages:
```
opt/python/packages
                  | -- a
                       | -- b
                            | -- my_thing.py
```
For B), we copy only the second level structure into opy/python/packages:
```
opt/python/packages
                  | -- b
                       | -- my_thing.py
```
For C), we copy only the module into opy/python/modules:
```
opt/python/modules
                 | -- my_thing.py
```

This way, given the same import statement, the module can be discovered correctly for each case.

Is my interpretation correct? If so, given this approach, I have two questions:
* Given python introspection, how do we know which kind (A, B, or C) of import statement was used? 
* Can we recreate that import statement at runtime when `my_module` needs to be imported? The package path of `my_module` stored in its __name__ attribute will always return `a.b.my_module`, regardless of how it was imported.

**Comment by ddebrunner** [comment]
Can we first focus on the case of the actual callable first before we jump into trying to figure out which modules are loaded.

So with Will's three import styles, I can use a function or a class in my_module.py as an argument to a topology function such as `transform`. Given those six cases, what happens:
* what is copied into `applicationDirectory>/opt/python/packages`?
* how do we import the module in the C++ primitive operator?

**Comment by henrychi2** [comment]
Using cases from @wmarshall484 for structure `/tmp/a/b/my_module.py`:

A) `import a.b.my_module`
```
>>> import sys
>>> sys.path.append('/tmp')
>>> import a.b.my_module
>>> a.b.my_module
<module 'a.b.my_module' from '/tmp/a/b/my_module.py'>
>>> a.b.my_module.__name__
'a.b.my_module'
```
- Directory `a` gets copied to `<applicationDirectory>/opt/python/packages`
- The module `__name__` for my_module.py is `a.b.my_module`.  This exact name is passed to loadFunction() and eventually importModule() in the C++ primitive operator.  The module name is the same if the input is a function or a class instance.

B) `from a import b`
The following doesn't seem to work for me:
```
>>> import sys; sys.path.append('/tmp');
>>> from a import b
>>> b.my_module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'a.b' has no attribute 'my_module'
```
I'm assuming it's something like:
```
>>> import sys; sys.path.append('/tmp'); sys.path.append('/tmp/a')
>>> from a import b
>>> from b import my_module
>>> my_module
<module 'b.my_module' from '/tmp/a/b/my_module.py'>
>>> my_module.__name__
'b.my_module'
```
- In order for the C++ operator to load my_module.py, directory `b` gets copied to `<applicationDirectory>/opt/python/packages`
- The module `__name__` for my_module.py is `b.my_module`, which is used to import the module.

C) `from a.b import my_module`
```
>>> import sys
>>> sys.path.append('/tmp')
>>> from a.b import my_module
>>> my_module
<module 'a.b.my_module' from '/tmp/a/b/my_module.py'>
>>> my_module.__name__
'a.b.my_module'
```
- Directory `a` gets copied to `<applicationDirectory>/opt/python/packages`
- The module `__name__` for my_module.py is `a.b.my_module`, which is used to import the module.

As mentioned by @wmarshall484, we don't need to recreate import statements per se.  We can use introspection such as the module's `__name__` attribute to help us figure which directories to copy, and the name used to load the module from the C++ operator.

**Comment by ddebrunner** [comment]
I don't think we can break the package structure, in case B) copying b directly into the packages directopry so the path is `applicationDirectory>/opt/python/packages/b` would seem to break b if it has a  dependency on a.

**Comment by wmarshall484** [comment]
We don't need to break directory structure. 

I'm going to make an assertion and say that it doesn't actually matter how the module is imported. Let's say we pass a function to filter -- when the python graph operator is created, it adds to the list of parameters the module path in which the function was defined:
``` python
    # in SPLInvocation._addOperatorFunction
    self.params["pyModule"] = function.__module__
```
"pyModule" represents the complete path of the module in which the function was defined, e.g. `a.b.my_module`.

So we have the three things we need:
1) The location of the top level packages (since the whole package can be copied):
```
opt/python/packages
```
2) The name of the module in which the function is defined:
```
a.b.my_module
```
3) The name of the function:
```
my_function
```

Using these three pieces of information, we should be able to import anything we need to, regardless of how the function/callable class instance was imported in the first place.

**Comment by henrychi2** [comment]
Agreed that we shouldn't break directory structure.  Implementation might be trickier.

Depending how the application specifies `sys.path`, `function.__module__`, basically the function's module `__name__`, can vary.  In case A) and C), the `function.__module__` is `a.b.my_module`.  But in case B), it will be `b.my_module`.
```
>>> import sys; sys.path.append('/tmp'); sys.path.append('/tmp/a')
>>> from b import my_module
>>> my_module.my_func.__module__
'b.my_module'
```
A couple of implementation issues to think about:
- To not break up a package, we need a reliable way to find the "root" of a package to copy.
- Say we determine that the root directory of a package is `a`, and copy directory `a`.  But the `function.__module__` is `b.my_module`.  We probably need another parameter that says, add `opt/python/package/a` to `sys.path`.

**Comment by henrychi2** [comment]
@wmarshall484
>>> "pyModule" represents the complete path of the module in which the function was defined, e.g. a.b.my_module.

I think I understand.  Even if `function.__module__`, is `b.my_module`, we need to somehow determine the complete path.  So in this case, we need to determine that the root directory is `a`, and append `a.` to `b.my_module`.  So yes, this seems like a possible way to implement.

**Comment by ddebrunner** [comment]
@henrychi2 

>  But in case B), it will be b.my_module.

This seems like a situation no one in their right mind would do, namely adding the middle of a package structure to PYTHONPATH. Is there any Python documentation that indicates this is a valid approach?

It seems like in a Java world it would be equivalent to trying to import 'spl.*' instead of 'java.sql.*'.

**Comment by henrychi2** [comment]
Adding a subpackage to the PYTHONPATH is definitely frowned-upon.  It's not something that's enforced though.  For the Python API, we can assume that packages are referred from the top-level.

**Comment by ddebrunner** [comment]
The latest edit to the description says:

> 2) 
> Support for importing of modules inside a namespace package (does not contain __init__.py). The top-level package is determined in the same way as regular packages, and it is copied to `<applicationDirectory>/opt/python/packages.`

For the python code as SPL operators we copy into `modules` not `packages`.
Is this a typo, or should it be modules?

**Comment by ddebrunner** [comment]
> 3) Limited support for importing of modules archived in a zip file.

Should we be copying into something that is not `packages`, since the zip files are not part of the package structure, instead maybe something like `zips` ?

Also, can we stop any new functionality being added related to this issue for the time being, it makes it hard to review when it's a continually moving target (e.g. zip files were originally not being considered).

**Comment by ddebrunner** [comment]
I think 5) is an example of creeping scope, is in really needed at this point?

**Comment by ddebrunner** [comment]
> 4) 

Is the module containing the functions/callables the only one that is checked, or is it an exhaustive search? E.g. if a function is in a.b.c, and depends on x.y.z, is z.y.z checked for its dependencies?

**Comment by ddebrunner** [comment]
@henrychi2 

I asked for a couple of confirmations on the wiki page:

https://github.com/IBMStreams/streamsx.topology/wiki/Python-Support---Copying-application-packages-to-a-bundle

**Comment by ddebrunner** [comment]
I thought that 2 was covering modules that are not in packages, but it isn't so what is there a plan for those? Will they be copied int `applicationDir/opt/python/modules` ?

**Comment by henrychi2** [comment]
>>> Also, can we stop any new functionality being added related to this issue for the time being, it makes it hard to review when it's a continually moving target (e.g. zip files were originally not being considered).

Yes, I will remove code related to zip file support, and remove from the Summary of Proposed Changes.

>>> I think 5) is an example of creeping scope, is in really needed at this point?

I will remove code related to supporting functions in the `__main__` module as input to operations, and remove from the Summary.
I think this is a nice feature to eventually have though.  I'm writing documentation for the Python application guide, and all the samples require at least two modules because of this limitation.  It will be nice to have a complete application in one module, like the Java samples.

>>> 4) Is the module containing the functions/callables the only one that is checked, or is it an exhaustive search? E.g. if a function is in a.b.c, and depends on x.y.z, is z.y.z checked for its dependencies?

It is an exhaustive search.  I think every import in the chain starting with a.b.c has to succeed, otherwise a.b.c itself will fail to be imported.

>>> I asked for a couple of confirmations on the wiki page

The copy results look correct.  I will update wiki page with what the contents of `opt/python/packages` should look like.

>>> I thought that 2 was covering modules that are not in packages, but it isn't so what is there a plan for those? Will they be copied int applicationDir/opt/python/modules

Yes, modules not in packages are copied to `<applicationDir>/opt/python/modules`.  I think the current implementation already supports that, so it is not mentioned as an enhancement.

**Comment by henrychi2** [comment]
Support for importing third-party libraries has been added.
