### ISSUE TITLE
Moving out of incubation?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#295]
I am wondering if there is any plan for this project o move out of incubation.

Looking at the graduation page, I think we only need a clear release plan for this project to move out of incubation.

We already have samples and have active committers?

**Comment by ddebrunner** [comment]
Couple of thoughts:

* I'm not sure what a release plan looks like for an open-source project that tends to have reactive development, I'm looking forward to seeing an example, probably from streamsx.messaging.

* What actually is the value of being a graduated project?

**Comment by chanskw** [comment]
My view is that being open-source does not preclude us from having some sort of development process.  We can definitely adopt a more structured agile process, where we are continuously integrating and releasing.  A release plan makes us to be less ad-hoc, and reactive.  It also gives end-user some expectation on when a new release is coming, that may include new features that they are waiting for.

A release plan does not have to be set in stone or long term.  But I think it is important to have it documented somewhere.

Perhaps a release plan can look like this as an example (this does not reflect what you are actually doing):
1)  Topology project is planning to have a well tested, formal release every 6 months.  The target is to release by the end of June and end of December in 2016.
2)  Topology project is running on 8 weeks sprint.  A sprint release will be created at the end of each sprint.  Here are the sprint dates.

The idea here is that we do not create ad-hoc releases.  Instead, we create releases when a collection of features are available.  We provide some schedule to allow end-users to plan on when to pick up these releases.

Of course, this is just one way of managing the project.  There are many other ways, and I expect each project will be different.

As for graduating from incubation, it is a very good question. I believe it has the following values.. but we can discuss this in the IBMStreams Administration project:
1)  You lose the "incubating" tag -   : )
2)  The incubation process is helpful to help guide the community on how to mature and build the project.  It gives the community a check list on what we are looking for as being a viable and mature project.  So, part of the goals of the incubation process is to help all the projects in this organization to mature.
3)  By graduating from incubation, it gives our customers and end-users confidence that the project is viable, well tested and managed, and the project is ready for production systems.
4)  As someone who is building IBM Streams product, graduating from incubation also gives us the confidence that the project is ready to be included into the product if needed, without a lot of work.

I am curious, what is the motivation of graduating from an Apache project?  Do projects get deleted if they do not graduate within a period of time?

**Comment by ddebrunner** [comment]
Motivation for graduating at Apache is probably:
 * The project has a healthy community
 * The project can call itself an Apache project (your value 1)
*  Releases can be made by the project without oversight
* Any licence issues have been resolved.

Apache does have a different focus, "community over code".

Incubating projects at Apache can be terminated or retired.

http://incubator.apache.org/incubation/Process_Description.html

**Comment by ddebrunner** [comment]
Probably would add a graduated icon to the list I proposed here:

https://github.com/IBMStreams/streamsx.documentation/issues/39
