### ISSUE TITLE
[Python] Sample Transform example missing mymodule.print

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#300]
In the SPLDOC the Sample Transform Application includes this:

`iso2.sink(mymodule.print)`

but this function does not exist below like string_to_int does.

It works just using print

`iso2.sink(print)`

**Comment by henrychi2** [comment]
Must-fix for alpha

**Comment by henrychi2** [comment]
Changing sample to use the built-in print() function
