### ISSUE TITLE
[Python] Pip installed packages are not copied into the bundle.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#308]
I tried an example using TwitterAPI where there were two "application modules"

streamsapp.py - contained the topology calls and imported streamsmodules to use a callable

streamsmodules.py - contained the callable and imported TwitterAPI

Running the bundle has TwitterAPI module not found.

**Comment by ddebrunner** [comment]
Not clear from the SPLDOC what should happen in this case.

**Comment by henrychi2** [comment]
Must-fix for alpha

**Comment by henrychi2** [comment]
I was able to install TwitterAPI and recreate the issue.  With changes in pull request #313, I manually inspected the .sab and can see that TwitterAPI and other dependent packages are copied.

**Comment by ddebrunner** [comment]
Verified, with #313 and #319 the twitter api and dependencies were copied into the bundle, actually 297 extra files were included.

I ran a standalone bundle:
* without PYTHONPATH being set
* and the com.ibm.streamsx.topology toolkit removed (to ensure there was no hard-coded path dependency)

and it worked.
