### ISSUE TITLE
[Python] What's the overhead of streamsx::topology::PyGILLock ?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#310]
Just wondering about the overhead of any added complexity of PyGILLock  compared to having explicit calls to the methods.

I assume it means an extra object creation for every tuple processed, so anything that is per-tuple is a concern. Of course the extra cost may be dwarfed by the computation cost of whatever the Python function is doing.

Thoughts?

**Comment by henrychi2** [comment]
PyGILock is a RAII class for obtaining and releasing the GIL lock.  From what I read, creating class instances on the stack has little to no overhead.

References:

1) https://www.hackcraft.net/raii/#sect4_0

"In C++ the cost is typically nil ... As these classes have inline non-virtual constructors and destructors the code produced by an optimising compiler should be pretty much identifcal to that of the equivalent using explicit resource acquisition and release. The class will also typically use no memory, or no more than would have been necessary through other methods."

2) http://stackoverflow.com/questions/4352226/overhead-of-creating-a-new-class

"Allocating things on the stack is effectively free, no matter what they are. The compiler adds up the size of all the local variables and adjusts the stack pointer all at once to make space for them."

**Comment by ddebrunner** [comment]
Thanks!
