### ISSUE TITLE
Getting started guide describes DISTRIBUTED incorrectly.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#32]
It says:

DISTRIBUTED - Run the application in distributed mode. When an application is submitted with this context, a Streams Application Bundle (.sab file) is produced. 
[...]
 For information on how to submit an application bundle to an instance from the command line [...]

However DISTRIBUTED submits the bundle to the instance, there's no requirement for the Java developer to manually submit the instance.

I think there's a couple of places where this issue exists in the guide.

(BUNDLE is the mode that just creates the bundle (.sab) file for later submission).

**Comment by wmarshall484** [comment]
Will add separate section distinguishing DISTRIBUTED from BUNDLE, and how DISTRIBUTED automatically submits the generated bundle.
