### ISSUE TITLE
[Python] Module not found running in distributed.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#323]
Running an app with tweepy worked fine in standalone but distributed had an error loading my module (`tweets.py`) holding the functions I cal from my topology. It fails trying to find the module 'six' which is referenced from the tweepy package I import from `tweets.py`.

Looking at the files in the sab six.py was included (hence discovered by the dependency checker) but it was put into a location that is not on the module path.

`opt/python/packages/requests/packages/urllib3/packages/six.py`

**Comment by henrychi2** [comment]
Must-fix for alpha

**Comment by henrychi2** [comment]
There is another `six.py` that should have been copied but wasn't (`opt/python/packages/six.py`).  `six.py` is a package that is not a directory but a single file, which I didn't account for.  I have potential fix with pull request #325.

**Comment by ddebrunner** [comment]
tweepy sample works!
