### ISSUE TITLE
[Python] Sample application parallel_regex_grep.py does not work

### ISSUE THREAD

**Issue by sdickes** [IBMStreams/streamsx.topology#337]
The Python sample application parallel_regex_grep.py does not work because util_functions is packaged in the samples/python/topology/simple directory and is not accessible to regex.

**Comment by henrychi2** [comment]
The user is expected to have `samples/python/topology/simple` in the PYTHONPATH.  There is a note in the docstring:

        * In addition to including the `com.ibm.streamsx.topology/opt/python/packages`
          directory in the PYTHONPATH environment variable, also include the
          `samples/python/topology/simple` directory.

**Comment by sdickes** [comment]
Thanks, I had not read that but was going to try that.
