### ISSUE TITLE
Only support Java 8/Streams 4.0.1+

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#346]
Currently the toolkit supports Streams 4.0.0 which has a Java 7 virtual machine and does not support Java 8.

If this toolkit made Streams 4.0.1 the minimum product version then it could switch to using Java 8 features including lambdas (users of the toolkit can already do this if they are using Streams 4.0.1 or 4.1.x.

This would apply to the next release of master and the next Python release. 

Thoughts?

**Comment by wmarshall484** [comment]
If a user has written an application for 4.0.0 using java Function interfaces, then the application should still be compatible with a 4.0.1 release -- so we have backwards compatibility.

If that's the case, I don't see a downside to making Streams 4.0.1 the MPV

**Comment by sdickes** [comment]
I agree that this makes sense and additionally  4.0.1 IBM Streams has many fixes for users running in a distributed or bundle fashion.

**Comment by ddebrunner** [comment]
Done.
