### ISSUE TITLE
SimpleMessage throws exception when not using lamdba expressions

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#354]
Take the following code block: 

```
            TStream<SimpleMessage> resultMsgStream = resultStream.transform(new Function<MyResult, SimpleMessage>() {
				private static final long serialVersionUID = 1L;

				@Override
				public SimpleMessage apply(MyResult v) {
					return new SimpleMessage(v.toJSONString());
				}
			});
```

When compiling using the above code, the following exception is thrown: 

```
java.lang.IllegalArgumentException: Functional logic argument iotStreams2.MqttUtils$1@d92e77c3 contains a non-serializable field:this$0 ,ensure anonymous classes are declared in a static context.
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.verifySerializable(JavaFunctional.java:197)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addFunctionalOperator(JavaFunctional.java:65)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addFunctionalOperator(JavaFunctional.java:57)
	at com.ibm.streamsx.topology.internal.core.StreamImpl._transform(StreamImpl.java:148)
	at com.ibm.streamsx.topology.internal.core.StreamImpl.transform(StreamImpl.java:136)
	at iotStreams2.MqttUtils.processData(MqttUtils.java:156)
	at iotStreams2.IoTStreamsMQ.main(IoTStreamsMQ.java:12)
```

However, when using a lambda expression, the code compiles without any exceptions: 

```
            TStream<SimpleMessage> resultMsgStream = resultStream.transform(d -> {
            	return new SimpleMessage(d.toJSONString());
            });
```

**Comment by ddebrunner** [comment]
Do you have a reproducible case, as I believe we do test for this.

**Comment by ddebrunner** [comment]
It is a valid exception, the issue is that the anonymous class implicitly contains a reference to the object you are using to build the topology, which is not serializable, and probably not the behaviour you want.

**Comment by cancilla** [comment]
@ddebrunner Thanks for the feedback. I went back to look at the code and I see now that the Topology object was created as a static field. Making this a local variable resolves the issue. Unfortunately, the exception message was not particularly helpful in diagnosing this issue. 

I also found a problem in the app with the exception handling, which is why the app continued to build after getting this exception. I have removed that complaint from my original description. :)

**Comment by ddebrunner** [comment]
> I see now that the Topology object was created as a static field. Making this a local variable resolves the issue.

I'm not sure how that solves it, the issue is that the anonymous class needs to be created in a static context (as the error message states). It shouldn't matter how a reference to the topology is stored.

Do you have a simple example of the working and not working code?

**Comment by cancilla** [comment]
The following code block is the working code. To ensure I understand what you are saying, this code works because the main() method is declared static and therefore the anonymous class is created within a static context? 

```
public class Main {

	private static Topology t = new Topology("Test");
	
	public static void main(String[] args) throws Exception {
		TStream<Double> srcStream = t.limitedSource(() -> Math.random() * 10, 10);
		
		TStream<String> floorStream = srcStream.transform(new Function<Double, String>() {
			private static final long serialVersionUID = 1L;

			@Override
			public String apply(Double v) {
				return String.valueOf(v);
			}
		});		
		floorStream.print();

		
		StreamsContextFactory.getStreamsContext(Type.EMBEDDED).submit(t).get();
	}
}
```


And the reason the following code fails is because the anonymous class is being declared in the non-static run() method?


```
public class Main {

	public static void main(String[] args) throws Exception {
		Main m = new Main();
		m.run();
	}
	
	public void run() throws Exception {
		Topology t = new Topology("Test");
		
		TStream<Double> srcStream = t.limitedSource(() -> Math.random() * 10, 10);
		
		TStream<String> floorStream = srcStream.transform(new Function<Double, String>() {
			private static final long serialVersionUID = 1L;

			@Override
			public String apply(Double v) {
				return String.valueOf(v);
			}
		});		
		floorStream.print();

		
		StreamsContextFactory.getStreamsContext(Type.DISTRIBUTED).submit(t).get();
	}
}
```

**Comment by ddebrunner** [comment]
Correct, it has nothing to do with how `Topology t` was declared.

So in the working case you can move `Topology t` to be a local variable of the main method and it will continue to work.

**Comment by cancilla** [comment]
I appreciate the feedback. Closing this issue.
