### ISSUE TITLE
[Python] New release?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#360]
In the spirit of release early & often I propose a new version of the Python fairly soon with these additions:

* Rebase/merge from master to pull in the publish/subscribe changes (will drop support for Streams 4.0.0 but that will be the case for the release version, so have to do it at some point)
* Include #359 JSON subscribe support, maybe publish as well
* Include #348 Flushing of output for notebook support
* New samples just added

The release would be 1.2.6 and I would also be releasing 1.1.6 to have the two be in sync wrt the non-Python functionality.

Anything else that could be added soon, e.g. within the next week?

**Comment by wmarshall484** [comment]
I think a new release is a good idea. I'd like to add a few Jupyter samples.
