### ISSUE TITLE
[Python] NameError: name 'HASH_PARTITIONED' is not defined using parallel

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#362]
Following the instructions for `parallel` in the SPLDOC I did this:

```
 ts = ts.parallel(3, routing=HASH_PARTITIONED, func=funcs.nameh)
```

and got:

```
NameError: name 'HASH_PARTITIONED' is not defined
```

It's a documentation error as there's no indication where HASH_PARTITIONED is defined.

**Comment by drhvm** [comment]
This is defined in the Routing class in topology.py.  Use the class name qualifier when specifying ie:
Routing.HASH_PARTITIONED

**Comment by ddebrunner** [comment]
> It's a documentation error as there's no indication where HASH_PARTITIONED is defined.

**Comment by ddebrunner** [comment]
SPLDOC for Python method no longer exists.
