### ISSUE TITLE
[Python] [limitation] Distributed application fails when native library dependencies are missing

### ISSUE THREAD

**Issue by henrychi2** [IBMStreams/streamsx.topology#363]
The Python Topology API has a dependency checker that attempts to find 3rd-party libraries used by application and copy them in the application bundle.  This mainly works for pure-Python packages.  It does not work well for extension packages (packages with native components), since native libraries can link to other libraries outside of the package directory, and can link to specific versions of other libraries.

An example of an extension package is `numpy`.  Suppose an application that uses `numpy` is built on one machine.  Only the `numpy` package is copied in the application bundle, and not other native library dependencies such as LAPACK and BLAS, which are located outside of the package.  If the application bundle is copied to another machine without LAPACK and BLAS installed, it will fail to run due to the missing dependencies.

In general, this means that extension packages need to be pre-installed on every Streams resource.

For the Bluemix service, along with provisioning CPython 3.5, a suggestion is to pre-install popular Python packages, such as `numpy`, `scipy`, `matplotlib`, etc.

Related issue: #355

**Comment by wmarshall484** [comment]
I agree with your assessment -- I think that any library dependencies need to be preinstalled on the target system. This is doubly true because the architecture of the target system is unknown at the time the topology and bundle are built.

I'm marking this as doc, since I think the solution to resolving this issue is to make the user aware of the limitation.

**Comment by ddebrunner** [comment]
I disagree, a bundle is not a platform indepdent entity, it is specific to the platform architecture it is built on.

In order to support Bluemix, we cannot require that arbitrary shared libraries required by Python  modules  are pre-installed.

**Comment by markheger** [comment]
add_pip_package resolves this issue
