### ISSUE TITLE
[Python] Support for joining tuples from multiple streams

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#367]
I am looking for a way to synchronize data from 2 or more streams and act on the tuples from those streams at the same time. Basically, I am looking for a barrier() or join() operation. 

My use case is that I have data coming in from 2 signals. I am storing the data points in lists and after a certain amount of time, I need to compare both of those lists and return a result.

**Comment by dlaboss** [comment]
I'm not familiar with the py API and/or what it has access to, but I'll note that if you were using the Java API you should be able to use one of the ]SPL.invokeOperator()](https://github.com/IBMStreams/streamsx.topology/blob/master/java/src/com/ibm/streamsx/topology/spl/SPL.java#L159) to use the standard toolkit's Barrier operator.

**Comment by sdickes** [comment]
The Python support does not have a barrier function but there is a union() function. The barrier functionality would need to be written by the application developer in a Python function .

An example usage of union() is listed in the Python API Guide in GitHub:

`from streamsx.topology.topology import Topology
import streamsx.topology.context
import union_source_functions

def main():
    topo = Topology("union_source")
   h = topo.source(union_source_functions.hello)
   b = topo.source(union_source_functions.beautiful)
   c = topo.source(union_source_functions.crazy)
   w = topo.source(union_source_functions.world)
    streamSet = {b, c, w}
    hwu = h.union(streamSet)
    hwu.sink(union_source_functions.print1)
    streamsx.topology.context.submit("STANDALONE", topo.graph)

if __name__ == '__main__':
    main()`

Include the following code in the union_source_functions.py file:
`def hello() :
    return ["Hello",]

def beautiful() :
    return ["beautiful",]

def crazy() :
    return ["crazy",]

def world() :
    return ["World!",]

def print1(tuple):
    print(" - ", tuple)`

**Comment by cancilla** [comment]
I originally thought union() would be a solution. Unfortunately, the problem with using union() is that there is no way to tell which stream an output tuple originally came from. If there was a way to determine which stream an output tuple was from, I would likely be able to do something in a downstream transform() to synchronize the tuples. 

One idea I came up with was to somehow tag the tuples (upstream from the union()) to indicate which stream the tuple originally came from. Then in a function downstream from the union(), I could synchronize the tuples based on the tag. However, this solution felt like a hack and I was hoping there was some built-in way to do this.

**Comment by ddebrunner** [comment]
I'm not so sure it's a hack, at least it would seem fairly normal in Python to add an attribute to an object
