### ISSUE TITLE
Main composites must not depend on application directory.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#394]
I used the toolkit submission context to create a toolkit with a python application as a main composite.

I then invoked it from effectively an SPL application and it failed to find the python modules. This is because it's looking relative to the application directory not the toolkit of the actual main composite.

This requires passing in the invoking toolkit to the Python functional operators as a toolkit parameter using the SPL expression `getThisToolkitDir()`.

**Comment by ddebrunner** [comment]
Note when the main composite is directly compiled the application directory and the toolkit directory are the same. It differs when the main composite is invoked from a different toolkit (embedded in another [main] composite).

**Comment by ddebrunner** [comment]
Fixed for Python, need to see what's the case for Java.

**Comment by markheger** [comment]
Close
a new issue should be created if required for Java case
