### ISSUE TITLE
investigate PyFunctionHashAdder_cpp.cgt processing for spltupleDict pystyle

### ISSUE THREAD

**Issue by sdickes** [IBMStreams/streamsx.topology#404]
It is unclear if the processing performed to process the style of "spltupleDict" is functioning correctly.

**Comment by ddebrunner** [comment]
Was this resolved?

**Comment by sdickes** [comment]
No, this has not been resolved yet.

A simple workaround at this point is to use a python transform/map function after the initial subscribe to ensure that the tuple is a python object not a streams spl tuple.
