### ISSUE TITLE
Python operator: Error reported when feeding stream's tuple is a type name

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#408]
The feeder stream:
```
		stream<BTNIngestType> **RawSourceObjects** = ...
```
The operator invocation:
```
               stream< ... > DatePartConvertedSourceObjects =
			**DateTimeConvert**(**RawSourceObjects**)  {}
```
CDISP0232E An error was encountered during the generation of
   the code for the DatePartConvertedSourceObjects operator.

When BTNIngestType is spelled out with the requisite attribute descriptions, there is no problem.

**Comment by wmarshall484** [comment]
Hi Mark, is that the exact output of the SPL generator? The SPL generator should suffix stream name with 'OUT0' or 'IN0' to avoid colliding with keywords. For example:
```
( stream<blob __spl_po> negative_one_1_OUT0) as negative_one_1 = com.ibm.streamsx.topology.functional.python::PyFunctionTransform  ( Counter_0_OUT0 as negative_one_1_IN0)
```

**Comment by ddebrunner** [comment]
This is a decorated Python function as an SPL operator.

**Comment by ddebrunner** [comment]
Not sure how this could be an issue, by the time code generation happens types like `BTNIngestType` have been expanded to the full tuple type.

**Comment by ddebrunner** [comment]
I added a test for this and it passes.

@mfeblowitz Is it possible to provide an isolated reproducible case?

**Comment by mfeblowitz** [comment]
This turned out to be a bogus issue. The problem was the mismatch between the provided tuple type and the declared received tuple type.

**Comment by ddebrunner** [comment]
Thanks!
