### ISSUE TITLE
Issue with streams topology 1.4 beta; python3-config

### ISSUE THREAD

**Issue by Tallwhitebro** [IBMStreams/streamsx.topology#421]
Downloaded the beta and built it myself, I ran into an issue using python 3.5.1 as recommended in the documentation. Here is the error message I receieve:
![issue](https://cloud.githubusercontent.com/assets/17501131/16117888/5c22fdde-33a2-11e6-92f9-c67ad92a7e90.JPG)

**Comment by Tallwhitebro** [comment]
Tried again with the 1.2 alpha and ran into the same error message

**Comment by ddebrunner** [comment]
How did you install Python 3.5?

**Comment by ddebrunner** [comment]
https://github.com/IBMStreams/streamsx.topology/releases/tag/v1.4.1_beta2 

Now has a built version of the toolkit.

Simplest approach is to install Python 3.5 using Anaconda.

**Comment by chanskw** [comment]
We tried installing using various modes.

We downloaded source from python.org and followed readme instructions.  We tried it on one of our servers, and also the QSE VM:

./configure
make
make install

On our VM, we also have Anaconda2-4.0.0-Linux-x86_64.sh and it still did not work.

How is Python supposed to be installed?

**Comment by ddebrunner** [comment]
Anaconda is recommended.

With Anaconda you just install it.
This may help: https://github.com/IBMStreams/streamsx.topology/issues/383 but I just installed it accepting the defaults.

With CPython 3.5 you need to follow this:

https://github.com/IBMStreams/streamsx.topology/wiki/Installing-Python-and-com.ibm.streamsx.topology-Python-alpha

In both cases for running distributed you need to set application environment variables for the instance:
https://github.com/IBMStreams/streamsx.topology/issues/383#issuecomment-225981075

**Comment by ddebrunner** [comment]
what happens when you type

`which python3`

?

**Comment by ddebrunner** [comment]
Any updates on this? Still an issue?
