### ISSUE TITLE
Beta release has no binary?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#422]
When trying out the beta release for Python, that release seems to only include the source code and no binary.  Is it possible to include binary so that users do not have to build the project themselves?

As a side note, is it also possible to separate out the requirement of needing JUnit to build the project?  Just seems like a lot of work for the user to do, before they can try out the code.

**Comment by ddebrunner** [comment]
I'm working on producing a binary, I needed some changes made first.

**Comment by ddebrunner** [comment]
Binary is now there.

https://github.com/IBMStreams/streamsx.topology/releases/tag/v1.4.1_beta2

**Comment by chanskw** [comment]
thanks!  will try this out!
