### ISSUE TITLE
Functional Python: Errors logged at Debug level

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#425]
Errors with missing modules, and possibly and other errors, do not appear in logs at Error level, even though the PE crashes.

**Comment by ddebrunner** [comment]
Do you have an example of the error message you saw at debug level, because when we load a module we log at error:

https://github.com/IBMStreams/streamsx.topology/blob/master/com.ibm.streamsx.topology/opt/python/include/splpy.h#L246

**Comment by markheger** [comment]
close since lack of demand
