### ISSUE TITLE
Python SPL Ops: modules must be installed on all hosts

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#426]
Yes. This is a feature. Albeit annoying. 
Related to issue about log levels for errors.
Job log reports (at Debug level): "Fatal error: missing module: <python spl operator name>"
PE log reports, e.g., "ImportError: No module named 'pymongo' "
The trouble here is that finding out is a somewhat random event. If the PE lands on a host with the module installed, all is well. But if it's deployed on a host that hasn't got it, the PE fails. And it's difficult to see. Somewhat like the 3-sided Monty Python LP :)

**Comment by ddebrunner** [comment]
Do you have an example, as the required modules should be created in the sab bundle.

**Comment by mfeblowitz** [comment]
This has to do with the modules required by the Python SPL operator - they’re the ones that need modules above and beyond what’s needed to process/launch the operator. The challenge is that both python3 and all modules required by the operator must be present on all nodes. And it’s sometimes random which node a PE can be installed on.

**Comment by ddebrunner** [comment]
The expectation is that the require modules are added into the toolkit containing the operators, under the opt/python/modules or opt/python/packages location. Both of these are automatically added to the python path.

Hence the toolkit becomes self-contained.

**Comment by mfeblowitz** [comment]
Ah - ok. So assuming a shared filesystem and the code being available on each, a system install is not necessary.

Is there a standard way to pip3 install in a non-system location?

**Comment by ddebrunner** [comment]
If the required modules are in the toolkit containing the operators that require them then a shared file system is **not** required. They will be distributed to the resources as needed by the Streams runtime as part of bundle handling.

**Comment by ddebrunner** [comment]
I found this for pip install into a different directory.

http://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip

**Comment by mfeblowitz** [comment]
Looks good. I'll try it. Thanks!

**Comment by mfeblowitz** [comment]
Very good. Thanks!

**Comment by mfeblowitz** [comment]
Ok - I tried this, once I encountered a machine that didn't have pymongo installed (lazy evaluation?) and found trouble when I tried to use one of the flavors of local install, to .../opt/python/modules. It appeared to be some problem with the interaction between the install code and the local python toolkit environment.

What did work is this sequence:
`>  pip3 install --target=$HOME/modules --ignore-installed pymongo
  > mv $HOME/modules/* $toolkit_dir/.../opt/python/modules
`
Basically, install outside of the toolkit env and then move into it.

BTW, here's what the error trace looks like, when using `$toolkit_dir/.../opt/python/modules` as the target:

`   gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python3.5m -c bson/_cbsonmodule.c -o build/temp.linux-x86_64-3.5/bson/_cbsonmodule.o
    bson/_cbsonmodule.c: In function ‘_elements_to_dict’:
    bson/_cbsonmodule.c:2598:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         while (position < max) {
                         ^
    gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python3.5m -c bson/time64.c -o build/temp.linux-x86_64-3.5/bson/time64.o
    gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python3.5m -c bson/buffer.c -o build/temp.linux-x86_64-3.5/bson/buffer.o
    gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python3.5m -c bson/encoding_helpers.c -o build/temp.linux-x86_64-3.5/bson/encoding_helpers.o
    gcc -pthread -shared build/temp.linux-x86_64-3.5/bson/_cbsonmodule.o build/temp.linux-x86_64-3.5/bson/time64.o build/temp.linux-x86_64-3.5/bson/buffer.o build/temp.linux-x86_64-3.5/bson/encoding_helpers.o -L/usr/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/bson/_cbson.cpython-35m-x86_64-linux-gnu.so
    building 'pymongo._cmessage' extension
    creating build/temp.linux-x86_64-3.5/pymongo
    gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python3.5m -c pymongo/_cmessagemodule.c -o build/temp.linux-x86_64-3.5/pymongo/_cmessagemodule.o
    gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python3.5m -c bson/buffer.c -o build/temp.linux-x86_64-3.5/bson/buffer.o
    gcc -pthread -shared build/temp.linux-x86_64-3.5/pymongo/_cmessagemodule.o build/temp.linux-x86_64-3.5/bson/buffer.o -L/usr/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/pymongo/_cmessage.cpython-35m-x86_64-linux-gnu.so
    running install_lib
    copying build/lib.linux-x86_64-3.5/gridfs/errors.py -> /usr/lib/python3.5/site-packages/gridfs
    error: could not delete '/usr/lib/python3.5/site-packages/gridfs/errors.py': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-dt2n584b/pymongo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e7p8hpvo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dt2n584b/pymongo`
