### ISSUE TITLE
Functional Python: sending parameters to python module

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#427]
Is there a way to pass parameters to a python module?
I've developed a pymongo operator that sends a tuple to a mongo database. I am currently sending 4 parameters to the operator via typle attributes:
- mongo db server
- mongo db port
- mongo db database
- mongodb collection
  It would be more "normal" to have these be specified as params in the SPL and then passed to the operator. Not sure how, as arguments to the operator are currently all assumed to be tuple attributes.

**Comment by wmarshall484** [comment]
Submission-time parameters are currently not supported in the Python API Beta.

**Comment by wmarshall484** [comment]
Submission-time parameters are not supported in the current Beta of the Python API. If you want to pass parameters to an operator such as a mongodb server connection, I suggest creating a callable class as an operator and using the parameters as arguments in the constructor. For example:

```Python
class MongeDBConnection(object):
    def __init__(self, server, port, database, collection):
        self.server = server
        self.port = port
        self.database = database
        self.collection = collection

    def __call__(self, tuple):
        #Using connection settings, save tuple in database
```

**Comment by cancilla** [comment]
+1 for adding support for submission-time parameters

**Comment by ddebrunner** [comment]
Python code can now access an application configuration, which is the preferred mechanism to store connection type info.

**Comment by ddebrunner** [comment]
Application configurations: https://streamsxtopology.readthedocs.io/en/stable/streamsx.ec.html#streamsx.ec.get_application_configuration

Submission time parameters: https://streamsxtopology.readthedocs.io/en/stable/streamsx.topology.topology.html#streamsx.topology.topology.Topology.create_submission_parameter
