### ISSUE TITLE
Functional Python: under what conditions to SPL Python operators require manual start?

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#428]
I am seeing jobs start up with python spl operators not started. There appears to be no explanation in the logs, and the presence of  "Start PE" as an IDE menu option appears to indicate that it was never started. I have seen this in two different operators in two different jobs. Starting the PE seems to work without error.

**Comment by ddebrunner** [comment]
Nothing requires a "manual" start.

Can you provide a reproducible case?

**Comment by mfeblowitz** [comment]
Not yet. I have a few ideas - one is that fusing has something to do with it.

**Comment by ddebrunner** [comment]
Closing as no update- please open an new issue with a reproducible case if there is an issue.
