### ISSUE TITLE
Functional Python: feature request: cleanup for all generated artifacts, e.g., for git 

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#429]
To simplify management of operators, it would be useful to include 
- a cleanup script to remove all generated artifacts
- .gitignore files for all generated artifacts, included when the artifacts are generated.

**Comment by wmarshall484** [comment]
When running a build there are a number of generated files which may be removed simply by calling `git clean -df` or `ant clean`. Are there certain files in particular that you had in mind to be removed?

**Comment by mfeblowitz** [comment]
For this particular case, the "extract" module creates a namespace directory and populates it with the cgt files, etc, that support a Streams SPL operator. Also there are some cache files. As these are generated by running a python script, so I'm thinking it's not similar to a traditional build.

**Comment by ddebrunner** [comment]
Basically we would like spl-make-toolkit -c be able to clean up generated artifacts, but it doesn't yet have that capability.

In the interim we could see if we could add a  -c or --clean option to the extract script.

**Comment by mfeblowitz** [comment]
That would be good. 

It’s almost doable as a script, but the script would have to harvest the namespace to be able to safely remove that.

**Comment by markheger** [comment]
should be done in spl-make-toolkit -c
