### ISSUE TITLE
How to run java application api with embedded zookeeper

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#433]
New users tend to run Streams with embedded zookeeper.

When we use the Java Application API, we are required to set the STREAMS_ZKCONNECT environment variable, so that submit job can find the zookeeper ensemble.  In the case of embedded zookeeper, what does the user have to set in the STREAMS_ZKCONNECT environment?  How should we set up the environment, just that we can run the Java Application API using embedded zookeeper?

**Comment by ddebrunner** [comment]
I'm running on the quickstart vm and it seems STREAMS_ZKCONNECT is not set in my environment.

**Comment by ddebrunner** [comment]
What sort of errors are you seeing?

**Comment by dlaboss** [comment]
Just set STREAMS_DOMAIN_ID and STREAMS_INSTANCE_ID to the existing started domain/instance to use and it should “just work” regardless of whether the domain is managed by an external or embedded zk.  

If the domain is associated with an external zk, then STREAMS_ZKCONNECT is only required and used when the user didn’t create the domain or when they have not previously accessed the domain via streamtool. (Streams maintains a cache of accessed domain info).

When the EVs are properly set the user can start an interactive streamtool with no command parameters and streamtool does not prompt for any zk connection information.  The “domain” command reports the intended domain, the “instance” command reports the intended instance, and the “getresourcestate” command works.

**Comment by chanskw** [comment]
Thank you both.  I was not in the VM and I think I  was having trouble because for some reason, my domain name was used in multiple zookeepers, so streamtool could not figure out which one to pick.  I have to check with the customer to see what errors they were getting and see if they are seeing the same error.

Thanks again!.

**Comment by dlaboss** [comment]
Perhaps you'd like to contribute some info on the topic to a new FAQ entry and/or StreamsContext.Type.DISTRIBUTED?
