### ISSUE TITLE
[Java topology] publish() throws IllegalStateException when using lambda expression

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#438]
I have the following topology application: 

```
public class Main {
	public static void main(String[] args) throws InterruptedException, ExecutionException, Exception {
		Topology t = new Topology("PubIssue");
		TStream<String> srcStream = t.strings("testing");
		TStream<MyTuple> tupStream = srcStream.transform(str -> new MyTuple(str));
		tupStream.publish("my_topic");
		
		StreamsContextFactory.getStreamsContext(Type.DISTRIBUTED).submit(t).get();		
	}
}
```

When I run this, I get the following error:
```
Exception in thread "main" java.lang.IllegalStateException: A TStream with a tuple type that contains a generic or unknown type cannot be published
	at com.ibm.streamsx.topology.internal.core.StreamImpl.publish(StreamImpl.java:413)
	at com.ibm.streamsx.topology.internal.core.StreamImpl.publish(StreamImpl.java:360)
	at Main.main(Main.java:21)
```

I tracked this down to the **_TypeDiscoverer_** class. Seems to be having some trouble figuring out the tuple type from the lambda expression. If I change the code to the following, the exception disappears and the application compiles: 

```
//		TStream<MyTuple> tupStream = srcStream.transform(str -> new MyTuple(str));
		TStream<MyTuple> tupStream = srcStream.transform(new Function<String, MyTuple>() {
			@Override
			public MyTuple apply(String v) {
				return new MyTuple(v);
			}
		});
```

**Comment by ddebrunner** [comment]
The issue is that at runtime it cannot be determined that the stream is of type MyTuple, as Java performs type erasure. Where possible we try to figure out the type when needed (e.g. for a publish), but in some cases it's not possible.

You can work around it by calling. `tupStream = tupStream.asType(MyType.class);`

Note you can also use a constructor reference instead of a lamda expression in this case:

`srcStream.transform(MyType::new)`

**Comment by dlaboss** [comment]
A good item for a FAQ, and/or improved publish() doc or improved exception message?

**Comment by cancilla** [comment]
Thanks @ddebrunner, using asType() resolved the exception. I agree with @dlaboss that this is a good item to add to docs.
