### ISSUE TITLE
Support for setting install location, domain and instance programatically

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#451]
Currently, the java topology expects the STREAMS_INSTALL, STREAMS_DOMAIN_ID and STREAMS_INSTANCE_ID environment variables to be set in order to compile and submit a distributed job. 

It would be useful if the framework allowed for setting these values programmatically. One scenario where this is useful is if I am running multiple instances under a single domain and I want to select which instance to submit the topology to. In another scenario, I may be doing comparative tests between different versions of Streams (or different fixpaks) and I want to select the specific installation when submitting the topology.

**Comment by ddebrunner** [comment]
You can set the compile version to use with this configuration property:

http://ibmstreams.github.io/streamsx.topology/doc/javadoc/com/ibm/streamsx/topology/context/ContextProperties.html#COMPILE_INSTALL_DIR

**Comment by johnmac-ibm** [comment]
I noticed recently that `InvokeCancel` also relies on the default domain / instance being set.

**Comment by markheger** [comment]
environment variables are sufficient
