### ISSUE TITLE
Add support for consistent regions

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#463]
See #462

**Comment by ddebrunner** [comment]
Pull #506 started.

**Comment by chanskw** [comment]
Tried the api, it is throwing unsupported operation exception.
Is it possible to add this support? 

In the health toolkit, a lot of the services are written using the Java Application API.  There is currently no way to enable consistent region for those services.

**Comment by ddebrunner** [comment]
Consistent region is currently supported through the Java App API with these exceptions:
 * The source cannot be a Java functional source
 * Drain is not exposed to a Java functional operator (stateful functions do correctly checkpoint and reset).

**Comment by ddebrunner** [comment]
Now supported in 1.11 for Python as well.
