### ISSUE TITLE
Windowing support for Python?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#482]
I can't find this in the documentation, does the Python topology API support windowing?  Is it possible to aggregate a set of data in a sliding window and process ?

**Comment by ddebrunner** [comment]
Not yet, it's on the list of things to do.

**Comment by ddebrunner** [comment]
Has been added:

http://ibmstreams.github.io/streamsx.topology/doc/releases/latest/pythondoc/streamsx.topology.topology.html?highlight=aggregate#streamsx.topology.topology.Window
