### ISSUE TITLE
Bug in dependency resolver -- module.__name__ doesn't always correlate with entries in sys.modules.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#496]
The dependency resolver used to find and include modules in the generated toolkit has a case where it uses module.__name__ to find the top-level package name of the module. 

It then uses the value of module.__name__ as a key to find the imported module from sys.modules.

The keys in sys.modules don't always correlate with the names in module.__name__, so users are observing a KeyError.

**Comment by wmarshall484** [comment]
This is addressed in #494

**Comment by ddebrunner** [comment]
PR #494 fixed this is master
The two commits from #494 were cherry-picked to v1_4
