### ISSUE TITLE
add '/usr/share/java' to toolkit's build classpath for JUnit JARs installed from RHEL&CentOS

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/streamsx.topology#504]
The 'common-build.xml' file expects to find the JUnit JAR files in the user's home directory (see line 20). 

If the JUnit JAR files are installed with 'yum' from the RHEL or CentOS repositories, the build will fail because the 'junit' RPM puts the JAR files in the system directory '/usr/share/java'.

I think the 'common-build.xml' file should add '/usr/share/java' to its classpath to cover both cases.

**Comment by markheger** [comment]
<fileset  id="junit.path" dir="${user.home}/.ant/lib" includes="junit-*.jar" erroronmissingdir="no"/>
  <pathconvert property="junit.jar" refid="junit.path"/>

**Comment by markheger** [comment]
<fileset  id="junit.path" dir="${user.home}/.ant/lib" includes="junit-*.jar" erroronmissingdir="no"/>
  <pathconvert property="junit.jar" refid="junit.path"/>
