### ISSUE TITLE
streamsx.topology.mqtt does not increment client count correctly

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#513]
I was poking around the code learning how things were done and I came across the following lines in publish() and subscribe():

```
 if (++self.opCnt > 1) :
            # each op requires its own clientID
            clientId =  parms['clientID']
```

I recently ran into this issue in my code so I thought I would share some knowledge. Python does not have pre-increment/decrement operators (++ or --). See this SO answer for details on what the ++ operator is actually doing (technically it's doing nothing): http://stackoverflow.com/a/1485854

The code should be changed to something along the lines of: 

```
self.opCnt += 1
 if (self.opCnt > 1) :
            # each op requires its own clientID
            clientId =  parms['clientID']
```

**Comment by markheger** [comment]
mqtt.py is no langer part of the python package.

repository contains just a copy of v1.7 in test/python/spl/tk17 (no need to change here)

-> Close this issue
