### ISSUE TITLE
Python version of readResolve() ?

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#514]
The Java Application API implements a readResolve() method for performing initialization of resources after the application is loaded. I was not able to find a similar function in the Python Application API. 

Does such a function exist? If not, consider this an enhancement request to have it added.

**Comment by ddebrunner** [comment]
Use a callable class and perform initialization in the __init__ function.

**Comment by ddebrunner** [comment]
`__init__` function that is.

**Comment by cancilla** [comment]
That's what I am doing, however the `__init__` function seems to be getting executed when I run the python application to build and launch the topology app. This is problematic when setting up a server to listen on a port. What I need is for this function to only get called when the actual topology application runs. 

Here's an app I am testing with: 

**app.py:**
```
from streamsx.topology.topology import Topology, schema
import streamsx.topology.context
from streamsx.topology import functions

from server import *

if __name__ == '__main__':
    topo = Topology("MyApp")
    srcStream = topo.source(src)
    srcStream.transform(MyServer()).print()

    streamsx.topology.context.submit("STANDALONE", topo.graph)
```

**server.py:**
```
class MyServer:
    def __init__(self):
        print("SERVER INITIALIZED!")

    def __call__(self, data):
        return data

def src():
    for i in range(10):
        yield i
```

Running `python app.py` shows the following:

```
[cancilla@jcancilla tmp]$ python app.py 
SERVER INITIALIZED!
Sep 01, 2016 11:42:58 AM com.ibm.streamsx.topology.internal.streams.InvokeMakeToolkit invoke
INFO: Invoking spl-make-toolkit
Sep 01, 2016 11:42:58 AM com.ibm.streamsx.topology.internal.streams.InvokeMakeToolkit invoke

  ...TRUNCATED...


0
1
2
3
4
5
6
7
8
9
Sep 01, 2016 11:43:12 AM com.ibm.streamsx.topology.internal.streams.InvokeStandalone$ProcessFuture get
INFO: Standalone application completed: return code=0

```

As you can see from the above output, "SERVER INITIALIZED" occurs before the app begins compiling and doesn't get called again when the app actually runs.

**Comment by ddebrunner** [comment]
Yeah, sorry, I was more thinking of the decorated callable classes that get used for SPL operators.

It does seem we might want a form of transform (etc.) like: `srcStream.transform(MyStream)`
which would create an instance of the class at runtime, rather than an instance at topology definition time and pickle the object to be depickled at runtime.

This could then be expanded possibly to include arguments to the `__init__`:

````
class MyServer:
    def __init__(self, a, b, c):
        pass

srcStream.transform(MyServer, 1,2,3)
````

**Comment by ddebrunner** [comment]
`readResolve` is actually provided by the Java serialization api, and Python has equivalent functionality:

`__setstate__`  and `__getstate__`

https://docs.python.org/3/library/pickle.html

This is probably what you are trying to do:
https://docs.python.org/3/library/pickle.html#handling-stateful-objects

In the example the pickled object doesn't include the file handle, but it is reopened when the object is depickled.

The great thing about Python is that there is usually a hook that allows you to do anything you need.

**Comment by cancilla** [comment]
Thank you!! That's exactly what I was looking for. For reference purposes, here is an updated version of the above-mentioned code: 

**server.py:**
```
class MyServer:
    def __init__(self):
        pass

    def __call__(self, data):
        return data

    def __getstate__(self):
        return self.__dict__.copy()

    def __setstate__(self, state):
        self.__dict__.update(state)
        print("SERVER INITIALIZED!")

def src():
    for i in range(10):
        yield i
```

**Comment by ddebrunner** [comment]
Python classes used in either SPL operators or Python Application api now also support the Pythonic `__enter__` and `__exit__`.

**Comment by ibmkendrick** [comment]
Should this be closed?

**Comment by ddebrunner** [comment]
I need to add some more docs around __enter__/__exit__.

**Comment by ddebrunner** [comment]
Added more docs in pr #825
