### ISSUE TITLE
Build is broken when building with Anaconda 2.7.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#523]
I downloaded Anaconda 2.7 and set my PYTHONHOME, PATH, PYTHONPATH, and LD_LIBRARY_PATH correctly. `ant all` fails with the following errors:

```
...
extract:
     [exec] Fatal Python error: Py_Initialize: Unable to get the locale encoding
     [exec] ImportError: No module named 'encodings'
     [exec]
     [exec] Current thread 0x00007f8d055e7740 (most recent call first):
     [exec] Result: 134
     [exec] CDISP9022I The /homes/hny4/wcmarsha/git/streamsx.topology/samples/python/com.ibm.streamsx.topology.pysamples/com.ibm.streamsx.topology.pysamples.positional/PrintTuple/PrintTuple_h.pm file is being generated.
     [exec] CDISP9022I The /homes/hny4/wcmarsha/git/streamsx.topology/samples/python/com.ibm.streamsx.topology.pysamples/com.ibm.streamsx.topology.pysamples.positional/PrintTuple/PrintTuple_cpp.pm file is being generated.

...

test.toolkit:
     [exec] Fatal Python error: Py_Initialize: Unable to get the locale encoding
     [exec] ImportError: No module named 'encodings'
     [exec]
     [exec] Current thread 0x00007fc8abb7b740 (most recent call first):

BUILD FAILED
/homes/hny4/wcmarsha/git/streamsx.topology/build.xml:17: The following error occurred while executing this line:
/homes/hny4/wcmarsha/git/streamsx.topology/test/python/build.xml:22: exec returned: 134

Total time: 41 seconds
```

**Comment by wmarshall484** [comment]
@sdickes

**Comment by sdickes** [comment]
python 2.7 support is not ready/commited yet.

**Comment by wmarshall484** [comment]
This was on the current master branch.

**Comment by wmarshall484** [comment]
Some preliminary debugging reveals that the following files (at least) still have explicit dependencies on python3.

**com.ibm.streamsx.topology/bin/spl-python-extract.py**
Relies on the `signature` and `Parameter` components of the `inspect` module. A 2.7 alternative is `signature` and `Parameter` from the `funcsigs` module (note that funcsigs does not come with Python3.5 by default, so you might want to find a way of switching between the two depending on the the version of Python which is running.

**com.ibm.streamsx.topology/opt/python/packages/streamsx/spl/spl.py**
Same issue as above.

**samples/python/build.xml**
Explicitly invokes python3 during an exec step.

Additionally, the following file needs to be created, otherwise python 2.7 won't recognize streamsx as a package:
**com.ibm.streamsx.topology/opt/python/packages/streamsx/__init__.py**

**Comment by ddebrunner** [comment]
The official releases will use Python 3.5 to build the toolkit, which will then work on Python 3.5 and 2.7.

So this is low priority to allow building the toolkit on 2.7.

**Comment by ddebrunner** [comment]
Closing this as we require building on Python 3.5 but it produces a toolkit/package that runs on Python 2.7.
