### ISSUE TITLE
Enable ThreadedPort with drop policy to be specified, specifically on the subscribe function

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#529]
This is an enhancement request.  To allow new developers to write Python analytics without putting back-pressure on SPL Ingest analytics, having the ability to specify that a Streams threadedPort with drop policy be added to the way that the subscribe is implemented in the SPL that is generated would be a big help to enterprise environments.  

- [x] SPL `Subscribe` support - #1551
- [x] SPL `FilteredSubscribe` support - #1559
- [x] Python support - #1614
- [ ] Java support

**Comment by ddebrunner** [comment]
Here's what I'm going to implement.

New optional parameters for `Subscribe` : 

- `connect` - Connection mode - `Direct` or `Buffered`
- `bufferFullPolicy` - The congestion modes from threadedPort queue: `Sys.{Wait,DropFirst,DropLast}`
- `bufferCapacity` - Size of the queue.

For example:

```
use com.ibm.streamsx.topology.topic::Subscribe;
use com.ibm.streamsx.topology.topic::Buffered;
...

     stream<String> S = Subscribe() {
       param topic: 'drinks';
       streamType: String;
       connect: Buffered;
       bufferPolicy: Sys.DropLast;
     }
```

**Comment by ddebrunner** [comment]
Initial SPLDOC.

![image](https://user-images.githubusercontent.com/3769612/37063545-9298812c-214e-11e8-8f70-55e5c232f50c.png)

**Comment by ddebrunner** [comment]
Example use - no slow app:

![image](https://user-images.githubusercontent.com/3769612/37063566-a80a6ee4-214e-11e8-985b-36e5fec3fd84.png)

Slow Exploratory app added with `Buffered` and `Sys.DropLast`:

![image](https://user-images.githubusercontent.com/3769612/37063853-adcbd6c8-214f-11e8-8705-d89f69868b4d.png)

**Comment by bmwilli** [comment]
Looks great. Thanks.
