### ISSUE TITLE
Please allow for ant version at v 1.9.2 

### ISSUE THREAD

**Issue by mfeblowitz** [IBMStreams/streamsx.topology#530]
We've built a docker container for use of Streams and our BTN application. We favor versions of software that are aligned with the OS version and are yum-installable. 

As we understand it, the yum version for RHEL and CentOs is only at 1.9.2. 

All instructions we've seen for installing ant at a higher level involve 
- yum remove for ant
- a wget of the desired ant version
- establishing a few symlinks 

So far, the only issue we encountered with 1.9.2 was a hard stop on the line `failonwarning="yes" from`,  when running  "ant doc"

Would it be possible to remove that line from build.xml at to support 1.9.2?

**Comment by ddebrunner** [comment]
See pr #622

**Comment by ddebrunner** [comment]
fixed,
