### ISSUE TITLE
subscribe with SPL schema sending to a sink seg faults when run

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#531]
The following code fails:
...
spl_publish_schema = schema.StreamSchema("tuple<rstring name, uint64 seq>")
topo = Topology("python_subscribe")
spl_publish_in = topo.subscribe("spl_publish",spl_publish_schema)
spl_publish_in.sink(print)
...

The root_cause is that the PyFunctionSink_cpp.cgt generates code in the constructor:
PyObject \* depickleInput = streamsx::topology::Splpy::loadFunction("streamsx.topology.runtime", "dict_in");

the function "dict_in" does not exist in runtime.py.

It looks like it either needs to exist, or the call that should have been generated is "spltupleDict_in"

A work around is to insert a noop transform between the subscribe and the print.

**Comment by ddebrunner** [comment]
I believe this is fixed in master.

**Comment by ddebrunner** [comment]
Python test2_spl2Python tests this and shows it is fixed.
