### ISSUE TITLE
Is it possible to retrieve and plot a Streams view that already exists in the Streams instance

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#537]
Is it possible and any examples of instantiating a view object in jupyter for an existing @view in a streams instance created by an SPL job?  After playing with the view interaction from Python topologies I started looking at the rest.py and topology.py files.  

Before I go much further, is there a way to interact with a view that was created by an SPL program?

This would be a another great use case

**Comment by ddebrunner** [comment]
here is some sample code showing how you can use the rest API to get data from an individual view. It's more manual than using `stream.view()` in the Python API, but you can do it if you know the SWS API url (from `streamtool geturl --api`), the SWS username/password, and the name of the view.
```
from streamsx import rest

################             username             password      SWS url
sc = rest.StreamsContext("streamsadmin", "passw0rd", "https://streamsqse.localdomain:8443/streams/rest/resources")
my_instance = sc.get_instances()[0]

# Or whichever view you need.
view = my_instance.get_views()[0]

items = view.get_view_items()
for itm in items:
    print(itm)
```
Output:
```
{'collectionTime': 1473703306609,
 'data': {'jsonString': '{"val": 4.782121394132322}'},
 'resourceType': 'viewItem',
 'rest_connection': <streamsx.rest.StreamsRestConnection object at 0x7fd3556142b0>}
{'collectionTime': 1473703306660,
 'data': {'jsonString': '{"val": 4.805457516595481}'},
 'resourceType': 'viewItem',
 'rest_connection': <streamsx.rest.StreamsRestConnection object at 0x7fd3556142b0>}
{'collectionTime': 1473703306711,
 'data': {'jsonString': '{"val": 4.77007267990546}'},
 'resourceType': 'viewItem',
 'rest_connection': <streamsx.rest.StreamsRestConnection object at 0x7fd3556142b0>}
...

**Comment by bmwilli** [comment]
Thanks Dan!

**Comment by ddebrunner** [comment]
FYI - credit where credit is due, it's a copy of post from @wmarshall484

**Comment by ddebrunner** [comment]
@bmwilli We would be interested in feedback on improving this. E.g. I think it would be useful in the REST api to get a view based upon its name (and maybe job id, whatever is required).

And i think there is some code in topology that we need to move to the rest api to provide a stream of tuples from the view back to Python, so you don't have to figure out removal of already seen tuples yourself)

**Comment by bmwilli** [comment]
@ddebrunner Funny you should mention that.  I was just thinking about functions that would be very useful in the Python rest api.  The first one's I thought of were:
* get_instance_by_name
* get_job_by_name
* get_job_by_id
* get_view_by_name

I really like your idea of pulling forward some sort of iterator on the view that would account for already seen tuples.

Any way to dynamically create a view (like is done via Console Application Dashboard for a stream in the graph) from python so that a topology would not even have to be submitted?

**Comment by bmwilli** [comment]
Re-opened as a place for more comments and suggestions.

**Comment by ddebrunner** [comment]
Recent updates to the Python REST api support include the ability to filter some returned objects using id or name (name filtering uses a regular expression). A list of items is still returned.

Here's a couple of examples:

```
        for instance in self._sc.get_instances(id=self._sc.instance_id):
            jobs = instance.get_jobs(id=self.job_id)
```

```
    for op in self.job.get_operators():
            metrics = op.get_metrics(name=Condition._METRIC_PREFIX + '*')
```

**Comment by ddebrunner** [comment]
Also I believe @wmarshall484 moved the code to get the contents of a view to the rest api so it can be used against existing views in an instance (including on Bluemix).

**Comment by wmarshall484** [comment]
I'm closing this issue given the support for obtaining operators and views via regular expressions.

Methods such as
* get_instance_by_name
* get_job_by_name
* get_job_by_id
* get_view_by_name

Are no longer necessary.
