### ISSUE TITLE
Request to be able to integrate with host pool tags for Python analytic isolation

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.topology#545]
A use case I see in my customer would be one part of a domain/instance used for production ingest and analytics that are high-speed, low-latency along with a Python "sandbox".  I implemented a "Python Adapter" job which was a Streams Import (complex subscription rules and possibly filters) followed by a publish operator.  I could then imagine the desire to use the new 4.2 restricted access resources and resource tags to isolate python analytics on a subset of resources.  

I believe this would require the ability to specify a tag on the Python topology for the host pool to use.

Thoughts?

**Comment by ddebrunner** [comment]
The Java Application API (topology) supports resource tags already, and so the framework exists to support it in Python, since the underlying code (SPL generation) is the same in both.

**Comment by ddebrunner** [comment]
1.7 includes the ability to set resource_tags:

http://ibmstreams.github.io/streamsx.topology/doc/releases/1.7/pythondoc/streamsx.topology.topology.html#streamsx.topology.topology.Stream.resource_tags

Need to check to see if it works for a `for_each` as well.

**Comment by ddebrunner** [comment]
Still needs to be added for `Sink`. (for_each).
