### ISSUE TITLE
Document clarification requested (Streams Forum): Streams Java API classpath entry

### ISSUE THREAD

**Issue by StanBury** [IBMStreams/streamsx.topology#555]
Please see the following forum entry regarding adding Streams Java API classpath requirements to this document:  
       http://ibmstreams.github.io/streamsx.topology/doc/scaladoc/index.html#package 
Forum post:
https://developer.ibm.com/answers/questions/305913/the-classpath-for-creating-streams-scala-applicati.html#answer-308227

**Comment by ddebrunner** [comment]
In theory the command the user tried should have worked, since the `-usemanifestcp` should have picked up the right jars.
