### ISSUE TITLE
Rebased to latest set of commits and cannot build

### ISSUE THREAD

**Issue by sdickes** [IBMStreams/streamsx.topology#563]
I rebased to the latest of commits and did an ant clean followed by ant and get this error. Might I be missing a dependency on my dev system?

test.toolkit:
     [exec] Checking  /home/sdickes/StreamsGit/sdickesFork/streamsx.topology/test/python/spl/testtkpy/opt/python/streams/spl_samples.py for operators
     [exec] Traceback (most recent call last):
     [exec]   File "/home/sdickes/StreamsGit/sdickesFork/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 276, in <module>
     [exec]     dynm = imp.load_source(name, mf)
     [exec]   File "/usr/local/lib/python3.5/imp.py", line 172, in load_source
     [exec]     module = _load(spec)
     [exec]   File "<frozen importlib._bootstrap>", line 693, in _load
     [exec]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
     [exec]   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
     [exec]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
     [exec]   File "/home/sdickes/StreamsGit/sdickesFork/streamsx.topology/test/python/spl/testtkpy/opt/python/streams/spl_samples.py", line 70, in <module>
     [exec]     @spl.map()
     [exec] AttributeError: module 'streamsx.spl.spl' has no attribute 'map'

**Comment by ddebrunner** [comment]
Do you have another older version of the toolkit in your PYTHONPATH or STREAMS_SPLPATH?

**Comment by sdickes** [comment]
PYTHONPATH  was the trouble. Thanks
