### ISSUE TITLE
Shall we open a new branch for toolkit globalization

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.topology#590]

**Comment by joergboe** [comment]
Starting from branchv1_4 we plan to implement localization support for the internet toolkit.

Shall we open a new branch for this work?
Proposal:
    use new branch v1_4_5 branched from v1_4
    new branch is targeted for FP for Streams 4.2.1

    bump version number from 1.4.4 to 1.4.5

    branch v1_4 can still be used as FP for Streams versions prior to 4.2.1

**Comment by ddebrunner** [comment]
Bumping the version number to 1.4.5 doesn't work as it leaves no room for future changes to 1.4.

Is there any reason though to create a branch, I assume globalization won't change the api at all, so can it just be a pull request to the v1_4 branch?

**Comment by joergboe** [comment]
Globalization is a new feature. This justifies and requires a new toolkit version.
A new feature justifies an increment of the minor version so we should use 1.5.x for the translation work.
The version 1.4 is shipped with streams 4.2.0.
So potential fixpacks can use toolkit version 1.4.5...
The translation is done in toolkit version 1.5.x
And the master brach should be bumped to version 1.6

**Comment by ddebrunner** [comment]
Why is it a new feature in terms of semantic versioning, an application still has the same api.

But sounds like it will just be pull requests to master which will be shipped as part of the 1.5 release.

**Comment by joergboe** [comment]
Yes, this feature should be finally merged into the master and will be shipped as part of future versions.
But at the moment it developed based on tool kit version 1.4.x and is targeted for streams version 4.2.1.
For this work I want to have a dedicated tool kit version number, which indicates
- the functional change and
- the compatible API.

Our guidelines for tool kit versioning states:
1)  If the tool kit only contains minor 'fixes', bump the 3rd digit.
2)  If the tool kit contains 'significant' new functions, but it will continue to be compatible with previous version, bump the 2nd digit
3)  If the tool kit contains incompatible changes, bump the first digit.

In my opinion the globalization work is more than a fix. But may be, that this function is not significant enough to justify the bump of the 2nd digit.

So I see 2 choices:
1. The translation is done in tool kit version 1.5.x and the master branch should be bumped to version 1.6 or higher (2.x). A new branch v1_5 is created for the globalization work.
 
2. The translation is done in tool kit version 1.4.100. The work uses branch 1_4 and the version 1.4.4. is labelled with a tag.

**Comment by joergboe** [comment]
Sorry the issue was closed by mistake.

**Comment by ddebrunner** [comment]
There's some chance that the current work in master will be shipped in 4.2.1.

**Comment by joergboe** [comment]
So I will first create the globalization pull request for the master branch
