### ISSUE TITLE
Globalizing the toolkit

### ISSUE THREAD

**Issue by gertmark** [IBMStreams/streamsx.topology#596]
Provide log messages for different locales via unique message ids: German (de_DE), French (fr_FR), Italian (it_IT), Spanish (es_ES). Brazilian Portuguese (pt_BR), Japanese (ja_JP), Simplified Chinese (zh_CN), Russian (ru_RU), Traditional Chinese (zh_TW), Korean (ko_KR). 
#590

**Comment by joergboe** [comment]
This is finished. Toolkit logs are generated in languages de, fr, it, es, pt, ja, ru, zh_CN or zh_TW depending on locale.
