### ISSUE TITLE
Modify the StreamingAnalyticsService and Distributed contexts to automatically submit to a remote build service if a local streams install is not present.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#606]
Currently, in order to choose the correct context, a user must know whether he/she is submitting from a system that contains a Streams install.

What should happen is the following -- the topology toolkit will automatically detect whether there is a Streams install and perform the correct corresponding action:

**If the system has a Streams install:**

Context | Action
------------ | -------------
Distributed | The application is compiled locally and submitted to an instance via streamtool
StreamingAnalytics | The application is compiled locally, and submitted to a BlueMix instance via REST

**If the system does *not* have a Streams install:**

Context | Action
------------ | -------------
Distributed | The application is compiled on a remote build farm and submitted to a non BlueMix instance
StreamingAnalytics | The supplied VCAP file is used to submit to a build farm within BlueMix, where the application is compiled, and from which the application is submitted as a job (most likely, this will call out to the RemoteBuildAndSubmitRemoteStreamsContext)

**Comment by ddebrunner** [comment]
there should also be a config option to force a remote build even if there is a local install.

**Comment by ddebrunner** [comment]
For 1.5 only need to support analytics service. Supporting distributed requires adding JMX support.

**Comment by wmarshall484** [comment]
Closing to split this into two separate issues.
