### ISSUE TITLE
With Streams 4.2, Python applications submitted with 'BUNDLE' context are fused into a single PE, even if .isolate() is used.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#626]
In the following application, I would expect two PEs to be created upon job submission:
```python
from streamsx.topology.topology import Topology
from streamsx.topology.context import submit

t = Topology("myTop")
st = t.source(['hello', 'world', "Something else"])
st.isolate().sink(lambda x: print(x, flush=True))

submit("BUNDLE", graph=t)
```
When the created .sab is submitted via streamtool, it results in a running application with all operators fused into a single PE. 
![pes](https://cloud.githubusercontent.com/assets/4752570/20371643/0c4b493c-ac1b-11e6-88d4-b36653872c91.JPG)

Haven't tested with Java yet, but I'll post an update; I expect the results should be the same.

**Comment by ddebrunner** [comment]
Which streams version is this?

**Comment by ddebrunner** [comment]
If it's 4.2 then it's somewhat expected, it's this issue #387
