### ISSUE TITLE
Is it possible for an endless source to accept an input stream?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#629]
I am trying to use the Java Application API to write an application that ingests some custom JSON data.  I am not able to use the JSONToTuple operator because the JSON schema is very customized and I needed more control on how data is parsed and mapped to a tuple.

I want my application to implement this application pattern, by using the Java Application API:

DirectoryScan -> FileSource -> GSON -> more processing...

I have created an endless source that combines this subgraph:  FileSource->GSON processing.  However, with an endless source, there is no way for it to accept the output stream from the DirectoryWatcher.  I have tried multiple ways to implement this with Java, but can't seem to find a good way.  Is it possible for an endless source to accept an input stream?  

I have also tried implementing this pattern using "multitransform".  In it, directory watcher sends filenames to my parser.  In the parser, I take the filename, read the file and parses its content.  The problem I run into here is that I am not able to submit tuples downstream when I am processing the data.  The end result is that I must process the file entirely before I can send any data downtstream.  The files that I am dealing with is big, and it could cause memory problem.

I think I can achieve this with writing a Java primitive operator, but thought maybe we can also do this using the Java Application API, but I just haven't found a way yet.

**Comment by dlaboss** [comment]
I'm probably missing something, and have been away from the Java API for some time, but here it goes anyway :-)
I take it that a single text line from the file doesn't completely represent a single JSON string - if it did then your JSON to Tuple processing could all just be a single (or pipeline of) transform()'d streams. (Also if you hadn't noticed the Java API has direct support for JSON that might be helpful - see its JSONStreams class).

If a single JSON object/string is represented as multiple lines in the file, then I'd just have the transform function collect as many lines as needed, returning null for each non-terminating text line String collected, and then return a single String for the whole JSON object, once the final text line was received.  e.g.,
```
    TStream<String> jos = FileStreams.textFileReader(FileStreams.directoryWatcher(...))
                                  .transform(t -> {  multiline-json-collector })
    TStream<JSONObject> jo = JSONStreams.deserialize(jos)
    jo = jo.transform( transform the JSONObject to another that's in the form of what you need )
```

**Comment by chanskw** [comment]
Thank you Dale.  I did not know about JSONStreams.  However, I am not sure if this approach will work for me.  The problem is that the file that I am dealing with is really big.  I wanted to create a streaming json parser using the gson streaming api.  If I have to collect enough lines so that the JSON deserialize function will work, I am not exactly sure how much to collect and when to start / stop.  And it seems really clunky.

See the JSonReader example here:
https://www.mkyong.com/java/gson-streaming-to-read-and-write-json/

I wanted to read JSON on the fly and submit tuples on the fly with the Java Application API, without having to do any buffering.  I think the problem I run into now is that all the functions in topology are synchronous, so it forces me to process the whole file, and return a list of records.  It will be nice if there is a way to submit tuples asynchronously, if this makes sense?

**Comment by dlaboss** [comment]
The Java API only has "pull based" source stream generators - i.e., essentially everything boils down to application code providing a Supplier who's get() is called to get the next tuple.
Fyi, the Edgent API includes a push based source stream generator (Topology.events(...)). I guess that form of API could be leveraged to avoid buffering.

In the absense of that might something along the lines of the following do the trick?
Is the buffering/thread-switching simply unacceptable for your app?

```
TStream<String> fileNames = FileStreams.directoryWatcher(...)
TSTream<JSONObject> jos = StreamingJsonParser.parse(fileNames);

class StreamingJsonParser {

  public static TStream<JSONObject> parse(TStream<String> fileNames) {
    Parser parser = new Parser();
    fileNames.sink(parser);
    return fileNames.topology().endlessSource(parser);
  }

  private static class Parser implements Consumer<String>, Supplier<JSONObject> {
    private int	JOQ_SIZE = 1;  // or larger as that suites you
    private final BlockingQueue<JSONObject> joq = new ArrayBlockingQueue<JSONObject>(JOQ_SIZE);

    // the Consumer side
    public void accept(String fileName) {
      JSONReader reader	= new JSONReader(...fileName...);
      incrementally consume / process the reader,
      for each incrementally produced JSONObject "jo"
        joq.put(jo)  // a blocking put
    }

    // the Supplier side
    public JSONObject get() { return joq.get() /* blocking get() */ }
  }
}
```

**Comment by chanskw** [comment]
Thanks Dale.  I implemented something very similar to this but found it very "hacky".  In my code, I created a parser object and then use the transform as the consumer side.  In there, I parse the file and submit tuple to the tuple queue.

On the supplier side, I take the tuple from the queue and return it for the `get` method.  The issue here is that the parser object that gets called by the `transform` method and the one being called as the `endless` source are actually two separate instances.  For the two sides to talk to each other, I must make the tuple queue static and make sure both instances of the parser objects are fused into the same PE.  While this works, I find this hacky and not sure that this is the right thing to do.

I think it is a good idea to have the push API in topology as well.  I am also wondering if there is a way for both calls to use the same parser object?  

Hope this makes sense...

Here's my topology code:

```
MyParser parser = new MyParser();

TStream<String> parserStream = jsonFiles.transform(filename -> {
	try {
		parser.parseFile(filename);
	} catch (Exception e) {
		TRACE.error("Unable to parse file conent.", e);
	}
	return null;
	});		
		
// NOTICE THE COLOLOCATE HERE
TStream<MyModelObject> bmeStream = topology.endlessSource(parser).colocate(parserStream);   

In the parser:

public class MyParser implements Serializable, Supplier<MyModelObject> {
    
       // NOTICE THE STATIC QUEUE HERE
	private static BlockingQueue<MyModelObject> tupleQueue = new ArrayBlockingQueue<>(1000);

    // on the consumer side, where I parse:
    public List<MyModelObject> streamingParse(String urlStr) throws IOException {
         // parse the file and create a stream for the Gson reader

        JsonReader reader = new JsonReader(new InputStreamReader(iStream));

			reader.beginObject();

			String rootTag = null;

			while (reader.hasNext()) {
                                // finished parsing and put tuple onto tuplequeue
                                tupleQueue.put(tuple);                        
                         }
    }

    // on the supplier side, I take the tuple from the queue and return
    @Override
	public MyModelObject get() {

		MyModelObject tuple = null;
		try {
			tuple = tupleQueue.take();
		} catch (InterruptedException e) {
			TRACE.error("Internal parser error.", e);
		}

		return tuple;
	}
}
```

**Comment by dlaboss** [comment]
Upon further thought, I think you can get the behavior your need with just multiTransform!
More on that in the next "comment" but first, just to flesh out / put something out there for what I think you really want:
```
<R> TStream<R> incrementalMultiTransform(BiConsumer<T,Supplier<Consumer<R>>> transformer);
```
And a transformer.accept() impl would do something like:
```
transformer.accept(String fileName, Supplier<Consumer<JSONObject>> consumerSupplier) {
  Consumer<JSONObject> consumer = consumerSupplier.get() // runtime supplied consumer
  MyParser parser = new MyParser(fileName);
  JSONObject jo
  while ((jo = parser.getNextObject()) != null)
      consumer.apply(jo) // adds the jo to the output stream
}
```

**Comment by dlaboss** [comment]
Since multiTransform's transformer.apply(T t) returns an Iterable<U> I think apply() can just immediately construct and return an Iterable and all of the incremental parsing and incremental generation of JSONObject can be lazilydone by the Iterable.iterator() returned Iterator's hasNext()/next().

Something like:
```
TStream<JSONObject> jo = FileStreams.directoryWatcher(...).multiTransform(new StreamingParser());

class StreamingParser implements Function<String,Iterable<JSONObject>> {
  public Iteratable<JSONObject> apply(String fileName) {
    return new Iterable<JSONObject>() {
        private FileParser parser = new FileParser(fileName);
        public Iterator<JSONObject> iterator() {
          return parser;
        }
    };
  }
}

class FileParser implements Iterator<JSONObject> {
  private final JSONReader reader;
  private JSONObject nextJo;
  private boolean done;
  FileParser(String fileName) {
    reader = new JSONReader(...fileName...);
  }
  public boolean hasNext() {
    if done return false;
    if nextJo != null return true;
    nextJo = getNextObject()
    done = nextJo == null;
    return nextJo != null;
  }
  public JSONObject next() {
    JSONObject jo = nextJo;
    nextJo = null
    return jo
  }
  private JSONObject getNextObject() {
    parse / build the next object (reader.beginObject(), while reader.hasNext(), ...)
    return the next JSONObject or null if the file has been fully processed
  }
}

```
