### ISSUE TITLE
How to specify a different username and pw at job submission

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#637]
I am working on a Java topology application.  I am using the Streams QSE to do development, and then I want to submit my job to a remote server for testing.

I can achieve this by specify streams domain, and instance environment variables.

However, the username and password between the two systems are different and I am getting errors on job submission.  I am trying to submit as distribute.  Is there a way to specify a different user id and password for job submission?

**Comment by ddebrunner** [comment]
Not at the moment, but looking into how to support it with a local streams install (i.e. streamtool submit job will work with a remote instance).

**Comment by markheger** [comment]
1.13.15 contains Java remote build support
