### ISSUE TITLE
NPE when setting subscribe topic via submission parameter

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#638]
I’m building a Java topology app where I need to subscribe to a topic. I want to be able to specify the topic using a submission-time parameter. I tried using the Topology.createSubmissionParameter(…) call, but I end up getting an NPE. Code snippet and exception are below. 

    Supplier<String> subscriptionTopic = topo.createSubmissionParameter("subscription_topic", String.class);
    TStream<String> src = topo.subscribe(subscriptionTopic.get(), String.class);
    src.print();

  
    Exception in thread "main" java.lang.NullPointerException
        at com.ibm.streamsx.topology.Topology.checkTopicFilter(Topology.java:477)
        at com.ibm.streamsx.topology.Topology.subscribe(Topology.java:435)
        ...

**Comment by ddebrunner** [comment]
It's because subscribe expects a fixed string, and you are passing `null` since `subscriptionTopic` is a `Supplier` that will be valid at runtime, not topology creation time.

We need a overload of `subscribe` that accepts submission parameters.
