### ISSUE TITLE
Standalone not printing all output when invoked from eclipse

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#64]
When I run my app with a STANDALONE context from eclipse, I get only one line of my expected output.
````
....
INFO: Streams Application Bundle produced: demoapp.ProcessLines.sab
Jul 01, 2015 11:24:45 AM com.ibm.streamsx.topology.internal.streams.InvokeStandalone invoke
INFO: Invoking standalone application
{myextractor.DoubleNegative={[[25-38]: 'not unwilling'(1 fields)]}}
````
When I run the sab file directly (`./demoapp.ProcessLines.sab`) I get all the expected lines.  Is this the expected behavior?

**Comment by ddebrunner** [comment]
How are you executing it?

**Comment by hildrum** [comment]
I see the problem when I execute from the eclipse menu--ie, run as, java application.

**Comment by ddebrunner** [comment]
What does you submission code look like, it  sounds like you are not waiting for the application to complete.

**Comment by hildrum** [comment]
How I'm running it:
<img width="766" alt="screen shot 2015-07-04 at 9 42 08 am" src="https://cloud.githubusercontent.com/assets/5419652/8508111/4346b31a-2231-11e5-81b6-fcf044825d3c.png">

The result when I run it via StreamsStudio.    As far as I can tell, it's done.  The little box that is red when it runs has stopped being red, anyway.  There's only one line of output, the first line.
<img width="429" alt="screen shot 2015-07-04 at 9 43 26 am" src="https://cloud.githubusercontent.com/assets/5419652/8508114/7081e156-2231-11e5-93d5-ab518ee891d7.png">

For comparison, here's what I get when I run it on the command line:
<img width="533" alt="screen shot 2015-07-04 at 9 43 55 am" src="https://cloud.githubusercontent.com/assets/5419652/8508120/b00ef25a-2231-11e5-8d9c-a77a664b770b.png">

**Comment by ddebrunner** [comment]
Can you show your java code that does the submission to the StreamsContext.

**Comment by hildrum** [comment]
It was: `StreamsContextFactory.getStreamsContext("STANDALONE").submit(flow);`
But now I understand what's you mean by "not waiting for the application to complete", as  I'm missing the `get` you have in the examples.  I added the `get` and it works as expected.  Closing.
