### ISSUE TITLE
[Python API] Enable callable classes defined in the Python interpreter to be used in the primitive operators..

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#640]
Currently, we mandate that all callable classes and functions be defined at the top level in a module. We required this because, initially, our primitive operators could only call out to functions to perform operations.

Now that we use Dill to perform serialization, we serialize lambdas and classes, pass the bytes to the operator as a parameter, and then deserialize then upon operator initialization. As such, they do not need to be defined at the top level in a module; they can be defined right in the interpreter. 

We support this with lambdas, but I don't believe it currently works with callable classes.

**Comment by ddebrunner** [comment]
Fixed.
