### ISSUE TITLE
IBM streams classloading issue

### ISSUE THREAD

**Issue by afilichkin** [IBMStreams/streamsx.topology#645]
I'm using IBM Streams 4.1.1 I can't use Elasticsearch client in my Java operator, because it has transitive dependency guava-18.0 lib

```
 <groupId>org.elasticsearch</groupId>
 <artifactId>elasticsearch</artifactId>
 <version>2.3.2</version>
```
When I submit my job I see NoSuchMethodError : com/google/common/util/concurrent/MoreExecutors.derectExecutor

It happens because IBM stream has in ext/lib guava-14. How to solve this issue?

**Comment by ddebrunner** [comment]
See answer: https://developer.ibm.com/answers/questions/332772/java-operator-classloader-issue.html

**Comment by ddebrunner** [comment]
Closing as answered and not related to this project.
