### ISSUE TITLE
Publish/Subscribe vs Import/Export? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.topology#646]
Do we have any documentation or articles discussing the merits of Publish/Subscribe vs Import/Export? Generally, I have used Import/Export, but I'm wondering if I'm just stuck in it because it's been around for longer. 

The topic approach is nice and clean, but seems similar to the export and import using properties.

**Comment by ddebrunner** [comment]
Publish/subscribe is a simplification of Import/Export that has these benefits over Import/Export:

- Follows a well-known publish/subscribe design pattern.
- Supports a true microservice approach where the publisher and subscriber are truly independent. Import/Export requires that the importer fully understand how any exporter is exporting its stream.
   * For example with publish/subscribe each side can be in a parallel region of any width (or no parallel region) and the correct tuples are delivered to the subscribing application. 
   * The publisher may or may not allow filters but the subscriber will always receive the correct data. (With Import/Export the importer must know if the exporter allows filters or not)
 - For Java/Python/Scala developers no knowledge of SPL expressions is required.
 - For SPL developers, no need to have to figure out how to represent a SPL expression as an `rstring` (with escaping of quotes etc.).
 - Designed to allow a microservice approach across any application implementation language, by having the publish/subscribe concept exposed in the IBM Streams programming apis for Java/Scala & Python.

**Comment by ddebrunner** [comment]
and publish/subscribe supports submission time values for the topic.

**Comment by Alex-Cook4** [comment]
Thanks @ddebrunner! If I publish a stream and there are 15 apps importing it, and one of the apps is very slow, does this slow down the publishing job the same way it does for import/export?

**Comment by ddebrunner** [comment]
Yes, since the underlying mechanism is Import/Export. 

You can add a threaded port after the `Subscribe` or even a buffering microservice that publishes the same tuples under a different topic. 

But at the end of the day you can only run as fast as the slowest component. 

Streams 4.2 adds a property on `Export` (I think) to disconnect a slow connection, `Publish` doesn't yet support that.

What sort of behaviour do you want in that case of a very slow subscriber?

**Comment by Alex-Cook4** [comment]
I didn't know about that option on the Export in Streams 4.2. I hadn't thought of the buffering microservice, that's a good idea. 

If there was a way from the export side to force a ThreadedPort-like implementation, it seems like that would fit well in the microservice architecture. "We don't want to be restrictive on who can connect to my microservice, but we don't want it to be able to just bog it down" With this approach, the "bad" or "slow" jobs can still get some data instead of being disconnected.

**Comment by ddebrunner** [comment]
> Streams 4.2 implements safeguards which will prevent a downstream slow application to create backpressure - one can specify that the tuples for slower downstream application will be dropped

Technically a slow downstream application is disconnected (according to the congestionPolicy [1]), which will then result in dropped tuples as it is disconnected. It's not clear from the documentation what happens then, never reconnected, reconnnected after some time etc.

The plan is to add such functionality to `Publish`, just need to figure out how to do it in a backward compatible way.

[1] http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.toolkits.doc/spldoc/dita/tk$spl/op$spl.adapter$Export.html

**Comment by markheger** [comment]
> Technically a slow downstream application is disconnected (according to the congestionPolicy [1]), which will then result in dropped tuples as it is disconnected.

When congestion is detected on an Export port than the connection is dropped and automatically re-established in the same way as the connection would have been dropped due to other reasons.  The Export in Streams 4.2 does not support to "reconnect after some time".

**Comment by dakshiagrawal** [comment]
> When congestion is detected on an Export port than the connection is dropped and automatically re-established in the same way as the connection would have been dropped due to other reasons. The Export in Streams 4.2 does not support to "reconnect after some time".

If the reconnection happens quickly (say immediately after dropping as the network connectivity is still there and perfect), then all disconnect would do is to drop all tuples which were in TCP/IP pipe, right? In this case, depending on how quickly the tuples are flowing, we will see connection dropped/reconnected rather frequently which is kind of ugly but it still works to protect other applications.

**Comment by markheger** [comment]
> all disconnect would do is to drop all tuples which were in TCP/IP pipe, right?
Correct, all tuples in the TCP/IP pipe would be dropped. How frequent the re-connect takes place is visible in the nBrokenConnections metric.

**Comment by ddebrunner** [comment]
@markheger Could you get that extra information into the product documentation?

**Comment by markheger** [comment]
@ddebrunner Yes, I will add extra information into production documentation of the Export operator,

**Comment by ddebrunner** [comment]
Discussion complete.
