### ISSUE TITLE
Conversion between SPL and Python tuples enhancement request

### ISSUE THREAD

**Issue by jms90h5** [IBMStreams/streamsx.topology#651]
The documentation [here](http://ibmstreams.github.io/streamsx.topology/experimental/python/doc/spldoc/html/tk$com.ibm.streamsx.topology/ns$com.ibm.streamsx.topology.python$7.html) states that only primitive types are currently supported for the output port of python based operators.  Many of the python functions I would like to access from SPL in the form of an operator would return, among other things, an array (or list). Since lists of primitive types are already supported for the input port, it would seem logical to also support them on the output port.  Is there a plan for supporting them on output ports in the near future?

**Comment by ddebrunner** [comment]
The latest code in master supports lists, sets and maps, including nested collection types such as `list<list<float64>>`

**Comment by jms90h5** [comment]
Great!  Thanks much.  Is it preferred to replace the topology toolkit in the Streams install location (4.2.0.1) or reference a separate copy in some other location (e.g. /home/streamsadmin/toolkits)?

**Comment by ddebrunner** [comment]
I would put the newer version in a separate location.

**Comment by jms90h5** [comment]
Understood. Will do.
