### ISSUE TITLE
How do I trigger python package dependency inclusion?

### ISSUE THREAD

**Issue by jms90h5** [IBMStreams/streamsx.topology#652]
I have a small python test function decorated to be an SPL operator.  Although it works fine when run standalone with Anaconda's python3 and processes cleanly with spl-python-extract.py, the operator fails in the Streams runtime with the PE console for the operator showing the following error:

Traceback (most recent call last):
  File "/home/streamsadmin/.streams/var/Streams.sab_ALZ-StreamsDomain-StreamsInstance/d0dcbaa4-5d73-4da2-9ce6-8d7e72da5538/d51a04b1f39fe88c3fffdc0fe9148dfa0b40791c74acce720a81685b/BuildConfig/toolkits/KarhunenLoeve/opt/python/streams/KarhunenLoeve.py", line 9, in <module>
    import numpy as np
ImportError: No module named 'numpy'
terminate called without an active exception
02 Jan 2017 17:31:59.816 =====================  SIGNAL SIGABRT     ============================

I realize that numpy is an extension package that relies on native libraries (see bug #363) but in this case all the libraries are installed and it seems that the numpy package itself is not getting included in the Streams application bundle.  Is there some step I missed to trigger the inclusion of packages that are installed along with Anaconda?

**Comment by ddebrunner** [comment]
Are you using Anaconda with the distributed Streams instance?

**Comment by ddebrunner** [comment]
Just to add any packages that are in the toolkit's `opt/python/packages` are added to PYTHONPATH when executing the operator. This is the toolkit where the operator is defined.

See: http://ibmstreams.github.io/streamsx.topology/doc/spldoc/html/tk$com.ibm.streamsx.topology/ns$com.ibm.streamsx.topology.python$11.html

You can probably install packages into that directory using the `--root` option of `pip install`.

**Comment by jms90h5** [comment]
Hi Dan,

Yes, I'm using Anaconda (3) installed into a 4.2 QSE vm.  Since numpy is already part of that distribution I didn't think I needed to do any additional _installation_ to use it in a python SPL operator. But perhaps I'm missing some configuration step.

Currently PYTHONPATH is set to this:
   PYTHONPATH=/home/streamsadmin/toolkits/com.ibm.streamsx.topology/opt/python/packages

What do I need to do to tell Streams where to find the default Anaconda packages?

**Comment by ddebrunner** [comment]
Did you set PYTHONHOME as an instance application environment variable to the location of Anaconda.

Either using the console or this command (replace the path with wherever you installed it):

```
streamtool setproperty -i myInstance --application-ev PYTHONHOME=/home/streamsadmin/anaconda3
```

There should be no other config step, but are you seeing an error at compile time or runtime?

**Comment by jms90h5** [comment]
Ahh.  That was what I missed.  

Thanks much
