### ISSUE TITLE
How to pass System parameter for Java operator?

### ISSUE THREAD

**Issue by afilichkin** [IBMStreams/streamsx.topology#660]
I need pass system parameter durring submitting streams jobs. Can I somehow use `-Dproperty=value` ?

**Comment by ddebrunner** [comment]
Is this the same as this Q&A?

https://developer.ibm.com/answers/questions/337279/how-to-pass-system-property-to-java-streams-operat.html#answer-337648

**Comment by ddebrunner** [comment]
assume it was the same issue.
