### ISSUE TITLE
Modify Distributed context to build on a remote build service if a local streams install is not present.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#665]
Currently, in order to choose the correct context, a user must know whether he/she is submitting from a system that contains a Streams install.

What should happen is the following -- the topology toolkit will automatically detect whether there is a Streams install and perform the correct corresponding action:

**If the system has a Streams install:**

Context | Action
------------ | -------------
Distributed | The application is compiled locally and submitted to an instance via streamtool

**If the system does *not* have a Streams install:**

Context | Action
------------ | -------------
Distributed | The application is compiled on a remote build farm and submitted to a non BlueMix instance

**Comment by markheger** [comment]
resolved with environment variables for Distributed context that can be used for local Streams and Streams in Cloud Pak for Data
