### ISSUE TITLE
Submission to analytics service for remote build needs to check status.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#671]
The existing submission of a sab to the analytics service checked to see if the status was up, the submit of a build archive needs to perform the same check before attempting any submission.

**Comment by ddebrunner** [comment]
Should be able to share the code between remote and non-remote contexts.

**Comment by ddebrunner** [comment]
This is complete now?

**Comment by ddebrunner** [comment]
Is this complete?????

**Comment by wmarshall484** [comment]
Yes, this is complete.
