### ISSUE TITLE
Status/Progress message for remote build & submit need to match existing messages.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#676]
The original messages for submitting a bundle to the Analytic Service look like this:

```
INFO: Streaming Analytics Service: Submitting bundle : hello_world.hello_world.sab to debrunne-streams2
```

The messages for the remote build need to look similar, namely:

* Use `Streaming Analytics Service` not `remote build` or `remote instance`
* Provide information on what is being submitted (e.g. app name etc.)
* use similar format

**Comment by ddebrunner** [comment]
We should probably change all the messages to include the service name, like:

Streaming Analytics Service (_service-name_):

**Comment by ddebrunner** [comment]
My fault, we should try to be consistent with:

`Streaming Analytics Service (service-name):`

**Comment by ddebrunner** [comment]
`Streaming Analytics Service("debrunne-streams2"):`

needs to change to match the previous comment.

**Comment by wmarshall484** [comment]
Can this be closed?
