### ISSUE TITLE
Enable relative paths for files through StreamsContext

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.topology#68]
Currently, it appears that `FileStreams.textFileReader` cannot accept relative paths. I think this is because it is actually run from the `/tmp` directory, and we have not set the `--data-directory` for the underlying Streams application. The issue, then is not specific to `textFileReader`, but for all applications that might use a data directory.

I think an appropriate solution is to provide an interface through `StreamsContext` for programmers to set the data directory. We may also want to provide a similar thing for the output directory as well.

If I am wrong, and it is possible to use relative paths, then please close this issue.

**Comment by ddebrunner** [comment]
Issue #60 added support for the data directory, though it should be documented where relative paths are relative to.
