### ISSUE TITLE
Simplify and make Python logging consistent.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#682]
Number of changes:

- Use a single logger `streamsx.topology` for simplicity & document its use
- Don't have a logger parameter on submit, loggers are not typically specific to a function execution (and not in this case as implemented). The api to change the logging level is to change the level on the `streamsx.topology` logger.
- Don't default any logger to DEBUG
- Pass the log level onto the Java code so changing the log level in Python to see more info is passed through to Java to see more info from submission, compilation etc.
- Resolve that loggers all go to system err.

**Comment by wmarshall484** [comment]
Regarding these comments:

> Use a single logger `streamsx.topology` for simplicity & document its use

Should we have a single logger? Other projects seem to create a hierarchy of loggers based on the module name. In this case we would have the `streamsx.topology.context` and `streamsx.topology.topology` loggers.

> Don't have a logger parameter on submit, loggers are not typically specific to a function execution (and not in this case as implemented). The api to change the logging level is to change the level on the `streamsx.topology` logger.

Done.

> Don't default any logger to DEBUG

Done.

> Pass the log level onto the Java code so changing the log level in Python to see more info is passed through to Java to see more info from submission, compilation etc.

TODO

> Resolve that loggers all go to system err.

Including logging.INFO and logging.DEBUG? Also, I believe the user can change this in a custom initialization, but I'd need to check.

**Comment by markheger** [comment]
close since lack of demand
