### ISSUE TITLE
support cancel of distributed job?

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#69]
It would be very convenient if the API exposed a mechanism to cancel a submitted job.
That would save the user's code from having to code to the Domain mgmt API (a non-negligible hurdle) or streamtool invocations to do it.

DistributedTester's returned Future has different semantics than Distributed.  It blocks until the job has been cancelled. and cancel() will cancel the job.  

Those semantics won't work for Distributed... where the jobId needs to be made available immediately.

Maybe consider something like Future<JobHandle> sc.submit().  And JobHandle would have getJobId() and cancel().  Cancel would cancel the job.  If the job didn't exist it would need to fail in a meaningful/useful way for clients - e.g., minimally the exception would need to say "job id ... not found in instance ....".  Additionally, could consider a JobNotFoundException or such.

**Comment by markheger** [comment]
even Java API has `cancelJob` in `com.ibm.streamsx.rest.Job`
python API supports it, too
