### ISSUE TITLE
Merge common REST code -- for example, avoid maintaining two copies of PostJob.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.topology#701]

**Comment by wmarshall484** [comment]
`AnalyticsServiceStreamsContext` contains many of the same methods as `BuildServiceRemoteRESTWrapper`. This was caused by one set of methods taking a `JSONObject` as a parameter, and the other set taking a `JsonObject`.

The merged copies should simply use `JsonObject`, and methods should be exposed to convert a `JSONObject` to a `JsonObject`.

**Comment by markheger** [comment]
seems resolved
