### ISSUE TITLE
Can I include files in the application bundle?

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#73]
I didn't see this in the documentation.

Is there a way to include files and directories in the application bundle?  If so, how do I create a path to a file that is in the bundle?  Is there something like `getApplicationDir()`?

**Comment by ddebrunner** [comment]
From Java code the natural way would be to include the files in your jar file or classes directory containing the code that builds the topology or include an additional jar/classes directory using Topology.addJarDependency() or Topology.addClassDependency().

Then you access them as resources in Java from the class loader:
https://docs.oracle.com/javase/tutorial/deployment/webstart/retrievingResources.html

**Comment by hildrum** [comment]
Thank you.   

For anyone else trying to include a file in the jar to be accessed at runtime:
* Put the files you want to access in the `bin` directory if using StreamsStudio.  The default is not to include the source directories in the jar, so putting files under `src` doesn't get them included.
* If you need to use the path in a static context (as I did), you can do `ProcessLines.class.getClassLoader()` (where `ProcessLines` is the name of the class).  The example linked to above uses `this`, but you can't do that in a static context.

**Comment by ddebrunner** [comment]
Putting source files under bin might be risky, I'm not sure if a clean project will delete the contents of bin. Eclipse might have a way to copy resources from source directories to bin.

**Comment by dlaboss** [comment]
fwiw, Topology.addFileDependency() is being added as part of the Pull #103 / Issue #98 work.  Don't know if it may be applicable to this use case.

**Comment by ddebrunner** [comment]
Files can be added as Java resources or using addFileDependency() for SPL operators.
