### ISSUE TITLE
python version of SPL appTrc() trace routine

### ISSUE THREAD

**Issue by ibmkendrick** [IBMStreams/streamsx.topology#747]
Is there a python equivalent version of appTrc() routine?  (i.e. respects the PE's application trace level settings)

**Comment by ddebrunner** [comment]
Not yet.

**Comment by ddebrunner** [comment]
This will be supported through the use of Python `logging` module, similar to how the Java support uses standard Java loggers.

**Application Trace**: Any message sent through the root logger (`logging.getLogger()`) or a child with `propagate` evaluating to `True` will result in a message to the Streams application trace.

**Application Log**: Any message sent through the logger (`logging.getLogger('com.ibm.streams.log')`) or a child with `propagate` evaluating to `True` will result in a message to the Streams application log. The default handler for `com.ibm.streams.log` logger will only accept messages at a level >= 30 (INFO). All other messages are discarded.

When the PE starts up the level of root logger is set to the trace level and `com.ibm.streams.log` logger set to the log level.

**Comment by ddebrunner** [comment]
This has been added.

**Comment by ddebrunner** [comment]
http://ibmstreams.github.io/streamsx.topology/doc/releases/latest/pythondoc/streamsx.ec.html#streams-app-log-trc
