### ISSUE TITLE
Optimise cats cradle.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#753]
Adjacent parallel regions where the second region is hashed are not optimized due to the insertion of the Hash adder. 

This was done but was intentionally removed to allow cleanup related to optimizing topologies for 4.2 by using job config overlays to force channel isolation, rather than insertion of isolation markers (which didn't force isolation on 4.2 due to a change in parallel region fusing in 4.2).

#752 should be fixed first.

**Comment by ddebrunner** [comment]
Deferring from the 1.5/1.6 release.

**Comment by mrshenli** [comment]
@ddebrunner Does the conflict causing the removal of [`relocateHashAdder`](https://github.com/ddebrunner/streamsx.topology/blob/62e053adb7218def57fa74e20da82ea38f6c881a/java/src/com/ibm/streamsx/topology/generator/spl/Preprocessor.java#L141) still exist? What is the conflict?

**Comment by mrshenli** [comment]
Hi @ddebrunner 

I want to make sure that I understand the code correctly. I have the following question and statements.

Question:
1. Why downstream `HashAdder`s of the same `endParallel()` need to use the same routing type? [[old code]](https://github.com/ddebrunner/streamsx.topology/blob/62e053adb7218def57fa74e20da82ea38f6c881a/java/src/com/ibm/streamsx/topology/generator/spl/Preprocessor.java#L172)

Are the following statements true?

2. In the current implementation, no `HashAdder` is inserted in front of `endParallel()`, so there is no need to check whether there is a `HashAdder` located immediately before `endParallel()`. [[old code]](https://github.com/ddebrunner/streamsx.topology/blob/62e053adb7218def57fa74e20da82ea38f6c881a/java/src/com/ibm/streamsx/topology/generator/spl/Preprocessor.java#L213)

3. In the current implementation, it is always `HashAdder` -> `Parallel` -> `HashRemover`, instead of `HashAdder` -> `Parallel` -> `Isolate` -> `HashRemover` as checked in the [[old code]](https://github.com/ddebrunner/streamsx.topology/blob/62e053adb7218def57fa74e20da82ea38f6c881a/java/src/com/ibm/streamsx/topology/generator/spl/Preprocessor.java#L197).

4. The following is a valid case where one `endParallel()` is followed by two `parallel()` with different keyers. In this case, both `HashAdder`s should be moved to the front of `endParallel()`, creating two outputs of the same parallel region. Each of the output can connect to its own downstream `parallel` virtual marker.
  
  ```java
  TStream<X> x = someStream.endParallel();
  TStream<A> a = x.parallel( ()->3, keyerA);
  TStream<B> b= x.parallel( ()-> 4, keyerB);
  ```

5. In the [[old code]](https://github.com/ddebrunner/streamsx.topology/blob/62e053adb7218def57fa74e20da82ea38f6c881a/java/src/com/ibm/streamsx/topology/generator/spl/Preprocessor.java#L235-L249), it seems one `HashAdder` can have multiple parents. But, in the current implementation, each `HashAdder` is guaranteed to have only one parent.

**Comment by ddebrunner** [comment]
- A1 : Maybe because previously a parallel region composite could only have a single output port. Now multiple output ports are supported (I think).
- A2 : Correct.
- A3 : Correct.
- A4: Correct
- A5 : Not sure, I can have a `union` feeding into a `parallel` which logically is multiple upstream operators.

**Comment by ddebrunner** [comment]
This can be tackled incrementally if it makes it easier, rather than trying to handle every possible case with the first approach.

E.g. initially handle the common case of a single upstream & downstream op

**Comment by mrshenli** [comment]
In the following case, moving `HashAdder_0` to the front of `$Unparellel_0` would require us to add a `HashRemover` after `$Parallel_1$` and another `HashAdder_1`  to the front of `$Unparellel_1$`. But it seems we do not have the keyer for `HashAdder_1`. Should I create a universal keyer for for `HashAdder_1`, e.g., use the `hashcode()` of the tuple object as the key?

`$Unparellel_0$` -> `HashAdder_0` -> `$Parallel$_0` -> `HashRemover`
`$Unparellel_0$` -> `$Parallel_1$`
`$Unparellel_1$` -> `$Parallel_1$`

**Comment by ddebrunner** [comment]
@mrshenli  Could you provide the Java or Python code for the situation you are trying to solve?

**Comment by mrshenli** [comment]
```java
  TStream<A> u1 = someStream.endParallel();
  TStream<A> u2 = someOtherStream.endParallel();
  TStream<A> p1 = u1.parallel( ()-> 3, keyerA);
  TStream<A> x = u1.union(u2);
  TStream<A> p2 = x.parallel( () -> 4)
```

I see. Though the application does not provide a keyer for `u2`, keyerA should work here, as `u1` and `u2` can be unioned together.

**Comment by ddebrunner** [comment]
Is such a situation likely, or is it sufficient to not perform the optimization in that case?

**Comment by mrshenli** [comment]
Maybe we can add a `PassThrough`  operator after `u1`, i.e., let `u1` have two downstream operators, a `HashAdder` and a `PassThrough`  (or directly use an `Unparellel` child).

**Comment by ddebrunner** [comment]
@mrshenli yeah, and it might end up instead of marking operator invocations as `hashAdder` we use a more generic property `moveIntoUpstreamParallelRegion` ?

**Comment by mrshenli** [comment]
@ddebrunner yes, `moveIntoUpstreamParallelRegion` would be more generic. My concern is that, as we discussed above, it could require more than moving itself into the upstream parallel region. For example, creating a sibling `PassThrough` operator is not indicated in the name. 

What are other operators that could be marked as `moveIntoUpstreamParallelRegion `?

**Comment by ddebrunner** [comment]
@mrshenli  I'm not sure scenario 2 can exist as SPL doesn't allow multiple streams feed a composite output port so at least in Python a pass through operator is inserted to "physically" union the streams so it turns into scenario 1. It's possible that Java takes a different approach now that composites with multiple output ports are supported. I'd have to see. (also see #1750)

**Comment by ddebrunner** [comment]
@mrshenli So for scenario 3 the added pass through is:

- Only needed if there is more than 1 downstream operator that is not parallel partitioned.
- Already occurs though may need tweaking.

**Comment by mrshenli** [comment]
I am not sure whether we indeed need that `PassThrough` operator. Can we do something like the following?

```
 HashAdder1 -> $Unparallel$ -> $Parallel$
     ^
     |                         
   input -> $Unparallel$ -> map
```

**Comment by ddebrunner** [comment]
yes - but only when there is one non-udp partitioned operator downstream of the input

**Comment by ddebrunner** [comment]
Seems like the simple approach for a union before a hash adder is to push a hash adder before the union.

**Comment by mrshenli** [comment]
would that still leave `HashAdder` after `$Unparallel`?

**Comment by ddebrunner** [comment]
Well, obviously it's relocating them, so the single hash adder would be relocated to multiple upstreams.

**Comment by mrshenli** [comment]
Hi @ddebrunner 

Below is what I plan to do for scenario 3, does it make sense to you?

1. find all distinct `HashAdder`'s parent `$Unparallel$` operators, and perform the following for each parent
2. triage parent `$Unparallel$`'s children into `HashAdder`s and others.
3. for each `HashAdder` child add an `$UnparellelCopy$` between the `HashAdder` and `$Parallel$`, i.e.,
    ```
    input -> $Unparallel$ -> HashAdder -> $Parallel$
    becomes
    input -> $Unparallel$ -> HashAdder -> $UnparallelCopy$ -> $Parallel$
    ```
4. move every `HashAdder` to be it's parent `$Unparellel$`'s sibling, i.e.
    ```
    input -> $Unparallel$ -> HashAdder -> $UnparallelCopy$ -> $Parallel$
    becomes
    input -> HashAdder -> $UnparallelCopy$ -> $Parallel$
          \-> $Unparallel$
   ```
5. If there is no other children expect `HashAdder`s, remove the original `$Unparallel$`
6. If there is only one other child besides `HashAdder`s, nothing needs to be changed
7. If there are multiple other children besides `HashAdder`s, insert a `PassThrough` operator between the original `$Unparallel$` and its parent.

**Comment by ddebrunner** [comment]
@mrshenli Quick question before I try and follow it, is this a different algorithm to the one you proposed earlier for scenario 3? If so , what's the key difference & why?

**Comment by mrshenli** [comment]
I think it will achieve the same result as described in Scenario 3, but the implementation (B) is a little simpler from what we discussed in Slack (A). 

Implementation A: In the Slack discussion, we discussed to do this in two passes. The first pass will add `PassThrough` operators after `$Unparallel$` operators, and mark both `PassThrough` and `HashAdder` as `moveIntoUpstreamParallelRegion `. The second pass will move `HashAdder` and `PassThrough` operators into the upstream parallel region.

Implementation B: The implementation proposal described in the previous comment achieves the same result in one pass but with the following benefits:
1. It avoids creating a new property `moveIntoUpstreamParallelRegion `.
2. The graph structure manipulation becomes simpler, especially for `PassThrough`, as we either need to insert it in the front of `$Unparallel$` or simply do nothing.

**Comment by ddebrunner** [comment]
Not sure about step 3, leaving the graph in an unnatural state, it seems you could go directly to the result of step 4.

Then is a `PassThrough` even needed? If I had a parallel region output being consumed today by multiple children (without any parallel regions) it works today (I assume) without a pass through.

So you can actually remove steps 5-7.

**Comment by mrshenli** [comment]
> Then is a PassThrough even needed? If I had a parallel region output being consumed today by multiple children (without any parallel regions) it works today (I assume) without a pass through.

`PassThrough` is necessary here because in step 1 we find distinct parents of all `HashAdder`s. So each parent processed in the following steps has at least one parallel child.

**Comment by mrshenli** [comment]
> Not sure about step 3, leaving the graph in an unnatural state, it seems you could go directly to the result of step 4.

Could you please elaborate?

It seems we need to perform two actions for each `HashAdder`, and either action will leave the graph in  some unnatural state. I am not sure if we can avoid the intermediate unnatural state.
a. make a copy of its original `$Unparallel$` parent, and insert the copy after `HashAdder`
b. move `HashAdder` to become a sibling of its original parent `$Unparallel$`

**Comment by mrshenli** [comment]
@ddebrunner 

Just to make sure I understand it correctly:

1. The `PassThrough` here should be an [operator](https://github.com/IBMStreams/streamsx.topology/blob/master/java/src/com/ibm/streamsx/topology/builder/GraphBuilder.java#L224) instead of a [marker](https://github.com/IBMStreams/streamsx.topology/blob/master/java/src/com/ibm/streamsx/topology/builder/GraphBuilder.java#L204)

2. Is there any convenient way to create a `PassThrough` as a `JsonObject`?

**Comment by ddebrunner** [comment]
> It seems we need to perform two actions for each HashAdder, and making either change first will leave the graph in some unnatural state. 

Maybe I'm missing something, but for the Hash adder you are moving the original state is:
 ```
I -> EndParallel -> HashAdder -> Parallel -> HashRemover
________________|-> other connections
```

You need to transform that to:
 ```

I -> EndParallel -> other connections
_|-> HashAdder  -> EndParallel -> Parallel -> HashRemover
```
(underscores only used to line up items)

Seems like that's a basic single step.

**Comment by ddebrunner** [comment]
Effectively the 1-1 case could also use the same approach to simplify the code. For each hash adder than needs to be moved:

1. Disconnect hash adder
1. Connect hash adder to input
1. add new end parallel between hash adder and its parallel start.
