### ISSUE TITLE
Symbolic link to python modules not copied into build archive

### ISSUE THREAD

**Issue by ibmkendrick** [IBMStreams/streamsx.topology#756]
[symlink_to_module.zip](https://github.com/IBMStreams/streamsx.topology/files/777337/symlink_to_module.zip)
contains python code importing a python module, where the module's folder is a symbolic link.

When a build archive is created, the toolkit is expected to contain the python module, but it doesn't.

**Comment by markheger** [comment]
Current code copies the name of the symlink as target directory, but misses to copy the content of the real source directory

in Forever.json:
`{"config":{"includes":[{"source":"/home/streamsadmin/hostdir/tst/symlink_to_module/custom","target":"opt/python/packages"}`

The real source directory is custom_real and this needs to used for the copy operation.

Current code runs then into the following error since the module forever.py is missing.
```
02 Apr 2020 06:31:17.823+0000 [5284] ERROR #splapplog,J[0],P[0],forever,python M[splpy_general.h:importModule:363]  - CDIST0305E: Fatal error: missing module: custom.forever.
ModuleNotFoundError: No module named 'custom'
02 Apr 2020 06:31:17.840+0000 [5284] ERROR #splapplog,J[0],P[0],forever,spl_pe M[PEImpl.cpp:logTerminatingException:2183]  - CDISR5033E: An exception occurred during the execution of the forever operator. Processing element number 0 is terminating.
02 Apr 2020 06:31:17.840+0000 [5284] ERROR #splapptrc,J[0],P[0],forever,spl_operator M[PEImpl.cpp:handleOperatorFailure:661]  - CDISR5030E: An exception occurred during the execution of the forever operator. The exception is: Unknown Python error
02 Apr 2020 06:31:17.841+0000 [5284] ERROR #splapptrc,J[0],P[0],forever,spl_pe M[PEImpl.cpp:process:1478]  - CDISR5079E: An exception occurred during the processing of the processing element. The error is: Unknown Python error.
02 Apr 2020 06:31:17.841+0000 [5284] ERROR #splapptrc,J[0],P[0],forever,spl_operator M[PEImpl.cpp:process:1516]  - CDISR5053E: Runtime failures occurred in the following operators: forever.
```

**Comment by markheger** [comment]
method `copyIncludes` in `java/src/com/ibm/streamsx/topology/internal/context/remote/ToolkitRemoteContext.java` needs to be modified.
* check if source file/dir is a symbolic link
* copy real source to target with origin name
