### ISSUE TITLE
Is there any support for tumbling windows?

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.topology#76]
Based on the documentation for `TStream.last`, I believe that it logically represents a sliding window. From the documentation (http://ibmstreams.github.io/streamsx.topology/doc/javadoc/com/ibm/streamsx/topology/TWindow.html):

> For example `s.last(10)` declares a window that at any time contains the last 
> ten tuples seen on stream s

I interpret that to mean a sliding window of size 10.

Is there any current support for tumbling windows, or is there any planned support for tumbling windows? If we want to support tumbling windows, the best method name I can think of is `TStream.accumulate`. For sliding windows, it's easy to describe as "it's the _last_ 10 tuples", which implies that at any given point in time, we may see the same tuples again. For tumbling windows, it could be described as "we wait until we _accumulate_ 10 tuples", which I think implies we don't see those 10 tuples again.

**Comment by ddebrunner** [comment]
I've been playing with an approach, but unsure what the use case is, so can you share what you are trying to do.

**Comment by scotts** [comment]
I'm working on implementing LogWatch. The particular piece of logic is here: https://github.com/scotts/streamsx.demo.logwatch/blob/master/language/com.ibm.streamsx.demo.logwatch.language/LogWatch.spl#L26

The aggregation semantics I'm trying to mimic is, in SPL:

    stream<FailureRange> Range = Aggregate(Failure) {
        window Failure: tumbling, count($attempts), partitioned;
        param partitionBy: rhost;
        output Range: max = Max(time), min = Min(time), user = Max(user);
    }

That is, I want to trigger my aggregation every time I see `$attempts` number of tuples, partitioned by `rhost`.

A higher level description is that each tuple represents a failed login attempt on the system. I want to partition these failed login attempts by the remote host because I'm trying to identify remote hosts that are trying to break into this system. I have a threshold, `$attempts`, which I use to say when a particular number of failed login attempts is too many, and it now becomes suspicious. I use a tumbling window because I only want one result for every `$attempts` number of failed logins.

I can implement this logic using the Java API, I just can't use windows right now to do it. I'm currently working on implementing my own ad-hoc windows doing this:

    public class SuspectFinder {
        public static TStream<Suspect> find(TStream<Failure> failures, int attempts, double seconds) {
            return failures.transform(new Function<Failure, Suspect>() {
                // ad-hoc implementation of a tumbling window
                private transient List<Failure> window = new ArrayList<Failure>();

                @Override
                public Suspect apply(Failure tuple) {
                    window.add(tuple);
                    if (window.size() == attempts) {
                        // aggregation logic goes here
                        return new Suspect(/* use result of aggregation logic */);
                        window.clear();
                    }
                    else {
                        return null;
                    }
                }
            }, Suspect.class);
        }
    }

So a work-around is possible.

**Comment by scotts** [comment]
(Note my code has an obvious bug where I clear the window *after* returning. Assume that the window is cleared before returning.)

**Comment by ddebrunner** [comment]
Thanks!
As implemented that would mean any time a host reached N failed attempts it would become suspicious, regardless of how long it took to achieve that many failed attempts, i..e N attempts over a year would still be treated as suspicious.  In a real application is that what would be required, or it is really N attempts within Y seconds, which goes back to a sliding window, or maybe partition eviction using SPL?

I think there probably is a need to tumbling style, really it's non-overlapping processing of tuples on the stream, especially for maintaining counts/totals etc. I'm experimenting with a trending hashtag  type application, where each tuple needs to be accounted for once, but the window of trending is a sliding window. One approach would be to count hashtags in a tumbling window (every 50ms say) and then put the resulting counts into the sliding window, this reduces memory & cpu from putting all tweets in a sliding window and then counting the tags within them. But I also wonder if a better approach would just be incremental aggregating on the sliding window, so that the developer is not forced to do multiple steps because of implementation details.

**Comment by scotts** [comment]
I left out the rest of the SPL logic, which does the time-based filtering, for N attempts in Y seconds:

    composite SuspectFind(input Failure; output Diff) {
        param
            expression<uint32> $attempts;
            expression<float64> $seconds;

        type FailureRange = timestamp max, timestamp min, rstring rhost, rstring user;
        graph
            stream<FailureRange> Range = Aggregate(Failure) {
                window Failure: tumbling, count($attempts), partitioned;
                param partitionBy: rhost;
                output Range: max = Max(time), min = Min(time), user = Max(user);
            }

            stream<FailureRange> Cutoff = Filter(Range) {
                param filter: max - min < (timestamp)$seconds;
            }

            stream<Suspect> Diff = Functor(Cutoff) {
                output Diff: diff = max - min, last = max, attempts = $attempts;
            }
    }

If the `max` and `min` times are not within a particular `$seconds` threshold, then we do not consider it suspicious. With reasonable thresholds, that means that a few failed logins over the course of a year will *not* be treated as suspicious.

Although I think you're right that this concept is better modeled with sliding windows, as that means every time we receive a new failure, we look back over the last N-1 failures. That is more sensible than starting fresh every N failures. I was trying to avoid too many notifications, but I think missing them because the logical time range happened to span window tumbles is worse.

I think there are valid uses of tumbling windows, but it appears my case may not be it.
