### ISSUE TITLE
Translation autorun.sh test issues.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#773]
I tried to run the new translation `autorun.sh` from pr #761 and it failed for me since I was running 4.1.

Test fails with 4.1/4.0.1 since there is no standalone binary built. May not need to fix this but at least this should be documented in the README.

Test runs the application `output/bin/standalone` but does not check for the return code being zero.

**Comment by joergboe** [comment]
I know this script is not very smart.
I will add as version check.
But in line 77 the execution must fail - this is an test for an error
In line 95 the execution must not fail

**Comment by ddebrunner** [comment]
So shouldn't the test test for those conditions (return code being zero or non-zero)?

I'd like to include this as part of the automated testing so that we don't get surprises at the end of a release when translation comes to run it. We would just run and and test for the return code being zero.

**Comment by joergboe** [comment]
Issue is resolved with PR #793 and #895
