### ISSUE TITLE
Standalone submission returns bundleRoot for non-existent file.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#775]
RET below is the return from a standalone submission.
```
INFO: Standalone application completed: return code=0
RET {'bundleRoot': '/home/streamsadmin/pyspl/Files.Files.sab', 'return_code': 0}
```

Two issues:

- `bundleRoot` doesn't look like the 'root' of a bundle, actually I have no idea what a bundle root is. It seems it would simply be `bundle`.
- The file does not exist since `topology.keepArtifacts` was not set, so I'm not sure of the value of returning a path to a non-existent file. Maybe only provide that path if `topology.keepArtifacts` was set to `True`?

**Comment by wmarshall484** [comment]
@ddebrunner, That should have been `bundlePath`, not root.

Good point, it should only be returned if the file exists. In that case, the returned JSON would be empty except for the `return_code`.
