### ISSUE TITLE
GVT - Add tests for use of unicode data.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#794]
- Job name
- View name (see #713 )
- Stream names
- Stream data (strings) (mostly handled by Python since it naturally supports Unicode data) - some testing exists for SPL Python operators.
- Decorated SPL operator names (which can only be ascii).

**Comment by ddebrunner** [comment]
App name/namespace tested in test2_names.py

**Comment by ddebrunner** [comment]
Decorated operator parameters will be covered by #801

**Comment by wmarshall484** [comment]
With regards to testing the unicode view names, the test needs to:
1. submit the job
2. retrieve and compare the unicode view name
3. cancel the job

In other words, after submission, some work needs to be done before cancellation. With the current test harness, a job is submitted like:
```python
tester.test(self.test_ctxtype, self.test_config)
```

which cancels the job upon completion, before the view name can be retrieved. A perhaps unnecessary solution would be to modify the test harness to support delayed cancellation of jobs. I think I have a workaround, though.

**Comment by ddebrunner** [comment]
The concept of "LocalConditions" might work, so in addition to conditions on streams, conditions could be added for locally visible items, maybe even a special category for conditions against the rest apis.

**Comment by ddebrunner** [comment]
Job name tested in test2_job_config.
