### ISSUE TITLE
Application exits in the middle of writing a file in standalone mode

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.topology#81]
My application is here: https://github.com/scotts/streamsx.demo.logwatch/tree/master/topology. It should be easy to pull, compile and run it to see if anyone else can reproduce my behavior.

I have a `Consumer` that [writes each tuple to a file] (https://github.com/scotts/streamsx.demo.logwatch/blob/master/topology/src/streamsx/demo/logwatch/topology/TextFileSink.java). However, when I run my application in standalone, it consistently seems to exit in the middle of writing a tuple. These are the final lines from my output file:

    diff=Wed Dec 31 19:00:18 EST 1969, last=Sun Feb 13 04:30:38 EST 2011, attempts=5, rhost=123.176.40.122, user=
    diff=Wed Dec 31 19:00:18 EST 1969, last=Sun Feb 13 04:30:43 EST 2011, attempts=5, rhost=123.176.40.122, user=
    diff=Wed Dec 31 19:00:18 EST 1969, last=Sun Feb

It looks like it was in the middle of writing that tuple - it even looks to be in the middle of writing the value `last`. What's curious is that this does not appear to be a race condition, as the same amount of data is written every time, and it seemingly exits in the middle, in the same place, every time.

I am submitting my topology with:

    StreamsContextFactory.getStreamsContext(contextType).submit(suspects.topology()).get();

Which is at https://github.com/scotts/streamsx.demo.logwatch/blob/master/topology/src/streamsx/demo/logwatch/topology/LogWatch.java#L23

When I run, I see no exceptions or any other indication that there was a problem with the execution. I am unable to tell if this is a problem with the logic of my application, or if this is a bug in the library.

**Comment by scotts** [comment]
@hildrum pointed out that flushing the output may fix the problem, and it does. That means the problem was that the application was exiting while the output buffer was not empty.

The problem with this is that flushing on every tuple is very slow. (It increased my runs from a few seconds to almost 45 seconds.) This means that `Consumers` may need some concept of shutdown. This is likely happening because I am not closing the file - but I can't, because the file is owned by the `Consumer`, and the `Consumer` does not know when the topology is finished.

This is the flip side of the initialization issue with `Consumer`s. The difference is that for now, I can use the initialization-flag pattern to get around it. But I'm not aware of a workaround for shutdown.

**Comment by ddebrunner** [comment]
I have considered adding support for initialization and shutdown through interfaces, thus if your Consumer implementation also implemented Initializable (yet to be defined) or java.ioClosable (standard Java interface) then we would call those at the relevant times.

I don't want to add extra methods to Consumer as it then stops Java 8 lambda functions from being used, and it deviates from the Java 8 consumer that at some point Consumer will be based upon.

**Comment by scotts** [comment]
I think that's reasonable, as it will give users a well documented option.

But I'm starting to wonder if our `Consumer`s are just different from the Java 8 ones. I'm sympathetic to wanting to keep our `Consumer` the same as what is in Java 8. But if in practice, most of the ones we and our users implement also implement `Initializable` and `ioClosable`, then that tells me they are actually different things. I think that for us, most `Consumer` objects will be for interacting with an external resource of some kind, which implies some need to initialize and close it.

Even if we end up there, though, I think it's reasonable to first use separate interfaces.

**Comment by ddebrunner** [comment]
Fixed in pull request #86 

Note that your application might perform better if you use a BufferedPrintWriter
