### ISSUE TITLE
Change Java Application API name to "Java Topology API"?

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.topology#82]
The name we have adopted for this project is "Java Application API". I assume this is meant to differentiate it from the "Java Operator API". However, that means our name as the odd redundancy, "Java Application Application Programming Interface".

As an alternative, I like "Java Topology API", as it is the library for creating Streams topologies entirely in Java. It also mirrors the library name.

**Comment by hildrum** [comment]
I agree with this.  I think "Java Topology API" is more descriptive than "Java Application API"

**Comment by ddebrunner** [comment]
To be clear the project is streamsx.topology, and will support more than Java.

The Java API could be changed to Java Topology API.

**Comment by wmarshall484** [comment]
I agree. "streamsx.topology", "com.ibm.streamsx.topology.jar", and the API itself make references to the term "topology". I think "Java Topology API" is a more consistent name.

**Comment by chanskw** [comment]
There was a reason why we called this Java Application API, but it was too far back and I cannot remember.

Please note that this name change affects more than just this project.  We have to update all our existing documentation and marketing material.  I am not sure we have the cycles to do this yet.

Can we find a better timing for this?

**Comment by scotts** [comment]
I made this suggestion knowing that we are actively promoting it in several places, but names are the sorts of things that are never easy to change, and only get harder with time.

**Comment by ddebrunner** [comment]
I'll make the claim that the name is not redundant, it's an application programming interface to build streaming applications, cf. YACC https://en.wikipedia.org/wiki/Yacc

**Comment by scotts** [comment]
I think the name actually is redundant. YACC stands for "Yet Another Compiler Compiler". That is, it is a compiler that generates code for a different compiler - in other words, a compiler generator. Each "compiler" in the name is for a different entity; there's recursion in compilers.

In "Java Application Application Programming Interface", there is no recursion. Both instances of "Application" refer to the same entity: the application the programmer is developing. Our current name is more similar to the common construct of "ATM machine".

**Comment by chanskw** [comment]
I have thought about this and I think I am going to have to cast a -1 vote on name change.

Here are my reasons for a -1 vote:

* I do not think the name Java Application API is confusing and do not think people will be troubled by the "redundancy".  
* For a complete newbie, the Java Application API is actually clearer than a Java Topology API.  I have asked other people about the name change at the lab in Toronto.  In general, people understands better what Application APIs are supposed to do... vs people question what a topology is for a new user.
* Making this name change generates work on documentation and marketing material change.  Given that the name does not seem to confuse people, I am not sure this work is necessary.  If the name is truly confusing, then I agree that we should do this work.  But I do not think this is the case.
* We have been referring to the name Java Application API for a while now, and people already know this API with this name.  Renaming this will actually cause more confusing as people question why we have "removed" the Java Application APIs and started introducing yet another set of APIs.

I do not think this name change will clarify things.  But I think this will cause more confusion.
