### ISSUE TITLE
[Java Topology] Question on specifying JAR dependencies in topologies

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#833]
While working on the streamsx.health platform, I have been creating a number of Java Topology-based micro services. I am packaging the micro services into JAR files, which I then add to the class path of the application I am working on. This allows me to programmatically connect and launch the micro services I need. 

This approach has been working so far, however I recently stumbled upon a problem involving adding JAR dependencies and I am not sure of the best way to handle this. I will explain the problem below with a simple example. 

Suppose I have the following class, _MyTopology.class_, which depends on the **ThirdPartyLib.jar** file. 

```
public class MyTopology {

	private Topology topo;
	
	public MyTopology() {
		topo = new Topology("MyTopology");
		topo.addJarDependency("./ThirdPartyLib.jar"); // necessary JAR dependency	
		topo.strings("test1", "test2", "test3").modify(DoesSomethingCool::magic).print();
	}
	
	public void run(Type contextType, Map<String, Object> config) throws Exception {
		StreamsContextFactory.getStreamsContext(contextType).submit(topo).get();
	}
}

```
I package this class into a JAR called **MyTopologyLib.jar**. I then add **MyTopologyLib.jar** to the class path of a separate application where I want to submit the topology:

```
public class MainApplication {

	public static void main(String[] args) throws Exception {
		MyTopology t = new MyTopology();
		t.run(Type.EMBEDDED, new HashMap<String, Object>());
	}

}
```

Attempting to run results in the following exception: 

```
Exception in thread "main" java.lang.IllegalArgumentException: File not found. Invalid third party dependency location:/home/streamsadmin/workspace/health/SeperateProject/./ThirdPartyLib.jar
	at com.ibm.streamsx.topology.internal.core.DependencyResolver.addJarDependency(DependencyResolver.java:93)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addJarDependency(JavaFunctional.java:133)
	at com.ibm.streamsx.topology.Topology.addJarDependency(Topology.java:552)
	at topo.test.MyTopology.<init>(MyTopology.java:19)
	at MainApplication.main(SeparateApplication.java:10)
```

The reason for the exception is obvious: the call to _addJarDependency()_ in MyTopology hard-codes the path to the **ThirdPartyLib.jar** file. 

This brings me to my question: how do I create a JAR “library” containing topologies that have dependencies on third-party libs without hard-coding the paths to those dependencies into the topology? 

There are 2 solutions that I have tried that were successful, however I am not entirely happy with either. 

**Solution 1**: Specify the path to the JAR dependency from MainApplication. In this case, I added a function to MyTopology called _addJar(path_to_jar)_ that just wraps a call to _topo.addJarDependency()_. I then call _addJar()_ from MyApplication and pass in the path to **ThirdPartyLib.jar**. This is ugly as it means I need to know what the dependencies are for each of the topologies I am instantiating and then set them in the calling application. 

**Solution 2**: Package the classes from **ThirdPartyLib.jar** into the **MyTopology.jar** file. Then, call _addClassDependency(DoesSomethingCool.class)_ instead of _addJarDependency()_. This is better than Solution 1 and the process for packaging the ThirdPartyLib.jar classes into MyTopology.jar can be done with a couple of lines of code in a gradle script. The down side to this is that it can result in a very large JAR file if there are a lot of dependencies.

I am wondering if there is some obvious solution that I am missing. I look forward to hearing any thoughts.

**Comment by ddebrunner** [comment]
Does `addClassDependency` work for you, passing a class from **ThirdPartyLib.jar** ?

http://ibmstreams.github.io/streamsx.topology/doc/javadoc/com/ibm/streamsx/topology/Topology.html#addClassDependency-java.lang.Class-

**Comment by cancilla** [comment]
I originally read the description for `addClassDependency()`, but I was still unsure how I would use this. Let me see if I have this right:

 1. Call `addClassDependency(DoSomethingCool.class)` in `MyTopology` 
 2. Add both **ThirdPartyLib.jar** _and_ **MyTopologyLib.jar** to the classpath for `MainApplication`
 3. When I run `MainApplication`, the call to `addClassDependency()` will:
    a) look for **DoSomethingCool.class** on `MainApplication`'s classpath
    b) generate a JAR containing **DoSomethingCool.class** and all of it's siblings & cousins
    c) add the generated JAR to the topology runtime classpath

Does I have that correct?

**Comment by ddebrunner** [comment]
No. Second sentence of the description says:

>If the .class file is contained in a jar file, the jar file is also included in the application's runtime.

So steps 3b, 3c do not happen, instead the jar file containing DoSomethingCool.class (ThirdPartyLib.jar) will be added into the bundle.

**Comment by ddebrunner** [comment]
Step 2 has to exist, because your class depends on ThirdPartyLib.jar and declaring the app will load the class. The only change you could make there is to add a manifest class path in MyTopologyLib.jar to point to ThirdPartyLib.jar, but then they would be fixed in location wrt to each other.

**Comment by cancilla** [comment]
What happens with JARs that ThirdPartyLib.jar depends on, but I don't explicitly make use of in my topology? Will I need to call `addClassDependency()` for some class in each those JARs in order to get them added to the bundle?

**Comment by ddebrunner** [comment]
Yes.

**Comment by ddebrunner** [comment]
@cancilla please let us know if this works for you or not.

**Comment by cancilla** [comment]
Thanks @ddebrunner. `addClassDependency()` appears to be addressing my concerns.
