### ISSUE TITLE
Is it possible to create custom metric with Java topology?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#845]
I can't seem to be able to find documentation for this.  But is there anyway to create custom metric in Java topology?

**Comment by ddebrunner** [comment]
No at the moment.

**Comment by ddebrunner** [comment]
Now fixed.

http://ibmstreams.github.io/streamsx.topology/doc/releases/1.7/javadoc/com/ibm/streamsx/topology/function/FunctionContext.html#createCustomMetric-java.lang.String-java.lang.String-java.lang.String-java.util.function.LongSupplier-

**Comment by chanskw** [comment]
Cool thanks!
