### ISSUE TITLE
ant test.quick fails

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.topology#858]
When I try to start the tests with ant test.quick I got the error:
home/joergboe/git/streamsx.topology/test/java/build.xml:185: /home/joergboe/git/streamsx.topology/test/java/build.xml:188: Test com.ibm.streamsx.topology.test.perf.TuplePassingTest failed

What is wrong?

**Comment by joergboe** [comment]
This happens when I test with Streams Version 4.2.1

**Comment by ddebrunner** [comment]
I haven't tried that target for a while , I tend to use one of the main ones from DEVELOPMENT.md.

**Comment by joergboe** [comment]
The error happens also it the target test is used.
But it seems to be a problem specific to RHEL7
When I execute the test target in RHEL6 the test suite works fine

**Comment by ddebrunner** [comment]
What assert does it fail on?

**Comment by joergboe** [comment]
The compilation fails for a Standalone tests:
This issue was due to the implicit dependency to iot and daytime toolkit.
The 4.2.1 Build that I used was incomplete. Wit the actual 4.2.1.0 Build there is no such issue

**Comment by ddebrunner** [comment]
Thanks for confirming - I just also ran a complete set of tests with RH7 & 4.2.1 and passed.
