### ISSUE TITLE
Document Python streamsx.rest api.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#864]

**Comment by ibmkendrick** [comment]
I'll look at `StreamsConnection` and `StreamingAnalyticsConnection`

**Comment by ddebrunner** [comment]
I'll do `topology.context` and `spl.*`

**Comment by markheger** [comment]
documentation available: https://streamsxtopology.readthedocs.io/en/stable/streamsx.rest.html
