### ISSUE TITLE
Applying transform twice to the same stream can give unpredictable results 

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.topology#88]
The behavior when the same Stream is transform but a `Function` that modifies its input multiple times is not consistent, and I didn't see anything in the documentation warning not to do this.  [full code here](https://github.com/hildrum/streamsx.topology.samples/blob/master/TryItOut/src/testapp/TwoStreams.java)

````
TStream<Tracker> alice = startStream.transform(/* functor add alice to list */,Tracker.class);
TStream<Tracker> bob = startStream.transform(/* functor to add bob to list */,Tracker.class);
alice.println();
blob.println();
````
Gets:
````
0: [alice ]
0: [alice bob ]
````
or sometimes
````
0: [bob ]
0: [bob alice ]
````

**Comment by ddebrunner** [comment]
The package overview for com.ibm.streamsx.topology describes the pass by reference semantics.

**Comment by hildrum** [comment]
I see now where you say that, and that you even have a "Ensuring Consistent Behavior" section.
