### ISSUE TITLE
Support for unsigned integers

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#89]
I was trying to create an application that uses the KMeansClustering operator from the com.ibm.streams.timeseries toolkit. The operator has a required parameter that expects a 'uint32' value. However, the topology API does not support unsigned integers, thus preventing me from using this operator in a topology. This is a request to add support for unsigned integers.

**Comment by ddebrunner** [comment]
What happens if you use an Integer, does the SPL fail because it doesn't do automatic conversion to an unsigned value from a literal like 17?

A work around might be to create an SPL composite that just calls KMeansClustering  but uses an int32 parameter and performs the cast.

**Comment by dlaboss** [comment]
fixed in pull#182.   See cist.SPL.
