### ISSUE TITLE
1.5.13 EA4 spl-python-extract.py using deprecated inspect method?

### ISSUE THREAD

**Issue by jms90h5** [IBMStreams/streamsx.topology#891]
I just installed Streams 4.2.0.3 into an new VM and then added com.ibm.streamsx.topology 1.5.13 EA4 to a toolkits directory in ~streams admin along with a fresh install of the latest Anaconda (python 3 version).  When I try and run spl-python-extract.py I get this error:

Checking  /home/streamsadmin/workspace.acoustic4/Acoustic_Kafka/opt/python/streams/spl_functions.py for operators
Traceback (most recent call last):
  File "/home/streamsadmin/toolkits/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 414, in <module>
    (name, suffix, mode, mtype)  = inspect.getmoduleinfo(mf)
AttributeError: module 'inspect' has no attribute 'getmoduleinfo'

I don't recall getting this with earlier versions of the toolkit but that was in an older Streams environment.  Maybe I skipped some step in setting up this one?

Edit:

These are the reported versions:
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

The doc I found state that getmoduleinfo has been deprecated since version 3.3 and to use importlib.machinery instead.  So this might just be that I'm using a newer version of python that generates an error instead of a warning.

**Comment by ddebrunner** [comment]
Thanks - will look into it, but only Python 3.5 is supported at the moment.

**Comment by jms90h5** [comment]
Hi Dan,

I figured that might be the case.  But given that this is an early access version I figured it would probably work with the current release of Anaconda.  I'll see what it takes to roll back to an older version.

**Comment by jms90h5** [comment]
Rolling back to Anaconda3 v4.1.1 did resolve the issue since that version includes python 3.5 rather than 3.6.

Although I can guess it's already on your roadmap, a feature request for some future version would be for compatibility with python 3.6 since that's the default version included in the default/current version of Anaconda3.

**Comment by ddebrunner** [comment]
Re-opening as we want to remove use of the deprecated method.

Thanks for the update on 4.1.1/3.6.

Note the Streaming Analytics service on IBM Bluemix is using Anancoda3 v4.1.1(?) with Python 3.5.

**Comment by ddebrunner** [comment]
Probable fix:
```
$ diff ./opt/python/packages/streamsx/scripts/extract.py ./opt/python/packages/streamsx/scripts/extract.py.bkup 
445c445
<         name = inspect.getmodulename(mf)
---
>         (name, suffix, mode, mtype)  = inspect.getmoduleinfo(mf)
```
