### ISSUE TITLE
Support host placement

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#9]
IBM Streams allows host placement of operators, for example run a InetSource operator on an ingest host.

Similar functionality needs to exist in the Java Application API, at least by host tags.

First pass may be where the Java application can use tags that are those defined by the instance, application says run on 'ingest' host, and one or more hosts in the instance must have that tag.

Subsequent changes could add a mapping, where the application defines 'ingest' but it is mapped to 'httpingest' on the instance.

**Comment by ddebrunner** [comment]
Thinking about a TContainer interface that represents the logical container a function (or operator for SPL invocations) is executing in. TStream (maybe TWindow as well) would have a TContainer getContainer() method. Simple applications can just ignore containers.

Would have methods like:

// Host tag support
void addHostTags(String ...tags)
Set<String> getHostTags()

// Co-location support
void colocate(TContainer ... containers)
void colocate(TStream<?> streams)  // shorthand for colocate(stream.getContainer()) for each stream

**Comment by ddebrunner** [comment]
Maybe even a tag based scheme for fusing (colocation)
`void addColocateTags(String ...tags)`
`Set<String> getColocateTags()`

TContainers would then be colocated if they matched colocate tags completely.

Might even be better to only have a tagging scheme.

**Comment by ddebrunner** [comment]
I wonder if the TSink being added in pull request #123 should be TContainer?

**Comment by dlaboss** [comment]
- we already have isolate() and lowLatency() for affecting fusion.  TContainer would add other ways.  Can/should there be any unification?  e.g., should isolate() just be a convenience op that can also be achieved via TContainer?
- today, each parallel channel is isolated, how would fusing the channels be achieved?  are there other TBD fusion scenarios we need to support?
- "scoping" for host location or fusing control?  e.g., a way to state "applies downstream too" so a processing pipeline can inherit the same host placement / fusion specs?
- seems a tad unfortunate that to express host placement constraints and/or (more complicated?) fusion I will have to breakup my processing pipeline and introduce intermediate variables. e.g.,
```
	top.endlessSource(…).filter(...).transform(...)….
```
to place the source on "ingest" and to fuse filter() with it, I'll have to:
```
	TStream source = top.endlessSource(...);
	source.getContainer().addHostTag("ingest");
	source.getContainer().addColocationTag("source");
	TStream filtered = source.filter(...);
	filtered.getContainer().addColocationTag("source");
	filtered.transform(...)…
```
vs perhaps something along the lines of the following - which would also allow for more complicated and reusable fusion and/or host placement specs:
```
	ContainerSpec cs = new ContainerSpec(new FusionSpec("source"),
							 new HostPlacementSpec("ingest"));
	top.endlessSource(cs, …).filter(cs, …).transform(…);
```

**Comment by ddebrunner** [comment]
Good points.

I think there are different types of fusion, and thus may require different apis. Isolate/lowlatency are logical instructions at the stream level, while container based fusion is somewhat more physical. One case I'm trying to solve is the ability for invocations of an operator like HTTPTupleView to be fused, regardless of their streams.

I think we do need a logical fusing, fuse with inputs/outputs, and maybe that is along the lines of isolate()/lowLatency().

One issue with the `top.endlessSource(cs, …)` is you now need two variants of each functional method, potentially confusing the api.
