### ISSUE TITLE
test.TestSubmitArgumentsMethodsNew failures/issue.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#908]
test.TestSubmitArgumentsMethodsNew tests were failing when no STREAMS_DOMAIN_ID or STREAMS_INSTANCE_ID was set. I initially only skipped the test `test_SameCredential` as it is the only one that results in a submitted job. 

However I found I had to skip all three (*) for now because even though the submit fails for the other two it fails trying to do a `streamtool geturl`.  Now since there is no request to access the REST apis in these test, why is geturl being executed at all?

I guess I was expecting that the failure would happen early , basically a verification of the matching credentials even before trying to do anything.

@wmarshall484 @ibmkendrick 

(*) all three skipped in commit 8f81272dd792afd7773fbd0eed25c110174bbf58

**Comment by ddebrunner** [comment]
@ibmkendrick 
The additional issue is that test `test_SameCredential` leaves a job running in the instance.

I was going to add a `sr.job.cancel()` but then realised that the user/password are incorrect for the instance.

**Comment by ibmkendrick** [comment]
In the current code, the creation of `StreamsConnection` would immediately try to get the resource URL.  The is done via `streamtool` or a REST call.   So we want to delay this action until a REST API request is truly needed.

This also exposed another problem.  In the case where the resource URL is obtained through a 
REST call, the Session object has not had a chance to be customized by the user yet.  (User can only customize the Session object after the `StreamsConnection` object is constructed).  So the code really shouldn't call any REST API during the `StreamsConnection` object construction phase anyways.

And the job cancel shouldn't need to call any REST APIs in this case, so I'll investigate that as well.
