### ISSUE TITLE
Documentation for TWindow.last(int n) should make clear that n is upper bound only

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.topology#91]
I had assumed that `TWindow.last(int n)` would always yield a list of tuples of size `n` when I used it in an aggregation. However, based on the behavior, it appears that `n` is actually the upper bound, and the list can be smaller than `n`.

See the check I put in my code here: https://github.com/scotts/streamsx.demo.logwatch/blob/master/topology/src/streamsx/demo/logwatch/topology/SuspectFinder.java#L17. Without that check, I would perform the aggregation, and emit a tuple, based on a window size of 1.

I assume that this is the intended behavior - if it is, we should clarify that in the documentation, as it was a surprise to me.

**Comment by ddebrunner** [comment]
Addressed in pull request #92

**Comment by scotts** [comment]
It looks like we can close this issue - or are we waiting until these pull requests go into the mainline release?

**Comment by ddebrunner** [comment]
will close when the pull release is merged
