### ISSUE TITLE
Accessing streamsx.ec can fail when using topology and 'dilled' class instances.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#932]
The class has a reference to hte module  `streamsx.ec` and dill preserves the state of the module which has `_supported = False`, as it is only supported when running inside a PE.

This not supported state is preserved through dill and thus on the Streams instance side the module becomes unsupported.

This causes a modified version of the tweepy app to fail that uses an application configuration.

**Comment by ddebrunner** [comment]
Fixed by having a `streamsx.ec._State` class that maintains module level state in a class level attribute `_state`.

All module state is moved to the `_State` class, i.e. the _supported flag and the thread local for the context pointers. 

Tested manually, got a version of the tweepy app running loading credentials from the application configuration.

Will submit pr after running all Python 3 tests.

**Comment by wmarshall484** [comment]
Why is `_State` not serialized along with `streamsx.ec`? I assume it's because the user code makes not explicit reference to `streamsx.ec._State`?

**Comment by ddebrunner** [comment]
There's more to the fix than I mentioned, you are right `_State` is serialized (I think) but I work around it.

When declaring the topology `_State._state` gets set to `None`.  Now we only attempt to import the C++ module `_streamsx_ec` when one of the methods is called (from a running topology). Thus when we check to see if the module is supported (only Streams 4.2 and Python 3.5 currently) the first time we see `_state` is None so try to import `_streamsx_ec`.  Based upon the success of that we set `_state` to reflect supported or not, and if supported set up the additional state we need.

**Comment by ddebrunner** [comment]
We may not need the class `_State` but it made it obvious that which variable was being used.

Previously there were two module level variables, and I couldn't see how to access them from a function, without the function thinking they were locals.

Plus encapsulating all the required state in a class seemed cleaner.
