### ISSUE TITLE
Maintiain parallel/partition information in a JSON object

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#94]
Currently parallel (partition) information is in several attributes of the operator:
https://github.com/IBMStreams/streamsx.topology/wiki/JSON-Format-for-Graphs

would be cleaner if the parallel/partition information was self-contained in its own JSON object and and kept in the operator object under the key 'partition'.

**Comment by wmarshall484** [comment]
Fixed by #1556
