### ISSUE TITLE
Names of sab files generated in a Jupyter notebook contain useless extraneous numbers

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.topology#951]
When developing in a notebook, generated bundle/application names are of the form:
```
ipythoninput22085adf68644.hello_world.sab
ipythoninput22085adf68644::hello_world
```
Is it possible for the `ipythoninput*` prefix be changed to something more meaningful, like `python` or `ipython`?

**Comment by ddebrunner** [comment]
Background is we take the module name as the SPL namespace.

You can explicitly set it as `topo = Topology(namespace="my.ns")`.

Not sure how we would know a name is not the one the user wants, e.g. maybe that is their module name.

**Comment by ddebrunner** [comment]
Just to push back a little, given the title, what makes 'python' or 'ipython' "meaningful"?

**Comment by queeniema** [comment]
Thanks, did not know about `namespace`. 

I would say that `ipython` is meaningful because you know that it is a Python app and that it was developed in a notebook. Also helps to distinguish between SPL and Python apps in the Streams Console.

**Comment by ddebrunner** [comment]
Doesn't `ipythoninput22085adf68644` also tell you it was a Python app from a notebook?

**Comment by queeniema** [comment]
Yes, but those extraneous numbers are an eyesore... that's my main gripe.

**Comment by ddebrunner** [comment]
that's not what the description says :-)

**Comment by queeniema** [comment]
Another suggestion is to use the Jupyter notebook name as the namespace. Currently, when a Python exception is logged in a PE's console logs (`pec.pe.pe-id.stdouterr` files), the file name isn't helpful; it doesn't tell you what the source is.

Example: `File "<ipython-input-5-2942cf8a7cc2>", line 27, in divideByZeroIfFive`

**Comment by ddebrunner** [comment]
@queeniema  Do you know the Python calls to get the name of the notebook?

**Comment by queeniema** [comment]
Did a Google search and this looks promising: https://mail.scipy.org/pipermail/ipython-dev/2014-June/014096.html

**Comment by markheger** [comment]
name looks like below
'bundlePath': '/home/wsuser/work/notebooks.BasicTemplate.sab'
