### ISSUE TITLE
Issues encountered when attempting to run on 2.7 run.

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.topology#962]
1) When setting python home : 
``streamtool setproperty --application-ev PYTHONHOME=/home/streamsadmin/anaconda``
Do not include a trailing "/", if you do a PYTHONHOME not defined error is thrown at runtime. 

2) The machine that application runs on requires that 'future' (no s) be installed. If it is not 
installed, a runtime error is thrown saying

``from builtins import super``

failed to import.

**Comment by ddebrunner** [comment]
I can't reproduce 1) on Python 2.7 or 3.5.

![image](https://cloud.githubusercontent.com/assets/3769612/24874582/04c1dd30-1dda-11e7-8473-5e6e4ce1dbf2.png)

**Comment by ddebrunner** [comment]
Also verified using path with a trailing slash works when using distributed.

**Comment by ddebrunner** [comment]
2.7 not supported any more.
