### ISSUE TITLE
Can TStream.publish and TStream.subscribe be generated differently based on streams context

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#963]
When developing microservices, we use TStream.publish and subscribe often in our applications.  They work great work the application is submitted with the StreamsContext.Type.Distributed as SPL code is generated and run in distributed mode.

However, when we develop the application, we often also try to launch as EMBEDDED (so we can use the Java debugger), or STANDALONE.  In those cases, the code generation will fail because Import and Export are not supported.  So, our solution to debugging is to change our code to comment out all publish and subscribe, debug in embedded mode. When testing in distributed mode, we will uncomment the code again.

I am wondering if it makes sense to change the code generation to a print for publish when the application is running in embdded / standalone mode.  When I am debugging, I am interested in seeing what's being published.  For import, I am wondering if we can somehow figure out how to generate dummy data that simulate the import.

**Comment by ddebrunner** [comment]
You can do this yourself if you setup some indicator you are in debugging mode.
```
s = ...
if (in_debug_mode) {
    s.print();
} else {
    s.publish("mytopic");
}
```

You could create a static `publish` method that by convention you always use to publish a stream and encapsulate the debug mode logic in that.

Similar for subscribe.

**Comment by ddebrunner** [comment]
Publish/subscribe do not cause code generation errors in STANDALONE mode do they?

**Comment by ddebrunner** [comment]
Closing this as what alternative to provide is most likely specific to the application, especially for subscribe. The technique to consistently use a different function has been provided.
