### ISSUE TITLE
New folder req'd for notebook images

### ISSUE THREAD

**Issue by jakrmpotic** [IBMStreams/streamsx.topology#972]
@wmarshall484 @ddebrunner Can one of you  create a new folder in the following location?
 https://github.com/IBMStreams/streamsx.topology/tree/master/samples/python/topology/notebooks

We would like to store images for our topology notebooks in that folder. Once we store them, we can then use the URLs to show the images in our DSX Jupyter notebooks.

**Comment by ddebrunner** [comment]
Creating the folder in your clone will create in the master when you add a file there.

**Comment by jakrmpotic** [comment]
@ddebrunner I tried what you suggested, but got a 403 error. I think I don't have access to do as you suggested. 
(py35) Jasnas-MacBook-Pro:notebooks jasna$ ls
Images		MultiGraph	NetDemo		PyAPI		ViewDemo
(py35) Jasnas-MacBook-Pro:notebooks jasna$ git status
On branch 0412jasna
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   Images/clickservicecredential.png
	new file:   Images/servicename.png

(py35) Jasnas-MacBook-Pro:notebooks jasna$  git push --set-upstream origin 0412jasna
remote: Permission to IBMStreams/streamsx.topology.git denied to jakrmpotic.
fatal: unable to access 'https://github.com/IBMStreams/streamsx.topology.git/': The requested URL returned error: 403

**Comment by ddebrunner** [comment]
Right - you can't push to IBMStreams repo as you are not a committer. You push to your fork and then create a pull request from that.
