### ISSUE TITLE
Request: Java wrappers for the Streams REST api's similar to the python REST api wrappers

### ISSUE THREAD

**Issue by yvchan** [IBMStreams/streamsx.topology#980]
Adding java based wrappers to streamsx.topology so that we can access the IBM Streams REST api's more easily would be very useful.

**Comment by yvchan** [comment]
The idea is to prove a set of read only java classes that map to the existing json structures provided by the REST api's in IBM Streams.

A RestAPIClient would setup a connection to the Streams Domain, and retrieve the relevant information when requested.

The methods to get the information would come from the RestAPIClient class, and will return the associated class object back.

**Comment by ddebrunner** [comment]
Gson should be used for JSON handling, it should simplify/automate creating Java POJOs from the JSON returned from the REST requests.

**Comment by ddebrunner** [comment]
@yvchan Please submit the contributor agreement if you plan to work on these.

https://github.com/IBMStreams/administration/blob/master/contribute.md

Thanks!

**Comment by yvchan** [comment]
@ddebrunner I've submitted via e-mail to Pete.

**Comment by ddebrunner** [comment]
@yvchan I created a branch `java_rest_api` that can be used as the development branch for Java rest api.

Please issue any pull requests against that branch!

**Comment by ddebrunner** [comment]
Initial version is is main and v1_7 branches.
