### ISSUE TITLE
Doc for Python schema needs improvement

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#981]
I looked at the [doc](http://ibmstreams.github.io/streamsx.topology/doc/releases/1.6/pythondoc/streamsx.topology.schema.html?highlight=schema#module-streamsx.topology.schema) for the schema module and it does not say anywhere  how to define a schema or that you just need to define it as a string. This is important especially when invoking SPL operators from Python.

**Comment by natashadsilva** [comment]
Are there plans to respin the API doc at  http://ibmstreams.github.io/streamsx.topology/doc/pythondoc/ soon  pick up these changes?

**Comment by ddebrunner** [comment]
In a couple of hours :-)
