### ISSUE TITLE
could we update httpcomponents-client from 4.3.6 to 4.5.3?

### ISSUE THREAD

**Issue by yvchan** [IBMStreams/streamsx.topology#988]
The existing httpcomponents-client-4.3.6 libraries have an issue in that is preventing the use of basic authentication with https sites, see [issue](https://issues.apache.org/jira/browse/HTTPCLIENT-1604) for details.   I encountered this while looking at creating some java wrappers to the ibm streams rest api's per issue #980 

From what I could see with a grep of "apache.http" in the code, I found only a few places that appear to be using this: 

```
streamsx.topology$  grep -l -I -R apache.http * | grep -v httpcomponents-client
java/src/com/ibm/streamsx/topology/internal/streaminganalytics/RestUtils.java
java/src/com/ibm/streamsx/topology/internal/context/remote/BuildServiceRemoteRESTWrapper.java
java/src/com/ibm/streamsx/topology/internal/context/Contexts.java
java/src/com/ibm/streamsx/topology/internal/context/AnalyticsServiceStreamsContext.java
```
Given the 4.3.6 libraries are from 2014 and it's usage is fairly limited, it maybe a good idea to move this up to a newer level.   I was able to confirm that the latest 4.5.3 code didn't cause the same problem in the code i'm writing.

**Comment by ddebrunner** [comment]
Any idea why the current use of the library works with basic authentication?

Are you using the same approach?

**Comment by yvchan** [comment]
The approaches are a bit different, as the classes in topology internal are using the CloseableHttpClient whereas I've created the connections via the fluent api's (i.e, using org.apache.http.client.fluent.Executor, Request and Response). however, the issue reported in 4.3.6 affects the base HttpClient that is included in both.

I've created a pull request https://github.com/IBMStreams/streamsx.topology/pull/990 with the sample code so that you can see what I have.

**Comment by ddebrunner** [comment]
Not needed atm.
