### ISSUE TITLE
Remote Build Service not GA in PythonDoc

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#991]
In the doc here, there is a big warning saying that the build service from Bluemix is not GA:

http://ibmstreams.github.io/streamsx.topology/doc/pythondoc/streamsx.topology.context.html?highlight=context#module-streamsx.topology.context

Is this still true ?

**Comment by ddebrunner** [comment]
It's addressed in pr #986

Will be pushed to the doc soon.

**Comment by ddebrunner** [comment]
Fixed - docs are updated.
