### ISSUE TITLE
API Doc: No visible link to streamsx.spl module

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#992]
There is now a link to streamsx.spl.spl on the home page but not to the streamsx.spl package.  Thus there's no easy way to find out how to invoke SPL operators from Python unless you know browse the index.  Searching for "operator" using the search feature turns up a "Searching" page that brings no results.

**Comment by ddebrunner** [comment]
There's a link in the section that mentions SPL operators can be invoked.

http://ibmstreams.github.io/streamsx.topology/doc/releases/1.6/pythondoc/streamsx.topology.topology.html#spl-operators

**Comment by natashadsilva** [comment]
I think it would be helpful to add a link to that in the main page.  The main page serves as an overview of the various features and even though that is not the focus of the API, there is a lot of value gained from being able to invoke operators from Python.  Adding a sentence under "Python application api for Streams" and a link to the relevant package would be enough.
