### ISSUE TITLE
Doc missing or incomplete for some Python modules

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#994]
topology.context.submit:
doc for `context.submit` says:

> config (dict) – Configuration for the submission.

It should say that the keys are constants from the `ConfigParams` class.

Next, the return type says:
> 
> Returns:	
> 
> Result of the submission. For details of what is contained see the ContextTypes constant passed as ctxtype.

But the doc for those constants is incomplete. 
The doc for `context.submit `should be updated to say that the return value is always a `SubmissionResult` object. `SubmissionResult`, in turn, should state that the `results` attribute of that class will contain relevant information that depends on the submission context, e.g. the path to the  generated toolkit if TOOLKIT is used, e.t.c
But the results attribute is not documented in the API.

**Comment by natashadsilva** [comment]
topology.mqtt module is missing documenation for the `publish` and `subscribe` methods.  
No documentation for the View class in the API (as mentioned in issue #995)

**Comment by markheger** [comment]
Required changes in documentation for Python modules:
### streamsx.topology.context.submit
* Parameter config(dict) needs to reference `ConfigParams`

### streamsx.topology.context.SubmissionResult
* Document `results` attribute

**Comment by markheger** [comment]
1.14.12
