### ISSUE TITLE
Python: What is the correct way to read data from a view?

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#995]
```
topo = Topology("Files")
csv_schema = StreamSchema("tuple<rstring ticker, rstring date, rstring time, float64 askprice>")
file_data = op.Source(topo, "spl.adapter::FileSource",schema=csv_schema,params = {'file': '/home/streamsadmin/workspace/TradesApp/data/trades.csv'})
filtered_quotes = file_data.stream.filter(valid, "filtered")
view = filtered_quotes.view(start=True, sample_size=100)

sc = StreamsConnection(username="streamsadmin",password="passw0rd")
sc.session.verify=False
result = context.submit("DISTRIBUTED", topo.graph,  config={context.ConfigParams.STREAMS_CONNECTION :sc})
print( "Now retrieving from view...\n\n")
q = view.start_data_fetch()
for x in iter(q.get, None):
   f.writeLines(x)

```
I just get this message printed out repeatedly:
`/opt/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)`

**Comment by natashadsilva** [comment]
Also, there is no documentation for the View class in the API.

**Comment by ddebrunner** [comment]
@wmarshall484

**Comment by ddebrunner** [comment]
Documentation in 1.12 has been improved for views.

The message is a warning from the requests library. 1.12 tries to ensure it only occurs once.
